// Practice bank — 68 worked exam problems from the source files.
//
// Sources:
//   MM-S1A: Math Medic Section I Part A (28 MCQ, no calc)
//   MM-S1B: Math Medic Section I Part B (12 MCQ, calc)
//   MM-S2A: Math Medic Section II Part A (2 FRQ, calc)
//   MM-S2B: Math Medic Section II Part B (2 FRQ, no calc)
//   CB:     College Board preview (24 MCQ + 4 FRQ)

export type ProblemSource = "MM-S1A" | "MM-S1B" | "MM-S2A" | "MM-S2B" | "CB";
export type UnitId = "u1" | "u2" | "u3";

export type MCQProblem = {
  id: string;
  source: ProblemSource;
  number: string;
  type: "mcq";
  unitId: UnitId;
  topicHint?: string; // free-text hint about which topic this teaches toward
  calc: boolean;
  prompt: string;
  choices: string[];
  answer: number;
  explain: string;
  takeaway: string;
};

export type FRQProblem = {
  id: string;
  source: ProblemSource;
  number: string;
  type: "frq";
  unitId: UnitId;
  topicHint?: string;
  calc: boolean;
  prompt: string;
  parts: { label: string; prompt: string; solution: string[]; answer?: string }[];
};

export type Problem = MCQProblem | FRQProblem;

// ──────────────────────────────────────────────────────────────────────
// MM-S1A: 28 MCQ, no calculator
// ──────────────────────────────────────────────────────────────────────

const MM_S1A: Problem[] = [
  {
    id: "mms1a-1", source: "MM-S1A", number: "Q1", type: "mcq", unitId: "u1", calc: false,
    topicHint: "1.2 Differences from a table",
    prompt: "Table: $x = 0, 3, 6, 9, 12, 15, 18$ and $f(x) = 100, 80, 62, 46, 32, 20, 10$. What is the function model?",
    choices: ["Linear", "Exponential", "Logarithmic", "Quadratic"],
    answer: 3,
    explain: "Compute first differences (over equal $\\Delta x = 3$): −20, −18, −16, −14, −12, −10. They themselves change by +2 each step — constant change in ARC, signature of a quadratic.",
    takeaway: "Constant first differences = linear. Constant change in first differences (= constant 2nd differences) = quadratic.",
  },
  {
    id: "mms1a-2", source: "MM-S1A", number: "Q2", type: "mcq", unitId: "u1", calc: false,
    topicHint: "1.3 End behavior",
    prompt: "$g(x) = -2x^5 + 7x^4 + 3x^2 - 8x + 1$. Determine $\\lim_{x\\to\\infty} g(x)$ and $\\lim_{x\\to-\\infty} g(x)$.",
    choices: ["both $+\\infty$", "both $-\\infty$", "$+\\infty$ and $-\\infty$ resp.", "$-\\infty$ and $+\\infty$ resp."],
    answer: 3,
    explain: "Leading term $-2x^5$. Odd degree, negative coefficient: as $x \\to \\infty$, $g \\to -\\infty$. As $x \\to -\\infty$, $g \\to +\\infty$.",
    takeaway: "End behavior is fully determined by the leading term. Memorize the four cases.",
  },
  {
    id: "mms1a-3", source: "MM-S1A", number: "Q3", type: "mcq", unitId: "u1", calc: false,
    topicHint: "1.5 Holes vs zeros vs VAs",
    prompt: "$f(x) = \\dfrac{x^2 + 2x - 15}{(x+4)(x-a)}$. For exactly one positive x-intercept and one VA, find $a$.",
    choices: ["$a = -5$", "$a = 3$", "$a = 4$", "$a = 5$"],
    answer: 0,
    explain: "Factor numerator: $(x+5)(x-3)$. If $a = -5$: $(x+5)$ cancels — hole at $-5$, VA at $-4$, single positive zero at 3. ✓",
    takeaway: "Common factors cancel and produce HOLES, not zeros or VAs.",
  },
  {
    id: "mms1a-4", source: "MM-S1A", number: "Q4", type: "mcq", unitId: "u1", calc: false,
    topicHint: "1.1 Increasing × concavity",
    prompt: "On a graph (typical Math Medic), where is the function increasing at a decreasing rate?",
    choices: ["$x < 1$", "$1 < x < 3$", "$3 < x < 5$", "$x > 5$"],
    answer: 1,
    explain: "Increasing at decreasing rate = increasing AND concave down. The portion going up while curving downward — like the top of a hill before peak.",
    takeaway: "Match the four behavior phrases to (monotonicity, concavity) pairs reflexively.",
  },
  {
    id: "mms1a-5", source: "MM-S1A", number: "Q5", type: "mcq", unitId: "u2", calc: false,
    topicHint: "2.7 Combining logs",
    prompt: "$f(x) = 3 \\log x + \\log(100 x^2)$. Simplest form?",
    choices: ["$2 + 3 \\log x$", "$2 + 5 \\log x$", "$5 \\log x$", "$3 \\log(100 x)$"],
    answer: 1,
    explain: "$3 \\log x + \\log 100 + \\log x^2 = 3 \\log x + 2 + 2 \\log x = 5 \\log x + 2$.",
    takeaway: "Aggressively split logs. Constants like $\\log 100 = 2$ drop out.",
  },
  {
    id: "mms1a-6", source: "MM-S1A", number: "Q6", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.6 Sec asymptotes ↔ cos zeros",
    prompt: "$f(x) = \\cos x$, $g(x) = \\sec x$, $h(x) = \\arccos x$. Which is true?",
    choices: [
      "Domain of $f$ = range of $g$",
      "Zeros of $f$ = zeros of $h$",
      "Domain of $g$ = domain of $h$",
      "Zeros of $f$ = vertical asymptotes of $g$",
    ],
    answer: 3,
    explain: "$\\cos x = 0$ at $\\pi/2 + k\\pi$. Those are exactly where $\\sec x = 1/\\cos x$ blows up.",
    takeaway: "Cos zeros and sec VAs share the same x-coordinates. Always.",
  },
  {
    id: "mms1a-7", source: "MM-S1A", number: "Q7", type: "mcq", unitId: "u2", calc: false,
    topicHint: "2.5 Inverse from graph (odd function)",
    prompt: "$h$ is odd, only $x \\le 0$ portion shown. From the graph, $h(-1) = 2$. Find $h^{-1}(-2)$.",
    choices: ["$-2$", "$-1$", "$1$", "$2$"],
    answer: 2,
    explain: "Odd ⇒ $h(-x) = -h(x)$. So $h(1) = -h(-1) = -2$, meaning $h^{-1}(-2) = 1$.",
    takeaway: "For odd function with one half shown: flip sign of $c$, look up, negate the result.",
  },
  {
    id: "mms1a-8", source: "MM-S1A", number: "Q8", type: "mcq", unitId: "u2", calc: false,
    topicHint: "2.3 Doubling time",
    prompt: "Revenue doubles every 9 months. $r(0) = 32{,}000$. $t$ in months. Model?",
    choices: ["$32{,}000 \\cdot 2^{9t}$", "$32{,}000 \\cdot 9^{t/2}$", "$32{,}000 \\cdot 2^9 t$", "$32{,}000 \\cdot 2^{t/9}$"],
    answer: 3,
    explain: "Doubling time $T = 9$ ⇒ $P(t) = P_0 \\cdot 2^{t/T} = 32{,}000 \\cdot 2^{t/9}$.",
    takeaway: "'Doubles every $T$' ⇒ exponent is $t/T$.",
  },
  {
    id: "mms1a-9", source: "MM-S1A", number: "Q9", type: "mcq", unitId: "u1", calc: false,
    prompt: "Subway fare $\\$2.90$ per ride, capped at 12 rides/week, 30 rides total over 2 weeks, ≥5 rides week 1. Cost-vs-rides graph?",
    choices: [
      "Linear throughout",
      "Linear up then plateau, repeated each week",
      "Exponential growth",
      "Logarithmic",
    ],
    answer: 1,
    explain: "Cost grows linearly until cap (12), then plateau. New week resets — linear up again then plateau. Two linear-rising segments separated by plateaus.",
    takeaway: "Capped rates → piecewise linear with plateaus.",
  },
  {
    id: "mms1a-10", source: "MM-S1A", number: "Q10", type: "mcq", unitId: "u1", calc: false,
    topicHint: "1.7 Transformations",
    prompt: "$f$ is an exponential ($f(0)=6, f(1)=12, f(2)=24, \\ldots$). $g$ table: $g(0)=-3/2, g(1)=-3, g(2)=-6$. Which transformation?",
    choices: ["$g(x) = -f(x-2)$", "$g(x) = f(x+2)$", "$g(x) = -f(x)/4$", "$g(x) = f(-x-2)$"],
    answer: 0,
    explain: "Test $g(0) = -f(-2) = -(6/4) = -3/2$ ✓. $g(1) = -f(-1) = -3$ ✓. $g(2) = -f(0) = -6$ ✓.",
    takeaway: "When matching transformations, plug in tabulated values until exactly one option fits.",
  },
  {
    id: "mms1a-11", source: "MM-S1A", number: "Q11", type: "mcq", unitId: "u1", calc: false,
    topicHint: "1.1 ARC of linear",
    prompt: "For linear $f$, $\\dfrac{f(7) - f(3)}{4} = -5$. Find $\\dfrac{f(20) - f(12)}{8}$.",
    choices: ["$-10$", "$-5$", "$0$", "$5$"],
    answer: 1,
    explain: "ARC of a linear function is the slope, constant on any interval. Both ARCs equal $-5$.",
    takeaway: "Linear ARC is constant. Defining property.",
  },
  {
    id: "mms1a-12", source: "MM-S1A", number: "Q12", type: "mcq", unitId: "u2", calc: false,
    topicHint: "2.6 Inverse of exponential",
    prompt: "$h$ has property: $\\Delta x = 1 \\Rightarrow$ output multiplies by $1.5$. Graph of $h^{-1}$?",
    choices: ["Linear, decreasing", "Exponential, increasing", "Logarithmic, increasing, concave down", "Polynomial"],
    answer: 2,
    explain: "$h$ is exponential with base 1.5. Inverse of an increasing exponential is an increasing logarithm: $(1, 0)$, VA at $x = 0$, concave down.",
    takeaway: "Exp ↔ log under inversion. Increasing exp inverts to increasing log.",
  },
  {
    id: "mms1a-13", source: "MM-S1A", number: "Q13", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.4 Reading sinusoid",
    prompt: "Graph: max 5, min −1, period $4\\pi$, trough at $x = 0$. Equation?",
    choices: [
      "$3\\cos(\\tfrac{1}{2}x) + 2$",
      "$3\\sin(\\tfrac{1}{2}x) + 2$",
      "$-3\\cos(\\tfrac{1}{2}x) + 2$",
      "$-3\\sin(\\tfrac{1}{2}x) + 2$",
    ],
    answer: 2,
    explain: "$A = 3$, $D = 2$, $B = 2\\pi/(4\\pi) = 1/2$. Trough at $x = 0$ ⇒ negative cosine. Verify: $-3\\cos 0 + 2 = -1$ ✓.",
    takeaway: "Pick sin/cos based on what's at $x = 0$. Trough at 0 ⇒ $-A\\cos$.",
  },
  {
    id: "mms1a-14", source: "MM-S1A", number: "Q14", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.9 Polar relative max",
    prompt: "$r = 4 - 7\\sin\\theta$. At which $(r, \\theta)$ is there a relative max?",
    choices: ["$(11, \\pi/2)$", "$(11, \\pi)$", "$(-3, \\pi/2)$", "$(11, 3\\pi/2)$"],
    answer: 3,
    explain: "$r$ is max when $-7\\sin\\theta$ is largest, i.e. $\\sin\\theta = -1$ at $\\theta = 3\\pi/2$. Then $r = 4 - 7(-1) = 11$.",
    takeaway: "$r = a + b\\sin\\theta$: max where $\\sin\\theta = -\\text{sign}(b)$.",
  },
  {
    id: "mms1a-15", source: "MM-S1A", number: "Q15", type: "mcq", unitId: "u1", calc: false,
    prompt: "$p(x) = (x+7)(x^2+25)(x-3)$. $h(x) = x \\cdot p(x)$. Real and imaginary zeros of $h$?",
    choices: ["2 real, 2 imaginary", "2 real, 4 imaginary", "3 real, 2 imaginary", "4 real, 0 imaginary"],
    answer: 2,
    explain: "$p$ zeros: $-7$ real, $\\pm 5i$ imaginary, $3$ real. Multiplying by $x$ adds real zero $0$. Total: real $\\{-7, 0, 3\\}$ (3), imaginary $\\{\\pm 5i\\}$ (2).",
    takeaway: "$x^2 + a^2$ factors as $(x - ai)(x + ai)$ — two imaginary zeros.",
  },
  {
    id: "mms1a-16", source: "MM-S1A", number: "Q16", type: "mcq", unitId: "u1", calc: false,
    topicHint: "1.8 Residual plots",
    prompt: "Comparing two models for a dataset: A's residuals scatter randomly, B's show a clear curved pattern. Which model is appropriate?",
    choices: ["Model A", "Model B", "Both equally", "Neither"],
    answer: 0,
    explain: "Random residuals = good fit. Patterned residuals = systematic mismatch. A is appropriate.",
    takeaway: "Shape of residuals tells fit quality, not magnitude.",
  },
  {
    id: "mms1a-17", source: "MM-S1A", number: "Q17", type: "mcq", unitId: "u1", calc: false,
    prompt: "$g$ has zero at $x = 9.217$ (mult 2) and zero at $x = -3 + 0.251i$. Min degree?",
    choices: ["$2$", "$3$", "$4$", "$5$"],
    answer: 2,
    explain: "Multiplicity 2 contributes 2. Complex zero requires conjugate pair (2 more). Total: 4.",
    takeaway: "Complex zeros of real polynomials come in conjugate pairs.",
  },
  {
    id: "mms1a-18", source: "MM-S1A", number: "Q18", type: "mcq", unitId: "u2", calc: false,
    topicHint: "2.4 Composition",
    prompt: "$h(x) = f(g(x))$. From sources, $g(3) = 5$ and $f(5) = 0$. Find $h(3)$.",
    choices: ["$0$", "$3$", "$5$", "Undefined"],
    answer: 0,
    explain: "$h(3) = f(g(3)) = f(5) = 0$.",
    takeaway: "Mixed-source composition: read inner from one source, look up in the other.",
  },
  {
    id: "mms1a-19", source: "MM-S1A", number: "Q19", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.8 Reflection identity",
    prompt: "Angle $\\theta$ with terminal ray through $A = (-1.9, -0.64)$ on circle of radius 2. Find $\\cos(2\\pi - \\theta)$.",
    choices: ["$0.32$", "$-0.32$", "$0.95$", "$-0.95$"],
    answer: 3,
    explain: "$\\cos(2\\pi - \\theta) = \\cos\\theta = x/r = -1.9/2 = -0.95$.",
    takeaway: "$\\cos(2\\pi - \\theta) = \\cos\\theta$. Memorize.",
  },
  {
    id: "mms1a-20", source: "MM-S1A", number: "Q20", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.4 Sinusoidal modeling",
    prompt: "$d(t) = 10\\cos(\\tfrac{\\pi}{3}(t+1)) + 90$ for $0 \\le t \\le 24$. Maximum and where?",
    choices: ["max 90 at $t = 0$", "max 100 at $t = 5$", "max 110 at $t = 5$", "max 100 at $t = 0$"],
    answer: 1,
    explain: "Cos max is 1, giving $d = 100$. Need $\\tfrac{\\pi}{3}(t+1) = 2\\pi k$ ⇒ $t = -1, 5, 11, \\ldots$. First in interval: $t = 5$.",
    takeaway: "For $A\\cos(\\cdot) + D$, max = $D + |A|$. Set argument to $2\\pi k$ to find $t$.",
  },
  {
    id: "mms1a-21", source: "MM-S1A", number: "Q21", type: "mcq", unitId: "u1", calc: false,
    prompt: "Cubic $f$ with rel min at $x = -3$ and rel max at $x = 5$. Decreasing intervals?",
    choices: ["$(-\\infty, -3) \\cup (5, \\infty)$", "$(-3, 5)$", "$(-\\infty, 5)$", "$(5, \\infty)$"],
    answer: 0,
    explain: "Min before max in $x$ ⇒ negative leading coefficient. Profile: dec → min → inc → max → dec. Decreasing on $(-\\infty, -3) \\cup (5, \\infty)$.",
    takeaway: "Order of rel max/min on the x-axis tells you the sign of the leading coefficient for a cubic.",
  },
  {
    id: "mms1a-22", source: "MM-S1A", number: "Q22", type: "mcq", unitId: "u1", calc: false,
    topicHint: "1.7 Range under transformation",
    prompt: "$g$ has range $[-2, 7]$. $f$ is $g$ dilated vertically by 2 then translated 3 units left. Range of $f$?",
    choices: ["$[-4, 14]$", "$[-1, 14]$", "$[-4, 11]$", "$[-2, 7]$"],
    answer: 0,
    explain: "Vertical dilation by 2: $[2 \\cdot -2, 2 \\cdot 7] = [-4, 14]$. Horizontal translation doesn't change range.",
    takeaway: "Horizontal moves leave range alone. Vertical moves transform range.",
  },
  {
    id: "mms1a-23", source: "MM-S1A", number: "Q23", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.7 Trig equation",
    prompt: "$f(x) = -8\\sin x + 1 = 5$. All real solutions?",
    choices: [
      "$x = \\pi/6 + 2\\pi k$",
      "$x = 5\\pi/6 + 2\\pi k$",
      "$x = \\pm \\pi/6 + 2\\pi k$",
      "$x = 7\\pi/6 + 2\\pi k$ or $x = 11\\pi/6 + 2\\pi k$",
    ],
    answer: 3,
    explain: "$\\sin x = -1/2$. Reference angle $\\pi/6$. Sin negative in QIII and QIV: $7\\pi/6$ and $11\\pi/6$.",
    takeaway: "Sin negative? Two solutions per cycle in QIII and QIV.",
  },
  {
    id: "mms1a-24", source: "MM-S1A", number: "Q24", type: "mcq", unitId: "u2", calc: false,
    topicHint: "2.2 Exponential through 2 points",
    prompt: "$f(x) = ab^x$ passes through $(1, 48)$ and $(3, 27)$. Find $a$ and $b$.",
    choices: ["$a = 27, b = 4/3$", "$a = 64, b = 3/4$", "$a = 48, b = 1/2$", "$a = 81, b = 2/3$"],
    answer: 1,
    explain: "$ab = 48$, $ab^3 = 27$. Divide: $b^2 = 27/48 = 9/16$ ⇒ $b = 3/4$. Then $a = 48/(3/4) = 64$.",
    takeaway: "For $ab^x$ through two points, divide to eliminate $a$ and solve for $b$ first.",
  },
  {
    id: "mms1a-25", source: "MM-S1A", number: "Q25", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.8 Sum identity",
    prompt: "$W = (c, d)$, $P = (a, b)$ on unit circle. $\\theta$ to $W$, $\\beta$ to $P$. $\\sin(\\theta + \\beta) = ?$",
    choices: ["$ad + bc$", "$ac + bd$", "$ad - bc$", "$ab + cd$"],
    answer: 0,
    explain: "Unit circle: $\\sin\\theta = d$, $\\cos\\theta = c$, $\\sin\\beta = b$, $\\cos\\beta = a$. Sum identity: $\\sin\\theta\\cos\\beta + \\cos\\theta\\sin\\beta = da + cb$.",
    takeaway: "Sum identity — read coordinates off unit circle directly.",
  },
  {
    id: "mms1a-26", source: "MM-S1A", number: "Q26", type: "mcq", unitId: "u1", calc: false,
    prompt: "$h(x) = f(x)/g(x)$, $f$ and $g$ both quadratic, $f$ opens up, $g$ opens down. End behavior of $h$?",
    choices: ["$\\to 0$", "$\\to \\infty$", "$\\to$ a positive constant", "$\\to$ a negative constant"],
    answer: 3,
    explain: "Equal degrees ⇒ HA at ratio of leading coefs. Positive over negative = negative.",
    takeaway: "Equal-degree rational ⇒ HA at coefficient ratio.",
  },
  {
    id: "mms1a-27", source: "MM-S1A", number: "Q27", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.5 Tangent concavity",
    prompt: "$f(\\theta) = \\tan(\\theta/2)$ on $7\\pi < \\theta < 8\\pi$. Behavior?",
    choices: [
      "Increasing, concave down",
      "Increasing, concave up",
      "Decreasing, concave down",
      "Decreasing, concave up",
    ],
    answer: 0,
    explain: "Sub $u = \\theta/2 \\in (7\\pi/2, 4\\pi)$. Modulo period $\\pi$, this matches $(\\pi/2, \\pi)$: tan goes from $-\\infty$ to 0, increasing, $\\tan u < 0$ ⇒ concave DOWN.",
    takeaway: "$\\tan'' \\propto \\tan$. Concavity matches sign of tan. Always increasing between VAs.",
  },
  {
    id: "mms1a-28", source: "MM-S1A", number: "Q28", type: "mcq", unitId: "u3", calc: false,
    topicHint: "3.9 Polar curve",
    prompt: "$r = -3\\cos(2\\theta)$ on $\\pi/4 < \\theta < \\pi/2$. Where is the point?",
    choices: [
      "Below polar axis, getting closer to origin",
      "Above polar axis, getting farther from origin",
      "Below polar axis, getting farther from origin",
      "Above polar axis, getting closer to origin",
    ],
    answer: 1,
    explain: "At $\\theta = \\pi/4$: $r = 0$. At $\\theta = \\pi/2$: $r = 3$. $r > 0$ in QI ⇒ point in QI (above), distance increasing.",
    takeaway: "Sign of $r$ + quadrant of $\\theta$ → actual quadrant.",
  },
];

// ──────────────────────────────────────────────────────────────────────
// MM-S1B: 12 MCQ, calculator
// ──────────────────────────────────────────────────────────────────────

const MM_S1B: Problem[] = [
  {
    id: "mms1b-1", source: "MM-S1B", number: "Q1", type: "mcq", unitId: "u1", calc: true,
    prompt: "$f(x) = |-0.2x^2 - 3x + 4| + 2$. Where is $f$ decreasing AND concave down?",
    choices: ["$(-7.5, 1.232)$", "$(-16.232, -7.5)$", "$(-7.5, 1.232)$ only the right portion", "Nowhere"],
    answer: 0,
    explain: "Inside parabola opens down with vertex $-7.5$. $g \\ge 0$ on $(-16.232, 1.232)$ — concave down there. Decreasing AND concave down: only $(-7.5, 1.232)$.",
    takeaway: "$|q(x)|$ flips parabola where $q < 0$, swapping concavity.",
  },
  {
    id: "mms1b-2", source: "MM-S1B", number: "Q2", type: "mcq", unitId: "u2", calc: true,
    prompt: "Sequence $6.5, 3.25, 1.625, 0.8125, 0.40625$. Common ratio?",
    choices: ["$0.5$", "$0.4$", "$0.6$", "$-3.25$"],
    answer: 0,
    explain: "$3.25 / 6.5 = 0.5$. Confirm: $1.625 / 3.25 = 0.5$.",
    takeaway: "Geometric: same ratio between consecutive terms.",
  },
  {
    id: "mms1b-3", source: "MM-S1B", number: "Q3", type: "mcq", unitId: "u2", calc: true,
    prompt: "Algae start at 2500, double every 5 hours. After 24 hours?",
    choices: ["$\\approx 7500$", "$\\approx 32{,}000$", "$\\approx 69{,}644$", "$\\approx 100{,}000$"],
    answer: 2,
    explain: "$2500 \\cdot 2^{24/5} \\approx 2500 \\cdot 27.86 \\approx 69{,}644$.",
    takeaway: "Doubling time: $P_0 \\cdot 2^{t/T}$.",
  },
  {
    id: "mms1b-4", source: "MM-S1B", number: "Q4", type: "mcq", unitId: "u1", calc: true,
    prompt: "Coefficient of $x^3$ in $(2x^3 - 5)^7$?",
    choices: ["$218{,}750$", "$140$", "$-15625$", "$2 \\cdot 7$"],
    answer: 0,
    explain: "Binomial term: $\\binom{7}{k}(2x^3)^{7-k}(-5)^k$. Want $x^3$ ⇒ $3(7-k) = 3$ ⇒ $k = 6$. Coef $= \\binom{7}{6}(2)(-5)^6 = 7 \\cdot 2 \\cdot 15625 = 218{,}750$.",
    takeaway: "Binomial expansion: write general term, set exponent, solve for $k$.",
  },
  {
    id: "mms1b-5", source: "MM-S1B", number: "Q5", type: "mcq", unitId: "u1", calc: true,
    prompt: "Exponential regression on meal-plan costs gives smallest residual $-\\$20.57$. What does that mean?",
    choices: [
      "Model fits perfectly there",
      "Model overestimates by \\$20.57",
      "Model underestimates by \\$20.57",
      "Data point is an outlier",
    ],
    answer: 1,
    explain: "Negative residual = predicted > actual = model overestimates.",
    takeaway: "Negative residual = overestimate. Positive = underestimate.",
  },
  {
    id: "mms1b-6", source: "MM-S1B", number: "Q6", type: "mcq", unitId: "u2", calc: true,
    prompt: "$\\text{dB} = 10 \\log_{10}(I/I_0)$. Conversation 60 dB, damaging 95 dB. Ratio of intensities?",
    choices: ["$\\approx 35$", "$\\approx 100$", "$\\approx 1000$", "$\\approx 3162$"],
    answer: 3,
    explain: "Difference 35 dB ⇒ $\\log(\\text{ratio}) = 3.5$ ⇒ ratio $= 10^{3.5} \\approx 3162$.",
    takeaway: "Every 10 dB = 10× intensity.",
  },
  {
    id: "mms1b-7", source: "MM-S1B", number: "Q7", type: "mcq", unitId: "u3", calc: true,
    prompt: "$f(t) = a\\cos(b(t+c)) + d$ with $a, b, c, d > 0$. Graph period 8. Find $b$.",
    choices: ["$0.785$", "$1.273$", "$\\pi$", "$2\\pi$"],
    answer: 0,
    explain: "$b = 2\\pi / \\text{period} = 2\\pi/8 = \\pi/4 \\approx 0.785$.",
    takeaway: "$b = 2\\pi/P$ always.",
  },
  {
    id: "mms1b-8", source: "MM-S1B", number: "Q8", type: "mcq", unitId: "u2", calc: true,
    prompt: "$f(x) = 12\\log_2(x+5) + 6$. $g = f^{-1}$. Find $x$ s.t. $g(x) = 0$.",
    choices: ["$0$", "$5$", "$11.5$", "$33.863$"],
    answer: 3,
    explain: "$g(x) = 0 \\iff f(0) = x$. $f(0) = 12\\log_2 5 + 6 \\approx 33.863$.",
    takeaway: "$f^{-1}(b) = a$ ⇔ $f(a) = b$. Use this to avoid actual inversion.",
  },
  {
    id: "mms1b-9", source: "MM-S1B", number: "Q9", type: "mcq", unitId: "u3", calc: true,
    prompt: "Express $-3 + 5i$ in polar form.",
    choices: [
      "$5(\\cos\\pi + i\\sin\\pi)$",
      "$\\sqrt{34}(\\cos 0.86 + i\\sin 0.86)$",
      "$5.831\\cos(2.111) + i \\cdot 5.831\\sin(2.111)$",
      "$8(\\cos\\pi/3 + i\\sin\\pi/3)$",
    ],
    answer: 2,
    explain: "$r = \\sqrt{9+25} = \\sqrt{34} \\approx 5.831$. Q2: $\\theta = \\pi - \\arctan(5/3) \\approx 2.111$.",
    takeaway: "QII: $\\theta = \\pi - |\\arctan|$.",
  },
  {
    id: "mms1b-10", source: "MM-S1B", number: "Q10", type: "mcq", unitId: "u3", calc: true,
    prompt: "Simplify $\\sec\\theta\\csc\\theta - \\cot\\theta$.",
    choices: ["$\\cos\\theta$", "$\\tan\\theta$", "$\\sin\\theta$", "$1$"],
    answer: 1,
    explain: "$1/(\\cos\\sin) - \\cos/\\sin = (1 - \\cos^2)/(\\sin\\cos) = \\sin^2/(\\sin\\cos) = \\tan\\theta$.",
    takeaway: "Common denominator + Pythagorean substitution.",
  },
  {
    id: "mms1b-11", source: "MM-S1B", number: "Q11", type: "mcq", unitId: "u3", calc: true,
    prompt: "Tide period 14 hr, high 5.83 ft at $t=9$, low 0.52 ft. Height at $t=20$?",
    choices: ["$0.5$", "$2.4$", "$3.766$", "$5.83$"],
    answer: 2,
    explain: "$h(t) = 2.655\\cos(\\tfrac{\\pi}{7}(t-9)) + 3.175$. $h(20) \\approx 3.766$.",
    takeaway: "Build model first, evaluate second.",
  },
  {
    id: "mms1b-12", source: "MM-S1B", number: "Q12", type: "mcq", unitId: "u3", calc: true,
    prompt: "$r(\\theta) = \\sin(2\\theta)$ on $[7\\pi/12, 3\\pi/4]$. Distance behavior?",
    choices: [
      "Increasing at increasing rate",
      "Increasing at decreasing rate",
      "Decreasing at increasing rate",
      "Decreasing at decreasing rate",
    ],
    answer: 1,
    explain: "$r$ goes from $-1/2$ to $-1$. $|r|$ goes from $1/2$ to $1$ — increasing. Rate of increase $-2\\cos(2\\theta)$ goes from $\\sqrt{3}$ to 0 — decreasing.",
    takeaway: "Distance = $|r|$, not $r$. Track magnitude separately when $r < 0$.",
  },
];

// ──────────────────────────────────────────────────────────────────────
// MM-S2A: 2 FRQ, calculator
// ──────────────────────────────────────────────────────────────────────

const MM_S2A: Problem[] = [
  {
    id: "mms2a-1", source: "MM-S2A", number: "Q1", type: "frq", unitId: "u1", calc: true,
    prompt: "$f$ table: $f(2)=1, f(4)=2, f(8)=3, f(16)=4, f(32)=5$. $g(x) = (x^2-x-12)/(x^2-9)$.",
    parts: [
      { label: "(A)(i)", prompt: "Find $h(8/3)$ where $h(x) = f(g(x))$.",
        solution: ["Factor $g(x) = \\dfrac{(x-4)(x+3)}{(x-3)(x+3)}$, simplifying to $\\dfrac{x-4}{x-3}$ for $x \\ne -3$.",
          "$g(8/3) = \\dfrac{8/3 - 4}{8/3 - 3} = \\dfrac{-4/3}{-1/3} = 4$.",
          "$f(g(8/3)) = f(4) = 2$ from table."],
        answer: "$h(8/3) = 2$" },
      { label: "(A)(ii)", prompt: "Find $f^{-1}(4)$.",
        solution: ["$f^{-1}(4)$ is the $x$ where $f(x) = 4$.", "From table: $f(16) = 4$."],
        answer: "$f^{-1}(4) = 16$" },
      { label: "(B)(i)", prompt: "Vertical asymptotes of $g$.",
        solution: ["After simplification: denominator $(x-3)$ remaining, no cancellation.", "VA at $x = 3$."],
        answer: "$x = 3$" },
      { label: "(B)(ii)", prompt: "Holes of $g$, in limit notation.",
        solution: ["$(x+3)$ cancels — hole at $x = -3$.", "$\\lim_{x \\to -3} g(x) = \\dfrac{-7}{-6} = \\dfrac{7}{6}$."],
        answer: "Hole at $(-3, 7/6)$" },
      { label: "(C)(i)", prompt: "Best model class for $f$.", solution: ["Inputs double; outputs add 1."], answer: "Logarithmic" },
      { label: "(C)(ii)", prompt: "Reason.", solution: [
        "As inputs are multiplied by a constant factor (2), outputs increase by a constant amount (1).",
        "This multiplicative-input/additive-output relationship is the defining characteristic of a logarithmic function.",
        "Specifically $f(x) = \\log_2 x$.",
      ] },
    ],
  },
  {
    id: "mms2a-2", source: "MM-S2A", number: "Q2", type: "frq", unitId: "u1", calc: true,
    prompt: "Spotify subscribers: 2015 (28M), 2016 (48M), 2017 (71M), 2018 (96M), 2019 (124M), 2020 (155M), 2021 (180M), 2022 (205M).",
    parts: [
      { label: "(A)(i)", prompt: "Quadratic system using 2015, 2018, 2021.",
        solution: ["With $x$ = years after 2015: $f(0) = c = 28$; $f(3) = 9a + 3b + c = 96$; $f(6) = 36a + 6b + c = 180$."] },
      { label: "(A)(ii)", prompt: "Solve for $a, b, c$.",
        solution: ["From $c = 28$: simplify to $9a + 3b = 68$ and $36a + 6b = 152$.",
          "Eliminate $b$: multiply first by 2 and subtract → $18a = 16$ → $a = 8/9 \\approx 0.889$.",
          "Then $b = (68 - 9 \\cdot 8/9)/3 = 60/3 = 20$.",
          "Final: $f(x) = \\tfrac{8}{9}x^2 + 20x + 28$."],
        answer: "$a = 8/9, b = 20, c = 28$" },
      { label: "(B)(i)", prompt: "ARC 2015 → 2017 from data.",
        solution: ["From data: $f(0) = 28$, $f(2) = 71$.", "$\\text{ARC} = (71 - 28)/2 = 21.5$."],
        answer: "$21.5$ million per year" },
      { label: "(B)(ii)", prompt: "Interpretation sentence.",
        solution: ["From 2015 to 2017, the number of Spotify premium subscribers increased by an average of approximately 21.5 million per year."] },
      { label: "(B)(iii)", prompt: "Compare ARCs from 2017 → $p > 3$ to ARC from 2015 → 2017.",
        solution: ["Model is concave up ($a = 8/9 > 0$).",
          "For concave-up functions, ARCs increase as the interval moves right.",
          "Therefore ARCs starting at 2017 are GREATER than the 2015-2017 ARC.",
          "Verify: 2017 → 2022 gives $(205-71)/5 = 26.8 > 21.5$ ✓."] },
      { label: "(C)", prompt: "When does $f(x)$ first exceed 250 million?",
        solution: ["Solve $\\tfrac{8}{9}x^2 + 20x + 28 = 250$ → $4x^2 + 90x - 999 = 0$.",
          "$x = \\dfrac{-90 + \\sqrt{8100 + 15984}}{8} \\approx 8.149$.",
          "$f(8) \\approx 244.9 < 250$. $f(9) = 280 > 250$.",
          "First integer year where $f$ exceeds 250 million corresponds to $x = 9$ → 2024."],
        answer: "Year 2024" },
    ],
  },
];

// ──────────────────────────────────────────────────────────────────────
// MM-S2B: 2 FRQ, no calc
// ──────────────────────────────────────────────────────────────────────

const MM_S2B: Problem[] = [
  {
    id: "mms2b-3", source: "MM-S2B", number: "Q3", type: "frq", unitId: "u3", calc: false,
    prompt: "Metronome at 40 BPM (1 beat = pendulum from extreme to extreme). Furthest left $-4$, furthest right $+4$. At $t = 0$, pendulum at furthest left.",
    parts: [
      { label: "Setup", prompt: "Period and parameters.",
        solution: ["Beat = half period. 40 beats/min = 1 beat per 1.5 sec = period 3 sec.",
          "Amplitude 4, midline 0."] },
      { label: "(A)", prompt: "Five points $F, G, J, K, P$.",
        solution: ["Quarter-period 0.75 sec.",
          "$F = (0.75, 0)$ — midline rising. $G = (1.5, 4)$ — first max. $J = (2.25, 0)$ — midline falling. $K = (3, -4)$ — second min. $P = (3.75, 0)$ — midline rising."] },
      { label: "(B)", prompt: "$h(t) = a\\cos(b(t+c)) + d$. Find $a, b, c, d$.",
        solution: ["$|a| = 4$, $d = 0$, $b = 2\\pi/3$.",
          "At $t = 0$, $h = -4$ (min). Use $a = -4$, $c = 0$: $h(0) = -4\\cos 0 = -4$ ✓."],
        answer: "$a = -4, b = 2\\pi/3, c = 0, d = 0$" },
      { label: "(C)(i)", prompt: "On $(2.25, 3)$, behavior of $h$?",
        solution: ["$h$ goes from 0 (midline) to $-4$ (min). Negative AND decreasing."],
        answer: "$h$ is negative and decreasing" },
      { label: "(C)(ii)", prompt: "Rate of change of $h$ on $(2.25, 3)$.",
        solution: ["At $t = 2.25$: midline crossing — slope is most negative.",
          "At $t = 3$: at minimum — slope is 0.",
          "Slope (the number) is going from very negative toward 0 — INCREASING.",
          "Equivalently, the curve is concave up."],
        answer: "Rate of change is increasing" },
    ],
  },
  {
    id: "mms2b-4", source: "MM-S2B", number: "Q4", type: "frq", unitId: "u3", calc: false,
    prompt: "Multi-part trig and log.",
    parts: [
      { label: "(A)(i)", prompt: "Solve $g(x) = 6\\sin^2 x - 5\\sin x = 4$ on $[\\pi/2, 3\\pi/2]$.",
        solution: ["Let $u = \\sin x$: $6u^2 - 5u - 4 = 0$.",
          "Quadratic formula: $u = (5 \\pm 11)/12$ → $u = 4/3$ (reject, $|\\sin| \\le 1$) or $-1/2$.",
          "$\\sin x = -1/2$ in $[\\pi/2, 3\\pi/2]$. QIII: $x = 7\\pi/6$. (QIV: $11\\pi/6$ outside interval.)"],
        answer: "$x = 7\\pi/6$" },
      { label: "(A)(ii)", prompt: "Solve $h(x) = 4000 \\cdot 2^{5x} + 100 = 6100$.",
        solution: ["$2^{5x} = 3/2$.",
          "$5x = \\log_2(3/2) = \\log_2 3 - 1$.",
          "$x = (\\log_2 3 - 1)/5$."],
        answer: "$x = (\\log_2 3 - 1)/5$" },
      { label: "(B)(i)", prompt: "Rewrite $j(x) = 3\\log x^2 - \\log\\sqrt{x}$ as a single log.",
        solution: ["$3\\log x^2 = \\log x^6$. $\\log\\sqrt{x} = \\log x^{1/2}$.",
          "$j(x) = \\log x^6 - \\log x^{1/2} = \\log x^{11/2}$."],
        answer: "$\\log x^{11/2}$ or $\\log\\sqrt{x^{11}}$" },
      { label: "(B)(ii)", prompt: "Rewrite $k(x) = (\\sin x \\cos x)/(1 - \\sin^2 x)$ with one $\\tan$.",
        solution: ["$1 - \\sin^2 x = \\cos^2 x$.",
          "$k(x) = \\sin x \\cos x / \\cos^2 x = \\sin x / \\cos x = \\tan x$."],
        answer: "$\\tan x$" },
      { label: "(C)", prompt: "$m(x) = 2\\sin(3x) - 5 = -7$. All solutions.",
        solution: ["$\\sin(3x) = -1$.",
          "$3x = -\\pi/2 + 2\\pi k$.",
          "$x = -\\pi/6 + (2\\pi/3) k$."],
        answer: "$x = -\\pi/6 + (2\\pi/3)k$" },
    ],
  },
];

// ──────────────────────────────────────────────────────────────────────
// CB Preview: 24 MCQ + 4 FRQ
// ──────────────────────────────────────────────────────────────────────

const CB: Problem[] = [
  // FRQs
  {
    id: "cb-frq1", source: "CB", number: "FRQ 1", type: "frq", unitId: "u1", calc: true,
    prompt: "$f$ table: $f(1) = -10, f(2) = -5, f(3) = 4, f(4) = 17, f(5) = 34$. $g(x) = (x^3 - 14x - 27)/(x + 2)$.",
    parts: [
      { label: "(A)(i)", prompt: "Find $h(5) = (g \\circ f)(5)$.",
        solution: ["$f(5) = 34$. $g(34) = (39304 - 476 - 27)/36 = 38801/36 \\approx 1077.806$."],
        answer: "$h(5) \\approx 1077.806$" },
      { label: "(A)(ii)", prompt: "$f^{-1}(4)$.",
        solution: ["From table: $f(3) = 4$, so $f^{-1}(4) = 3$."],
        answer: "$3$" },
      { label: "(B)(i)", prompt: "Solve $g(x) = 3$.",
        solution: ["$x^3 - 14x - 27 = 3(x + 2) = 3x + 6$ → $x^3 - 17x - 33 = 0$.",
          "Numerical solve: only one real root, $x \\approx 4.886$."],
        answer: "$x \\approx 4.886$" },
      { label: "(B)(ii)", prompt: "End behavior of $g$ as $x \\to -\\infty$.",
        solution: ["For large $|x|$, $g(x) \\sim x^3/x = x^2$.",
          "As $x \\to -\\infty$, both numerator and denominator are negative, ratio is $\\sim |x|^2 \\to +\\infty$."],
        answer: "$\\lim_{x \\to -\\infty} g(x) = +\\infty$" },
      { label: "(C)(i)", prompt: "Best model class for $f$.",
        solution: ["First differences (Δx = 1): 5, 9, 13, 17 (not constant).",
          "Second differences: 4, 4, 4 (constant!).",
          "Constant second differences = quadratic."],
        answer: "Quadratic" },
      { label: "(C)(ii)", prompt: "Reason.",
        solution: ["Over equal-length intervals, the second differences $\\Delta^2 f$ are constant at 4.",
          "A function whose second differences are constant over equal-length input intervals is quadratic."] },
    ],
  },
  {
    id: "cb-frq2", source: "CB", number: "FRQ 2", type: "frq", unitId: "u2", calc: true,
    prompt: "Knowledge retention $R(t) = a + b\\ln(t+1)$, $t$ months. $R(0) = 75$, $R(3) = 70.84$.",
    parts: [
      { label: "(A)(i)", prompt: "Set up equations.",
        solution: ["$R(0) = a + b \\cdot 0 = a = 75$.",
          "$R(3) = a + b\\ln 4 = 70.84$."] },
      { label: "(A)(ii)", prompt: "Find $a, b$.",
        solution: ["$a = 75$. From $75 + b\\ln 4 = 70.84$: $b = -4.16/\\ln 4 \\approx -3.001$."],
        answer: "$a = 75, b \\approx -3.001$" },
      { label: "(B)(i)", prompt: "ARC from $t = 0$ to $t = 3$.",
        solution: ["$\\text{ARC} = (70.84 - 75)/3 = -4.16/3 \\approx -1.387$ points/month."],
        answer: "$\\approx -1.387$ points per month" },
      { label: "(B)(ii)", prompt: "Interpret.",
        solution: ["From $t = 0$ to $t = 3$ months, the score decreased by an average of approximately 1.387 points per month."] },
      { label: "(B)(iii)", prompt: "Compare ARCs from $t = 3$ to $t = p$ (where $p > 3$) with the ARC from 0 to 3.",
        solution: ["Model is decreasing AND concave up (second derivative of $b\\ln(t+1)$ is $-b/(t+1)^2 > 0$ since $b < 0$).",
          "For decreasing concave-up functions, ARCs become LESS NEGATIVE (closer to 0) as the interval moves right.",
          "Therefore ARCs from 3 to $p > 3$ are GREATER than $-1.387$."] },
      { label: "(C)", prompt: "For how many years is $R$ appropriate (drop ≥ 1 pt/year)?",
        solution: ["End-of-year scores at $t = 12, 24, 36, 48$.",
          "$R(12) \\approx 67.30$, $R(24) \\approx 65.34$, $R(36) \\approx 64.17$, $R(48) \\approx 63.32$.",
          "Yearly drops: 1.97 (year 1→2 ✓), 1.18 (year 2→3 ✓), 0.85 (year 3→4 ✗).",
          "Model appropriate through year 3."],
        answer: "3 years" },
    ],
  },
  {
    id: "cb-frq3", source: "CB", number: "FRQ 3", type: "frq", unitId: "u3", calc: false,
    prompt: "Fan blade, 5 rotations/sec, point B is 6 inches from center, center 20 inches above table. At $t = 0$, B at top.",
    parts: [
      { label: "Setup", prompt: "Period, amplitude, midline.",
        solution: ["Period = 1/5 = 0.2 sec. Distance to table: midline 20, amplitude 6, max 26, min 14."] },
      { label: "(A)", prompt: "Five points $F, G, J, K, P$.",
        solution: ["Quarter-period 0.05.",
          "$F = (0, 26)$ max. $G = (0.05, 20)$ midline falling. $J = (0.10, 14)$ min. $K = (0.15, 20)$ midline rising. $P = (0.20, 26)$ next max."] },
      { label: "(B)", prompt: "$h(t) = a\\sin(b(t+c)) + d$. Find $a, b, c, d$.",
        solution: ["$a = 6, d = 20, b = 2\\pi/0.2 = 10\\pi$.",
          "Sine peaks when argument = $\\pi/2$, so $bc = \\pi/2$ → $c = (\\pi/2)/(10\\pi) = 1/20$."],
        answer: "$a = 6, b = 10\\pi, c = 1/20, d = 20$" },
      { label: "(C)(i)", prompt: "On $(0.15, 0.20)$, behavior of $h$.",
        solution: ["Goes from midline (20) up to max (26). Positive (always > 0) and increasing."],
        answer: "Positive and increasing" },
      { label: "(C)(ii)", prompt: "Concavity and rate of change.",
        solution: ["Going from midline up to max — curve flattens at peak. Concave DOWN.",
          "Slope is most positive at midline crossing, decreases toward 0 at max. Rate of change is DECREASING."],
        answer: "Concave down, rate of change decreasing" },
    ],
  },
  {
    id: "cb-frq4", source: "CB", number: "FRQ 4", type: "frq", unitId: "u3", calc: false,
    prompt: "Multi-part: log, trig, exponential, equation solving.",
    parts: [
      { label: "(A)(i)", prompt: "Rewrite $g(x) = 3\\ln x - \\tfrac{1}{2}\\ln x$ as one ln.",
        solution: ["$(3 - 1/2)\\ln x = (5/2)\\ln x = \\ln x^{5/2}$."],
        answer: "$\\ln x^{5/2} = \\ln\\sqrt{x^5}$" },
      { label: "(A)(ii)", prompt: "$h(x) = (\\sin^2 x - 1)/\\cos x$, with $\\cos$ once.",
        solution: ["$\\sin^2 x - 1 = -(1 - \\sin^2 x) = -\\cos^2 x$.",
          "$h(x) = -\\cos^2 x / \\cos x = -\\cos x$."],
        answer: "$-\\cos x$" },
      { label: "(B)(i)", prompt: "Solve $j(x) = 2\\sin x \\cos x - \\cos x = 0$ on $[0, \\pi/2]$.",
        solution: ["Factor: $\\cos x(2\\sin x - 1) = 0$.",
          "$\\cos x = 0$ → $x = \\pi/2$ (in interval).",
          "$2\\sin x - 1 = 0$ → $\\sin x = 1/2$ → $x = \\pi/6$."],
        answer: "$x = \\pi/6, \\pi/2$" },
      { label: "(B)(ii)", prompt: "$k(x) = 8e^{3x} - e = 3e$.",
        solution: ["$8e^{3x} = 4e$ → $e^{3x} = e/2$.",
          "$3x = \\ln(e/2) = 1 - \\ln 2$.",
          "$x = (1 - \\ln 2)/3$."],
        answer: "$x = (1 - \\ln 2)/3$" },
      { label: "(C)", prompt: "$m(x) = \\cos(2x) + 4 = 9/2$.",
        solution: ["$\\cos(2x) = 1/2$.",
          "$2x = \\pm\\pi/3 + 2\\pi k$.",
          "$x = \\pm\\pi/6 + \\pi k$."],
        answer: "$x = \\pm\\pi/6 + \\pi k$" },
    ],
  },
  // MCQs
  {
    id: "cb-mcq-1", source: "CB", number: "MCQ Q1", type: "mcq", unitId: "u1", calc: false,
    prompt: "End behavior of $p(x) = -4x^5 + 3x^2 + 1$.",
    choices: [
      "Both ends $+\\infty$",
      "Both ends $-\\infty$",
      "Left $-\\infty$, right $+\\infty$",
      "Left $+\\infty$, right $-\\infty$",
    ],
    answer: 3,
    explain: "Negative leading coefficient, odd degree (5). Right $\\to -\\infty$, left $\\to +\\infty$.",
    takeaway: "Odd negative leading: right goes down.",
  },
  {
    id: "cb-mcq-2", source: "CB", number: "MCQ Q2", type: "mcq", unitId: "u1", calc: false,
    prompt: "$W(t)$ is increasing on $(0, 6)$ and $(18, 30)$. Concave up on $(0, 3)$, concave down on $(3, 6)$, etc. Where is $W$ increasing AND concave down?",
    choices: ["$(0, 3)$", "$(3, 6)$", "$(18, 30)$", "$(0, 6)$"],
    answer: 1,
    explain: "Need both conditions: increasing (yes on $(3, 6)$) AND concave down (yes there). Answer: $(3, 6)$.",
    takeaway: "Two-condition graph reading — match each condition's interval, intersect.",
  },
  {
    id: "cb-mcq-3", source: "CB", number: "MCQ Q3", type: "mcq", unitId: "u1", calc: false,
    prompt: "Want zero at $x = 3$, hole at $x = 1$, VA at $x = 2$. Which rational function?",
    choices: [
      "$\\dfrac{x^2 - 4x + 3}{x^2 - 3x + 2}$",
      "$\\dfrac{x^2 - 4x + 4}{x^2 - 3x + 2}$",
      "$\\dfrac{x^2 - 1}{x^2 - 4}$",
      "$\\dfrac{x - 3}{x - 1}$",
    ],
    answer: 0,
    explain: "Factor: $\\dfrac{(x-1)(x-3)}{(x-1)(x-2)}$. $(x-1)$ cancels (hole at 1). After: $\\dfrac{x-3}{x-2}$ — zero at 3, VA at 2.",
    takeaway: "Build rational functions by encoding zeros, holes, VAs as factors.",
  },
  {
    id: "cb-mcq-4", source: "CB", number: "MCQ Q4", type: "mcq", unitId: "u1", calc: false,
    prompt: "$p$ is odd. $p(3) = -4$ is a relative max. What about $p(-3)$?",
    choices: ["$-4$, rel min", "$4$, rel min", "$4$, rel max", "$-4$, rel max"],
    answer: 1,
    explain: "Odd: $p(-3) = -p(3) = 4$. Rel max at $(3, -4)$ reflects through origin to $(-3, 4)$, which is now a rel MIN (sign flipped).",
    takeaway: "Odd functions: rel max ↔ rel min under origin reflection.",
  },
  {
    id: "cb-mcq-5", source: "CB", number: "MCQ Q5", type: "mcq", unitId: "u1", calc: false,
    prompt: "$g(x) = x^3 - 3x^2 - 18x$. $h(x) = x^2 - 2x - 35$. Domain of $k = h/g$?",
    choices: ["All reals", "$x \\ne 7, -5$", "$x \\ne -3, 0, 6$", "$x \\ne 0$"],
    answer: 2,
    explain: "$g(x) = x(x-6)(x+3)$, zeros at $0, 6, -3$. No common factors with $h$. Domain excludes $g$'s zeros.",
    takeaway: "Factor both. No common factors ⇒ domain excludes denominator zeros only.",
  },
  {
    id: "cb-mcq-6", source: "CB", number: "MCQ Q6", type: "mcq", unitId: "u1", calc: false,
    prompt: "Quartic graph with double-root touch at $x = -5$, simple roots at $-1$ and $8$, opens up. Equation?",
    choices: [
      "$0.25(x+5)(x+1)(x-8)$",
      "$0.25(x+5)^2(x+1)(x-8)$",
      "$0.25(x-5)^2(x-1)(x+8)$",
      "$-0.25(x+5)^2(x+1)(x-8)$",
    ],
    answer: 1,
    explain: "Quartic, positive leading. Double root at $-5$ (touch), simple at $-1$ and $8$ (cross).",
    takeaway: "Multiplicity 2 = touch. Match roots and end behavior to factored form.",
  },
  {
    id: "cb-mcq-7", source: "CB", number: "MCQ Q7", type: "mcq", unitId: "u1", calc: false,
    prompt: "$f(-2) = 5$, $g(x) = 3f(\\tfrac{1}{2}x) + 5$. $g(-4) = ?$",
    choices: ["$5$", "$15$", "$20$", "$25$"],
    answer: 2,
    explain: "$g(-4) = 3 f(\\tfrac{1}{2} \\cdot -4) + 5 = 3f(-2) + 5 = 3 \\cdot 5 + 5 = 20$.",
    takeaway: "Plug in carefully when applying transformations to specific values.",
  },
  {
    id: "cb-mcq-8", source: "CB", number: "MCQ Q8", type: "mcq", unitId: "u2", calc: false,
    prompt: "Expand $\\log_{10}(kz/w^2)$.",
    choices: [
      "$\\log k + \\log z - 2\\log w$",
      "$\\log k - \\log z + 2\\log w$",
      "$\\log(k+z) - 2\\log w$",
      "$\\log k \\log z - 2\\log w$",
    ],
    answer: 0,
    explain: "Quotient: $\\log(kz) - \\log w^2$. Product on top: $\\log k + \\log z$. Power: $2\\log w$.",
    takeaway: "Apply log rules in order: quotient, product, power.",
  },
  {
    id: "cb-mcq-9", source: "CB", number: "MCQ Q9", type: "mcq", unitId: "u2", calc: false,
    prompt: "Geometric: $g_1 = 8, g_2 = 4, g_3 = 2, g_4 = 1$. Explicit form?",
    choices: ["$g_n = 8 \\cdot 2^n$", "$g_n = 4 \\cdot (1/2)^{n-2}$", "$g_n = 8 \\cdot (1/2)^n$", "$g_n = 8(n-1)$"],
    answer: 1,
    explain: "$r = 1/2$. Standard form $g_n = g_1 \\cdot r^{n-1} = 8(1/2)^{n-1}$, equivalent to $4(1/2)^{n-2}$.",
    takeaway: "Geometric explicit: $g_1 \\cdot r^{n-1}$. Equivalent forms by index shifting.",
  },
  {
    id: "cb-mcq-10", source: "CB", number: "MCQ Q10", type: "mcq", unitId: "u2", calc: false,
    prompt: "$f(x) = 3^x + x^2$, $g(3) = -2$. $f(g(3)) = ?$",
    choices: ["$-1$", "$1/9 + 4 = 37/9$", "$11$", "$-37/9$"],
    answer: 1,
    explain: "$f(-2) = 3^{-2} + 4 = 1/9 + 4 = 37/9$.",
    takeaway: "Negative exponents: $b^{-n} = 1/b^n$.",
  },
  {
    id: "cb-mcq-11", source: "CB", number: "MCQ Q11", type: "mcq", unitId: "u1", calc: false,
    prompt: "Residual plot for a linear model shows a clear curved (parabolic) pattern.",
    choices: [
      "Linear model not appropriate",
      "Linear model appropriate",
      "Need more data",
      "The data has outliers",
    ],
    answer: 0,
    explain: "Patterned residuals → systematic mismatch → wrong model class.",
    takeaway: "Curved residual plot for linear model = wrong class.",
  },
  {
    id: "cb-mcq-12", source: "CB", number: "MCQ Q12", type: "mcq", unitId: "u2", calc: false,
    prompt: "Value increases 6.1% per quarter, $M(0) = 54$M, $t$ in years (4 quarters/year). Model?",
    choices: ["$54(1.061)^t$", "$54(1.061)^{t/4}$", "$54 \\cdot 4(1.061)^t$", "$54(1.061)^{4t}$"],
    answer: 3,
    explain: "$4t$ quarters in $t$ years: $M(t) = 54(1.061)^{4t}$.",
    takeaway: "Convert time units by adjusting exponent.",
  },
  {
    id: "cb-mcq-13", source: "CB", number: "MCQ Q13", type: "mcq", unitId: "u2", calc: false,
    prompt: "$h(d) = A_0 (0.5)^{d/8}$, $d$ in days. As function of hours $t$ ($d = t/24$)?",
    choices: ["$A_0(0.5)^t$", "$A_0(0.5)^{t/8}$", "$A_0(0.5)^{t/24}$", "$A_0(0.5)^{t/192}$"],
    answer: 3,
    explain: "Substitute $d = t/24$: exponent $= (t/24)/8 = t/192$.",
    takeaway: "Substitute the new variable expression for the old in the exponent.",
  },
  {
    id: "cb-mcq-14", source: "CB", number: "MCQ Q14", type: "mcq", unitId: "u2", calc: false,
    prompt: "Solve $\\ln(x^3) - \\ln x = 4$.",
    choices: ["$x = e$", "$x = e^2$ only", "$x = \\pm e^2$", "$x = e^4$"],
    answer: 1,
    explain: "$\\ln(x^2) = 4$ → $x^2 = e^4$ → $x = \\pm e^2$. But $\\ln(x^3)$ requires $x > 0$. Reject negative.",
    takeaway: "Always domain-check log equations.",
  },
  {
    id: "cb-mcq-15", source: "CB", number: "MCQ Q15", type: "mcq", unitId: "u3", calc: false,
    prompt: "$1 + 3\\sec x = -5$ on $[0, 2\\pi)$.",
    choices: ["$\\pi/3$ only", "$2\\pi/3, 4\\pi/3$", "$\\pi/3, 2\\pi/3$", "$\\pi$ only"],
    answer: 1,
    explain: "$\\sec x = -2$ → $\\cos x = -1/2$. In $[0, 2\\pi)$: $x = 2\\pi/3, 4\\pi/3$.",
    takeaway: "Reciprocal trig: convert to sin/cos first, then solve.",
  },
  {
    id: "cb-mcq-16", source: "CB", number: "MCQ Q16", type: "mcq", unitId: "u3", calc: false,
    prompt: "Sinusoid with peaks at $x = 3$ and $x = 11$ (both $y = 3$), troughs at $y = -3$. Period and amplitude?",
    choices: ["Period 4, amp 3", "Period 8, amp 3", "Period 8, amp 6", "Period 11, amp 3"],
    answer: 1,
    explain: "Peak-to-peak distance = period = $11 - 3 = 8$. Amp = (max - min)/2 = (3 - (-3))/2 = 3.",
    takeaway: "Period from peak-to-peak. Amplitude from (max - min)/2.",
  },
  {
    id: "cb-mcq-17", source: "CB", number: "MCQ Q17", type: "mcq", unitId: "u3", calc: false,
    prompt: "Polar curve $r = 3\\cos\\theta + 2$. Shape?",
    choices: ["Circle", "Cardioid", "Convex limaçon", "Inner-loop limaçon"],
    answer: 3,
    explain: "$|a/b| = 2/3 < 1$ → inner-loop limaçon.",
    takeaway: "Limaçon classification by $|a/b|$.",
  },
  {
    id: "cb-mcq-18", source: "CB", number: "MCQ Q18", type: "mcq", unitId: "u3", calc: false,
    prompt: "Solve $2\\cos\\theta > -1$ AND $2\\sin\\theta > \\sqrt{3}$ on $[-\\pi, \\pi]$.",
    choices: [
      "$(\\pi/3, 2\\pi/3)$",
      "$(-\\pi/3, \\pi/3)$",
      "$(\\pi/6, \\pi/3)$",
      "$(0, \\pi)$",
    ],
    answer: 0,
    explain: "$\\cos > -1/2$: $(-2\\pi/3, 2\\pi/3)$. $\\sin > \\sqrt{3}/2$: $(\\pi/3, 2\\pi/3)$. Intersect: $(\\pi/3, 2\\pi/3)$.",
    takeaway: "Trig inequalities: solve each, intersect.",
  },
  {
    id: "cb-mcq-19", source: "CB", number: "MCQ Q19", type: "mcq", unitId: "u3", calc: false,
    prompt: "$r = -1 + \\sin\\theta$ on $(0, \\pi/2)$. Where is the actual point?",
    choices: [
      "Above polar axis, getting closer to origin",
      "Above polar axis, getting farther from origin",
      "Below polar axis, getting closer to origin",
      "Below polar axis, getting farther from origin",
    ],
    answer: 2,
    explain: "$r$ goes from $-1$ to $0$, negative throughout, $|r|$ decreases. Negative $r$ in QI ⇒ point in QIII (below). Distance decreasing → getting closer.",
    takeaway: "Negative $r$ flips quadrant; track $|r|$ for distance.",
  },
  {
    id: "cb-mcq-20", source: "CB", number: "MCQ Q20", type: "mcq", unitId: "u1", calc: true,
    prompt: "$T(t) = (75t^3 - 836t^2 + 3100t - 4185)/(14t^2 + 10t - 35)$ on $[2, 9]$. Hours for temperature to rise from 0° to 5°?",
    choices: ["$1.5$", "$2.0$", "$2.280$", "$3.0$"],
    answer: 2,
    explain: "Solve $T(t) = 0$ and $T(t) = 5$ numerically: $\\approx 5.420$ and $\\approx 7.701$. Difference $\\approx 2.280$.",
    takeaway: "Calc-allowed: numerical solving.",
  },
  {
    id: "cb-mcq-21", source: "CB", number: "MCQ Q21", type: "mcq", unitId: "u2", calc: true,
    prompt: "Table $x = -2, -1, 1, 2$, $f = 10, 15, 40, 56$. Exponential regression. Predict $f(1.5)$.",
    choices: ["$32.5$", "$46.767$", "$50.0$", "$55.0$"],
    answer: 1,
    explain: "ExpReg: $a \\approx 24.07$, $b \\approx 1.557$. $f(1.5) \\approx 24.07 \\cdot 1.557^{1.5} \\approx 46.767$.",
    takeaway: "Calculator regression, then evaluate at predicted x.",
  },
  {
    id: "cb-mcq-22", source: "CB", number: "MCQ Q22", type: "mcq", unitId: "u3", calc: true,
    prompt: "$D(t) = 160\\cos(2\\pi(t - 172)/365) + 729$. Behavior on day 150?",
    choices: [
      "Increasing at increasing rate",
      "Increasing at decreasing rate",
      "Decreasing at increasing rate",
      "Decreasing at decreasing rate",
    ],
    answer: 1,
    explain: "Max at $t = 172$. Day 150 is BEFORE max → increasing toward max. Concavity near max is concave down → decreasing rate of increase.",
    takeaway: "Just before a sinusoid peak: increasing at decreasing rate.",
  },
  {
    id: "cb-mcq-23", source: "CB", number: "MCQ Q23", type: "mcq", unitId: "u3", calc: true,
    prompt: "$g(x) = \\sin x - \\cos x = \\sqrt{2}\\sin(x - \\pi/4)$. Restricted-domain interval for invertibility?",
    choices: [
      "$[0, \\pi]$",
      "$[-\\pi/4, 3\\pi/4]$ (length $\\pi$, half period — monotonic increasing)",
      "$[-\\pi/2, \\pi/2]$",
      "$[-\\pi, \\pi]$",
    ],
    answer: 1,
    explain: "Half-period intervals on a sinusoid are monotonic. Period $2\\pi$, half is $\\pi$. $[-\\pi/4, 3\\pi/4]$ has length $\\pi$ and contains all values exactly once.",
    takeaway: "Length-half-period intervals where sinusoid is monotonic.",
  },
  {
    id: "cb-mcq-24", source: "CB", number: "MCQ Q24", type: "mcq", unitId: "u3", calc: true,
    prompt: "Theme park ride: highest 120 ft, lowest 20 ft, returns to highest every 8 sec. At $t = 0$ at highest. Model?",
    choices: [
      "$50\\cos(\\pi t/4) + 70$",
      "$50\\sin(\\pi t/4) + 70$",
      "$70\\cos(\\pi t/4) + 50$",
      "$50\\cos(2\\pi t) + 70$",
    ],
    answer: 0,
    explain: "$A = 50, D = 70, B = 2\\pi/8 = \\pi/4$. Peak at $t = 0$ ⇒ cosine, $C = 0$.",
    takeaway: "Peak at $t = 0$ favors cosine with $C = 0$.",
  },
];

export const PRACTICE: Problem[] = [...MM_S1A, ...MM_S1B, ...MM_S2A, ...MM_S2B, ...CB];

export const PRACTICE_SOURCES: { id: ProblemSource; label: string; section: string; calc: boolean }[] = [
  { id: "MM-S1A", label: "Math Medic — S1A", section: "Section I Part A", calc: false },
  { id: "MM-S1B", label: "Math Medic — S1B", section: "Section I Part B", calc: true },
  { id: "MM-S2A", label: "Math Medic — S2A", section: "Section II Part A", calc: true },
  { id: "MM-S2B", label: "Math Medic — S2B", section: "Section II Part B", calc: false },
  { id: "CB", label: "College Board Preview", section: "Mixed", calc: true },
];
