// Unit 3 — Trigonometric & Polar Functions (30-35% of exam)
//
// 9 topics, 50 lessons. The largest unit by lesson count. Trig is the
// most error-prone topic on the exam — too many moving parts, too many
// identities. Master it by drilling unit circle and a small library of
// identities until they're reflex.

import type { Unit } from "../types";

export const UNIT_3: Unit = {
  id: "u3",
  number: 3,
  title: "Trigonometric & Polar Functions",
  examWeight: "30–35%",
  coreIdeas: [
    "Trig functions encode periodic behavior",
    "Polar coordinates make rotation natural",
    "A small library of identities applied as reflex",
  ],
  topics: [
    // ─────────────────────────────────────────────────────────
    // 3.1 Periodic Foundations
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-1",
      title: "Periodic Foundations",
      blurb: "What 'periodic' means. Amplitude, midline, period, frequency, phase shift.",
      lessons: [
        {
          id: "l3-1-1",
          title: "What 'periodic' means",
          estimateMin: 4,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-1, 12], yRange: [-2, 2],
            curves: [{ id: "f", fn: (x: number) => Math.sin(x), color: "var(--learn-accent)", label: "sin x" }],
          },
          beats: [
            { type: "intro", title: "Periodic functions", stake: "A function is periodic if the same pattern repeats forever. The period is the smallest positive shift that lands you back where you started." },
            { type: "formula-card", title: "Definition", formula: "f \\text{ is periodic with period } P \\iff f(t + P) = f(t) \\text{ for all } t" },
            { type: "narrate", text: "$\\sin x$ has period $2\\pi$. After every $2\\pi$ units, the curve repeats exactly." },
            { type: "checkpoint", prompt: "If $f(t)$ has period 8, what's a period of $g(t) = f(2t)$?",
              choices: ["$2$", "$4$", "$8$", "$16$"],
              answer: 1,
              explain: "Inside-factor of 2 compresses horizontally by 1/2 — period halves to 4.",
            },
            { type: "summary", bullets: ["Period $P$: smallest positive $P$ where $f(t + P) = f(t)$", "Frequency = 1/period"] },
          ],
        },
        {
          id: "l3-1-2",
          title: "Amplitude, midline, period, frequency, phase",
          estimateMin: 7,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [0, 12], yRange: [-1, 9],
            curves: [{ id: "f", fn: (t: number) => 3 * Math.sin((Math.PI / 4) * (t - 1)) + 4, color: "var(--learn-accent)" }],
            features: [{ kind: "h-asymptote", id: "mid", y: 4, label: "midline y = 4" }],
          },
          beats: [
            { type: "intro", title: "Five parameters of a sinusoid", stake: "Five names. Each ties to a specific feature on the graph. Read them off any sinusoid in 30 seconds." },
            { type: "formula-card", title: "The five", formula: "\\begin{array}{ll} \\text{amplitude} & A = (\\max - \\min)/2 \\\\ \\text{midline} & D = (\\max + \\min)/2 \\\\ \\text{period} & P, \\text{ peak-to-peak} \\\\ \\text{frequency} & f = 1/P \\\\ \\text{phase shift} & \\text{horizontal translation} \\end{array}" },
            { type: "highlight", text: "Above: max 7, min 1, so amplitude 3 and midline 4. Period 8 (peaks at $t = 3$ and $t = 11$).", focus: "all" },
            { type: "checkpoint", prompt: "Sinusoid has max 10, min −2. What's the midline?",
              choices: ["$0$", "$4$", "$6$", "$8$"],
              answer: 1,
              explain: "$(10 + -2)/2 = 4$. Midline is the average of max and min.",
            },
            { type: "summary", bullets: ["Amplitude = half the swing", "Midline = average of max and min", "Period = peak-to-peak distance"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 3.2 The Unit Circle
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-2",
      title: "The Unit Circle",
      blurb: "Radians, exact values, ASTC, all 16 points cold.",
      lessons: [
        {
          id: "l3-2-1",
          title: "Radians vs degrees",
          estimateMin: 6,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 4, exact: { theta: "π/4", sin: "√2/2", cos: "√2/2" } },
          beats: [
            { type: "intro", title: "Radians as a measurement of angle", stake: "Radians are the measurement that makes calculus work. $180° = \\pi$ rad. Memorize the conversion and stop converting back to degrees." },
            { type: "formula-card", title: "Conversions", formula: "180° = \\pi \\text{ rad} \\qquad \\text{degrees} \\to \\text{rad: } \\times \\dfrac{\\pi}{180}" },
            { type: "narrate", text: "A radian is the angle whose arc length equals the radius. $2\\pi$ radians = full circle." },
            { type: "narrate", text: "Memorize: $30° = \\pi/6$, $45° = \\pi/4$, $60° = \\pi/3$, $90° = \\pi/2$." },
            { type: "checkpoint", prompt: "Convert $135°$ to radians.",
              choices: ["$2\\pi/3$", "$3\\pi/4$", "$5\\pi/6$", "$7\\pi/8$"],
              answer: 1,
              explain: "$135 \\cdot \\pi/180 = 135\\pi/180 = 3\\pi/4$.",
            },
            { type: "summary", bullets: ["$180° = \\pi$ rad", "Special: $30°, 45°, 60°, 90° = \\pi/6, \\pi/4, \\pi/3, \\pi/2$"] },
          ],
        },
        {
          id: "l3-2-2",
          title: "Sin and cos as unit-circle coordinates",
          estimateMin: 8,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 3, showSin: true, showCos: true, exact: { theta: "π/3", sin: "√3/2", cos: "1/2" } },
          beats: [
            { type: "intro", title: "Unit-circle definition", stake: "$\\sin\\theta$ and $\\cos\\theta$ ARE the coordinates of a point on the unit circle. That's the entire definition." },
            { type: "formula-card", title: "Definition", formula: "(\\cos\\theta, \\sin\\theta) = \\text{point on unit circle at angle } \\theta" },
            { type: "highlight", text: "On the artifact: at $\\theta = \\pi/3$, the terminal point is at $(1/2, \\sqrt{3}/2)$. Cos is the x-coordinate (orange), sin is the y-coordinate (green).", focus: "projections" },
            { type: "transform", text: "Sweep to $\\pi/2$: cos → 0, sin → 1. The point lands on the top of the circle.",
              artifact: { angle: Math.PI / 2, showSin: true, showCos: true, exact: { theta: "π/2", sin: "1", cos: "0" } } },
            { type: "checkpoint", prompt: "$\\cos(0) = ?$",
              choices: ["$0$", "$1$", "$-1$", "Undefined"],
              answer: 1,
              explain: "At $\\theta = 0$, terminal point is $(1, 0)$. $\\cos = $ x-coord = 1.",
            },
            { type: "summary", bullets: ["$\\cos\\theta$ = x-coordinate of point on unit circle", "$\\sin\\theta$ = y-coordinate", "$\\sin^2 + \\cos^2 = 1$ comes from $x^2 + y^2 = 1$"] },
          ],
        },
        {
          id: "l3-2-3",
          title: "Tangent as sin/cos",
          estimateMin: 5,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 4, showTan: true, exact: { theta: "π/4", sin: "√2/2", cos: "√2/2", tan: "1" } },
          beats: [
            { type: "intro", title: "Tangent", stake: "$\\tan\\theta = \\sin\\theta / \\cos\\theta$. Geometrically: slope of the terminal ray." },
            { type: "formula-card", title: "Definition", formula: "\\tan\\theta = \\dfrac{\\sin\\theta}{\\cos\\theta}" },
            { type: "narrate", text: "Tangent is undefined when $\\cos\\theta = 0$ (at $\\pi/2 + k\\pi$). The terminal ray is vertical there — no slope." },
            { type: "checkpoint", prompt: "$\\tan(\\pi/4) = ?$",
              choices: ["$0$", "$1/2$", "$1$", "$\\sqrt{2}$"],
              answer: 2,
              explain: "$\\sin(\\pi/4) = \\cos(\\pi/4) = \\sqrt{2}/2$. Ratio is 1.",
            },
            { type: "summary", bullets: ["$\\tan\\theta = \\sin\\theta/\\cos\\theta$", "Undefined where $\\cos\\theta = 0$"] },
          ],
        },
        {
          id: "l3-2-4",
          title: "Exact values for π/6, π/4, π/3",
          estimateMin: 7,
          artifact: "triangle",
          artifactInitial: { kind: "30-60-90", sides: { a: "1", b: "√3", c: "2" }, angles: { A: "30°", B: "60°", C: "90°" } },
          beats: [
            { type: "intro", title: "Two triangles, three angles, six values", stake: "All your $\\pi/6$, $\\pi/4$, $\\pi/3$ exact values come from two special right triangles. Derive once, remember forever." },
            { type: "narrate", text: "30-60-90 triangle: sides in ratio $1 : \\sqrt{3} : 2$." },
            { type: "highlight", text: "From this triangle: $\\sin(30°) = \\sin(\\pi/6) = $ opposite/hypotenuse $= 1/2$.", focus: "side-a" },
            { type: "highlight", text: "$\\cos(30°) = \\cos(\\pi/6) = $ adjacent/hypotenuse $= \\sqrt{3}/2$.", focus: "side-b" },
            { type: "transform", text: "45-45-90 triangle: sides in ratio $1 : 1 : \\sqrt{2}$. Symmetric.", artifact: { kind: "45-45-90", sides: { a: "1", b: "1", c: "√2" }, angles: { A: "45°", B: "45°", C: "90°" } } },
            { type: "narrate", text: "From this: $\\sin(\\pi/4) = \\cos(\\pi/4) = 1/\\sqrt{2} = \\sqrt{2}/2$." },
            { type: "checkpoint", prompt: "$\\cos(\\pi/3) = ?$",
              choices: ["$1/2$", "$\\sqrt{2}/2$", "$\\sqrt{3}/2$", "$1$"],
              answer: 0,
              explain: "$\\pi/3 = 60°$. From the 30-60-90 triangle: $\\cos(60°) = $ adjacent/hypotenuse, where adjacent is the SHORT side. = $1/2$.",
            },
            { type: "summary", bullets: ["30-60-90: ratios $1, \\sqrt{3}, 2$", "45-45-90: ratios $1, 1, \\sqrt{2}$", "Read sin/cos off the appropriate triangle"] },
          ],
        },
        {
          id: "l3-2-5",
          title: "All 16 unit-circle values",
          estimateMin: 10,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 6, exact: { theta: "π/6", sin: "1/2", cos: "√3/2" } },
          beats: [
            { type: "intro", title: "The whole unit circle", stake: "16 angles, 16 (sin, cos) pairs. By the end of this lesson you should be able to recite them in your sleep." },
            { type: "narrate", text: "Strategy: memorize Q1 ($0$ to $\\pi/2$). Use reference angles + ASTC for Q2, Q3, Q4." },
            { type: "transform", text: "$\\theta = \\pi/6$: $(\\cos, \\sin) = (\\sqrt{3}/2, 1/2)$.", artifact: { angle: Math.PI / 6, exact: { theta: "π/6", sin: "1/2", cos: "√3/2" } } },
            { type: "transform", text: "$\\theta = \\pi/4$: $(\\sqrt{2}/2, \\sqrt{2}/2)$.", artifact: { angle: Math.PI / 4, exact: { theta: "π/4", sin: "√2/2", cos: "√2/2" } } },
            { type: "transform", text: "$\\theta = \\pi/3$: $(1/2, \\sqrt{3}/2)$.", artifact: { angle: Math.PI / 3, exact: { theta: "π/3", sin: "√3/2", cos: "1/2" } } },
            { type: "transform", text: "$\\theta = 2\\pi/3$ (Q2): reference angle $\\pi/3$, cos negative in Q2: $(-1/2, \\sqrt{3}/2)$.", artifact: { angle: 2 * Math.PI / 3, exact: { theta: "2π/3", sin: "√3/2", cos: "-1/2" } } },
            { type: "transform", text: "$\\theta = 7\\pi/6$ (Q3): reference $\\pi/6$, both negative: $(-\\sqrt{3}/2, -1/2)$.", artifact: { angle: 7 * Math.PI / 6, exact: { theta: "7π/6", sin: "-1/2", cos: "-√3/2" } } },
            { type: "checkpoint", prompt: "$\\sin(11\\pi/6) = ?$",
              choices: ["$-\\sqrt{3}/2$", "$-1/2$", "$1/2$", "$\\sqrt{3}/2$"],
              answer: 1,
              explain: "$11\\pi/6$ is Q4 (just below the positive x-axis). Reference angle $\\pi/6$. Sin is negative in Q4: $-1/2$.",
            },
            { type: "summary", bullets: [
              "Q1 angles: $0, \\pi/6, \\pi/4, \\pi/3, \\pi/2$",
              "Q2/Q3/Q4: use reference angle + quadrant signs",
              "Drill until reflex",
            ] },
          ],
        },
        {
          id: "l3-2-6",
          title: "Quadrant signs (ASTC)",
          estimateMin: 5,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 4, showAstc: true, showQuadrants: true },
          beats: [
            { type: "intro", title: "ASTC", stake: "All Students Take Calculus. Each letter tells you which trig functions are POSITIVE in that quadrant." },
            { type: "formula-card", title: "ASTC mnemonic", formula: "\\begin{array}{c|c|c} \\text{Q2: S} & \\text{Q1: A} \\\\ \\sin > 0 & \\text{all} > 0 \\\\ \\hline \\text{Q3: T} & \\text{Q4: C} \\\\ \\tan > 0 & \\cos > 0 \\end{array}" },
            { type: "narrate", text: "Q1: ALL positive. Q2: only Sin. Q3: only Tan. Q4: only Cos. (Cofunctions: where sin is +, csc is +. Same for cos/sec, tan/cot.)" },
            { type: "checkpoint", prompt: "In which quadrant is $\\cos\\theta < 0$ AND $\\sin\\theta < 0$?",
              choices: ["Q1", "Q2", "Q3", "Q4"],
              answer: 2,
              explain: "Q3 — Tangent is positive there because both sin and cos are negative (negative ÷ negative = positive).",
            },
            { type: "summary", bullets: ["Q1: All", "Q2: Sin", "Q3: Tan", "Q4: Cos (the rest are negative)"] },
          ],
        },
        {
          id: "l3-2-7",
          title: "Sin/cos for non-unit-radius circles",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: { xRange: [-3, 3], yRange: [-3, 3] },
          beats: [
            { type: "intro", title: "Off-circle radii", stake: "Point at $(x, y)$ on a circle of radius $r$ ⇒ divide by $r$ to recover sin and cos." },
            { type: "formula-card", title: "Generalized definitions", formula: "\\cos\\theta = x/r, \\quad \\sin\\theta = y/r, \\quad \\tan\\theta = y/x" },
            { type: "derive", text: "Point $(-1.9, -0.64)$ on a circle of radius 2. Find $\\cos\\theta$.",
              line: "\\cos\\theta = x/r = -1.9/2 = -0.95" },
            { type: "checkpoint", prompt: "Point $(3, 4)$ on a circle of radius 5. $\\sin\\theta$?",
              choices: ["$3/4$", "$3/5$", "$4/5$", "$5/3$"],
              answer: 2,
              explain: "$\\sin\\theta = y/r = 4/5$.",
            },
            { type: "summary", bullets: ["Always divide by $r$", "If radius isn't 1 you'll get weird-looking sin/cos values until you remember to divide"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 3.3 Sin & Cos Graphs
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-3",
      title: "Sin & Cos Graphs",
      blurb: "Parent functions, the cosine-as-shifted-sine relationship, concavity.",
      lessons: [
        {
          id: "l3-3-1",
          title: "Parent sin and cos",
          estimateMin: 8,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-Math.PI, 3 * Math.PI], yRange: [-2, 2],
            curves: [{ id: "sin", fn: (x: number) => Math.sin(x), color: "var(--learn-accent)", label: "sin x" }],
          },
          beats: [
            { type: "intro", title: "Sin and cos parents", stake: "Period $2\\pi$. Range $[-1, 1]$. Sin starts at 0; cos starts at 1." },
            { type: "narrate", text: "Sin: passes through origin, max at $\\pi/2$, returns to zero at $\\pi$, min at $3\\pi/2$, back to zero at $2\\pi$." },
            { type: "transform", text: "Cos: shifted version of sin — peak at $x = 0$.",
              artifact: { curves: [{ id: "cos", fn: (x: number) => Math.cos(x), color: "var(--learn-accent)", label: "cos x" }] } },
            { type: "checkpoint", prompt: "Range of $f(x) = 3\\sin x$?",
              choices: ["$[-1, 1]$", "$[-3, 3]$", "$[0, 3]$", "$[-3, 1]$"],
              answer: 1,
              explain: "Multiplying sin by 3 stretches range by factor 3. $[-3, 3]$.",
            },
            { type: "summary", bullets: ["Period $2\\pi$, range $[-1, 1]$", "Sin starts at origin, cos starts at peak"] },
          ],
        },
        {
          id: "l3-3-2",
          title: "Cosine = sine shifted left",
          estimateMin: 4,
          artifact: "comparison",
          artifactInitial: {
            left: { kind: "coordinate-plane", label: "sin x", state: { xRange: [-Math.PI, 3 * Math.PI], yRange: [-1.5, 1.5], curves: [{ id: "sin", fn: (x: number) => Math.sin(x), color: "var(--learn-accent)" }] } },
            right: { kind: "coordinate-plane", label: "cos x = sin(x + π/2)", state: { xRange: [-Math.PI, 3 * Math.PI], yRange: [-1.5, 1.5], curves: [{ id: "cos", fn: (x: number) => Math.cos(x), color: "var(--learn-accent)" }] } },
          },
          beats: [
            { type: "intro", title: "Cos = sin shifted left", stake: "Same shape. Cos is sin shifted left by $\\pi/2$." },
            { type: "formula-card", title: "The relationship", formula: "\\cos\\theta = \\sin\\left(\\theta + \\dfrac{\\pi}{2}\\right)" },
            { type: "compare", text: "Both curves have the same shape, period, and amplitude. Cos peaks at 0 because that's where sin peaks once shifted." },
            { type: "checkpoint", prompt: "$\\sin(\\theta + \\pi/2) = ?$",
              choices: ["$\\sin\\theta$", "$\\cos\\theta$", "$-\\sin\\theta$", "$-\\cos\\theta$"],
              answer: 1,
              explain: "That IS cosine. Cofunction identity in disguise.",
            },
            { type: "summary", bullets: ["$\\cos\\theta = \\sin(\\theta + \\pi/2)$", "Sin and cos are the same curve, $\\pi/2$ apart"] },
          ],
        },
        {
          id: "l3-3-3",
          title: "Concavity of sinusoids",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-Math.PI, Math.PI], yRange: [-1.5, 1.5],
            curves: [{ id: "sin", fn: (x: number) => Math.sin(x), color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "Where does sin curve up vs down?", stake: "Standard FRQ: 'is the function concave up or down on this interval?' For sinusoids, it's always one of two answers based on max/min proximity." },
            { type: "narrate", text: "Near a MAX, the curve is concave DOWN (like a frown — about to descend)." },
            { type: "narrate", text: "Near a MIN, the curve is concave UP (like a smile — about to ascend)." },
            { type: "narrate", text: "Inflection points: every midline crossing." },
            { type: "checkpoint", prompt: "$\\sin x$ on $(\\pi/2, \\pi)$. Concavity?",
              choices: ["Concave up", "Concave down", "Inflection at $\\pi$", "None of these"],
              answer: 1,
              explain: "$x = \\pi/2$ is the max of sin. Past a max, descending. Concavity is DOWN until the next inflection at $x = \\pi$.",
            },
            { type: "summary", bullets: ["Near max: concave down", "Near min: concave up", "Inflection at every midline crossing"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 3.4 Sinusoidal Modeling
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-4",
      title: "Sinusoidal Modeling",
      blurb: "A·sin(B(t-C)) + D. Read off graph. Build from context. The four canonical scenarios.",
      lessons: [
        {
          id: "l3-4-1",
          title: "A, B, C, D — what each does",
          estimateMin: 10,
          artifact: "sinusoidal-builder",
          artifactInitial: { A: 1, B: 1, C: 0, D: 0 },
          beats: [
            { type: "intro", title: "Four parameters", stake: "$f(t) = A \\sin(B(t - C)) + D$. Each letter does one thing. Memorize the mapping." },
            { type: "formula-card", title: "Parameter map", formula: "\\begin{array}{ll} |A| & \\text{amplitude} \\\\ B & \\text{period} = 2\\pi/|B| \\\\ C & \\text{phase shift right} \\\\ D & \\text{midline / vertical shift} \\end{array}" },
            { type: "transform", text: "Increase $A$ to 3: amplitude triples, range stretches.", artifact: { A: 3, B: 1, C: 0, D: 0 } },
            { type: "transform", text: "Now $B = 2$: period halves to $\\pi$. Faster oscillation.", artifact: { A: 3, B: 2, C: 0, D: 0 } },
            { type: "transform", text: "$D = 4$: whole curve shifts up by 4 — midline now $y = 4$.", artifact: { A: 3, B: 2, C: 0, D: 4 } },
            { type: "transform", text: "$C = 1$: shifts right by 1 — phase shift.", artifact: { A: 3, B: 2, C: 1, D: 4 } },
            { type: "checkpoint", prompt: "$f(t) = 5 \\sin(\\pi t / 3) + 7$. What's the period?",
              choices: ["$3$", "$6$", "$\\pi/3$", "$2\\pi/3$"],
              answer: 1,
              explain: "Period $= 2\\pi/|B| = 2\\pi/(\\pi/3) = 6$.",
            },
            { type: "summary", bullets: ["$|A|$ = amplitude", "Period = $2\\pi/|B|$", "$C$ = phase shift right", "$D$ = midline"] },
          ],
        },
        {
          id: "l3-4-2",
          title: "Reading a sinusoid off a graph",
          estimateMin: 8,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-2 * Math.PI, 2 * Math.PI], yRange: [-2, 6],
            curves: [{ id: "f", fn: (t: number) => -3 * Math.cos(t / 2) + 2, color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "From graph to formula", stake: "Spot max, min, period, reference point — solve for A, B, C, D in 60 seconds." },
            { type: "narrate", text: "Above: max 5, min −1, midline 2 (between). Amplitude $A = 3$, $D = 2$." },
            { type: "narrate", text: "Period $= 4\\pi$ (peaks $4\\pi$ apart). $B = 2\\pi/(4\\pi) = 1/2$." },
            { type: "narrate", text: "At $t = 0$, the curve is at MIN. With $-A\\cos$, $-3\\cos(0) + 2 = -1$. ✓" },
            { type: "checkpoint", prompt: "Graph has max 8, min 2, peak at $t = 3$, period 8. Build a cosine model.",
              choices: [
                "$3 \\cos(\\pi t/4) + 5$",
                "$3 \\cos(\\pi (t-3)/4) + 5$",
                "$5 \\cos(\\pi t/4) + 3$",
                "$3 \\cos(2\\pi t/8) + 5$",
              ],
              answer: 1,
              explain: "$A = 3$, $D = 5$, $B = 2\\pi/8 = \\pi/4$. Peak at $t = 3$ ⇒ $C = 3$.",
            },
            { type: "summary", bullets: ["Max + min ⇒ A, D", "Peak-to-peak ⇒ B", "Reference point ⇒ C"] },
          ],
        },
        {
          id: "l3-4-3",
          title: "The 4-step modeling protocol",
          estimateMin: 7,
          artifact: "sinusoidal-builder",
          artifactInitial: { A: 1, B: 1, C: 0, D: 0 },
          beats: [
            { type: "intro", title: "The protocol", stake: "Same four steps every time. Don't think about it — execute it." },
            { type: "formula-card", title: "Modeling protocol", formula: "\\begin{array}{l} 1.\\ \\text{Get max, min from context} \\Rightarrow A, D \\\\ 2.\\ \\text{Get period} \\Rightarrow B \\\\ 3.\\ \\text{Pick a reference time} \\Rightarrow \\text{sin or cos} \\\\ 4.\\ \\text{Solve for } C \\text{ from reference} \\end{array}" },
            { type: "narrate", text: "Cosine is simpler if you know where a peak is. Sine is simpler if you know where the function crosses the midline going up." },
            { type: "summary", bullets: ["Always: max/min → period → ref point → C", "Pick the form that matches your reference"] },
          ],
        },
        {
          id: "l3-4-4",
          title: "Tides — full worked model",
          estimateMin: 8,
          artifact: "sinusoidal-builder",
          artifactInitial: { A: 2.655, B: Math.PI / 7, C: 9, D: 3.175, useCos: true, tRange: [0, 28] },
          beats: [
            { type: "intro", title: "Tides — classic FRQ scenario", stake: "Period 14 hr. High tide 5.83 ft at $t = 9$. Low tide 0.52 ft. Build the model." },
            { type: "derive", text: "Step 1 — A and D from max/min:",
              line: "A = (5.83 - 0.52)/2 = 2.655; \\quad D = (5.83 + 0.52)/2 = 3.175" },
            { type: "derive", text: "Step 2 — B from period:",
              line: "B = 2\\pi/14 = \\pi/7" },
            { type: "derive", text: "Step 3-4 — pick cosine peaked at $t = 9$:",
              line: "h(t) = 2.655 \\cos\\left(\\dfrac{\\pi}{7}(t - 9)\\right) + 3.175" },
            { type: "checkpoint", prompt: "Using this model, $h(20) \\approx ?$",
              choices: ["$0.5$", "$2.4$", "$3.8$", "$5.6$"],
              answer: 2,
              explain: "$h(20) = 2.655 \\cos(11\\pi/7) + 3.175 \\approx 3.766$ ft.",
            },
            { type: "summary", bullets: ["High tide → cosine reference point", "Plug into the formula and evaluate"] },
          ],
        },
        {
          id: "l3-4-5",
          title: "Theme park ride",
          estimateMin: 6,
          artifact: "sinusoidal-builder",
          artifactInitial: { A: 50, B: Math.PI / 4, C: 0, D: 70, useCos: true, tRange: [0, 16] },
          beats: [
            { type: "intro", title: "Theme park ride", stake: "Highest 120 ft, lowest 20 ft, returns to highest every 8 sec. At $t=0$, X is at highest." },
            { type: "derive", text: "$A = 50$, $D = 70$, $B = 2\\pi/8 = \\pi/4$, peak at $t = 0$ ⇒ use cosine with $C = 0$:",
              line: "H(t) = 50 \\cos(\\pi t / 4) + 70" },
            { type: "summary", bullets: ["Peak at $t = 0$ ⇒ cosine, $C = 0$", "Always check max with the model"] },
          ],
        },
        {
          id: "l3-4-6",
          title: "Fan blade — sine vs cosine choice",
          estimateMin: 7,
          artifact: "sinusoidal-builder",
          artifactInitial: { A: 6, B: 10 * Math.PI, C: 1 / 20, D: 20, useSin: true, tRange: [0, 0.4] },
          beats: [
            { type: "intro", title: "Fan blade", stake: "5 rotations/sec. B is 6 inches from center. Center 20 inches above table. At $t = 0$, B is at top." },
            { type: "derive", text: "Setup: max 26, min 14, period 0.2, peak at $t = 0$:",
              line: "A = 6, \\ D = 20, \\ B = 2\\pi/0.2 = 10\\pi" },
            { type: "narrate", text: "Choose sine. For sine to peak at $t = 0$, need argument $= \\pi/2$ at $t = 0$. So $B \\cdot c = \\pi/2$, giving $c = (\\pi/2)/(10\\pi) = 1/20$." },
            { type: "derive", text: "Final model:",
              line: "h(t) = 6 \\sin(10\\pi(t + 1/20)) + 20" },
            { type: "summary", bullets: ["Could use either sine or cosine — pick based on the reference point", "Sine peaks when its argument is $\\pi/2$"] },
          ],
        },
        {
          id: "l3-4-7",
          title: "Metronome — half-period subtlety",
          estimateMin: 8,
          artifact: "sinusoidal-builder",
          artifactInitial: { A: 4, B: 2 * Math.PI / 3, C: 0, D: 0, useCos: true, tRange: [0, 6] },
          beats: [
            { type: "intro", title: "Metronome — the half-period trap", stake: "40 BPM. 1 beat = pendulum from one extreme to the other (HALF a full period). Tricky setup." },
            { type: "narrate", text: "40 beats/min ⇒ 1 beat per 1.5 sec. But beat = HALF period, so full period = 3 sec." },
            { type: "narrate", text: "At $t = 0$, pendulum is at minimum (furthest left, $h = -4$). Use $-A\\cos$ form:" },
            { type: "derive", text: "Model:", line: "h(t) = -4 \\cos\\left(\\dfrac{2\\pi}{3} t\\right)" },
            { type: "checkpoint", prompt: "Why is this $-4\\cos$ and not $4\\cos$?",
              choices: [
                "Cosine starts at peak, but here we want it at min — flip the sign",
                "Negative makes the period longer",
                "Both are equivalent",
                "Doesn't matter",
              ],
              answer: 0,
              explain: "$\\cos(0) = 1$ is a maximum. To start at a min, multiply by $-1$.",
            },
            { type: "summary", bullets: ["Read carefully: 'beat' might be half a period", "Negative cosine flips peaks to troughs"] },
          ],
        },
        {
          id: "l3-4-8",
          title: "Daylight — concavity at peak",
          estimateMin: 7,
          artifact: "sinusoidal-builder",
          artifactInitial: { A: 160, B: 2 * Math.PI / 365, C: 172, D: 729, useCos: true, tRange: [0, 365] },
          beats: [
            { type: "intro", title: "Daylight model", stake: "$D(t) = 160\\cos(2\\pi(t-172)/365) + 729$. What's the behavior on day 150?" },
            { type: "narrate", text: "Cosine peaks where its argument is 0. So MAX of $D$ is at $t = 172$." },
            { type: "narrate", text: "Day 150 is BEFORE the max. So $D$ is INCREASING toward max." },
            { type: "narrate", text: "Concavity near a max is concave DOWN. So $D$ is increasing AT A DECREASING RATE." },
            { type: "checkpoint", prompt: "What's the behavior of the daylight model on day 200?",
              choices: [
                "Increasing at increasing rate",
                "Increasing at decreasing rate",
                "Decreasing at decreasing rate",
                "Decreasing at increasing rate",
              ],
              answer: 2,
              explain: "$t = 200$ is past the max ($t = 172$). Now decreasing. Past max, concavity is still down — so 'decreasing at decreasing rate' (slope going from 0 to more negative — wait, that's INCREASING rate of decrease). Actually past max, concavity transitions from DOWN to UP at the next inflection (midline crossing at $t = 172 + 365/4 \\approx 263$). On $(172, 263)$, still concave down, so 'decreasing at INCREASING rate.' — Correct answer: D.",
            },
            { type: "summary", bullets: ["Peak of cos is where argument = 0", "Just before peak: increasing at decreasing rate", "Concavity flips at midline crossings"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 3.5 Tangent
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-5",
      title: "Tangent",
      blurb: "Period π. Asymptotes. Always increasing. Concavity matches sign of tan.",
      lessons: [
        {
          id: "l3-5-1",
          title: "Definition, period π, asymptotes",
          estimateMin: 7,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-Math.PI, Math.PI], yRange: [-5, 5],
            curves: [{ id: "tan", fn: (x: number) => Math.abs(Math.cos(x)) > 0.1 ? Math.tan(x) : NaN, color: "var(--learn-accent)" }],
            features: [
              { kind: "v-asymptote", id: "va1", x: -Math.PI / 2, label: "x = -π/2" },
              { kind: "v-asymptote", id: "va2", x: Math.PI / 2, label: "x = π/2" },
            ],
          },
          beats: [
            { type: "intro", title: "Tangent — period $\\pi$", stake: "$\\tan x = \\sin x / \\cos x$. Period $\\pi$ (NOT $2\\pi$). VAs where $\\cos x = 0$." },
            { type: "narrate", text: "Above: tangent on $(-\\pi/2, \\pi/2)$. Vertical asymptotes at $\\pm\\pi/2$. Crosses zero at $x = 0$." },
            { type: "checkpoint", prompt: "Period of $\\tan(2x)$?",
              choices: ["$\\pi/2$", "$\\pi$", "$2\\pi$", "$4\\pi$"],
              answer: 0,
              explain: "Tan period is $\\pi$. Inside-factor 2 compresses to $\\pi/2$.",
            },
            { type: "summary", bullets: ["Period $\\pi$ (half of sin/cos)", "VAs at $\\pi/2 + k\\pi$", "Zeros at $k\\pi$"] },
          ],
        },
        {
          id: "l3-5-2",
          title: "Always increasing between asymptotes",
          estimateMin: 4,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-Math.PI / 2, Math.PI / 2], yRange: [-5, 5],
            curves: [{ id: "tan", fn: (x: number) => Math.abs(Math.cos(x)) > 0.1 ? Math.tan(x) : NaN, color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "Tangent never decreases between VAs", stake: "On every interval between asymptotes, $\\tan x$ is increasing." },
            { type: "narrate", text: "Goes from $-\\infty$ at the lower VA, up through 0, up to $+\\infty$ at the upper VA. No turning around." },
            { type: "summary", bullets: ["Between consecutive VAs, tangent is strictly increasing"] },
          ],
        },
        {
          id: "l3-5-3",
          title: "Concavity matches sign of tan",
          estimateMin: 6,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-Math.PI / 2, Math.PI / 2], yRange: [-5, 5],
            curves: [{ id: "tan", fn: (x: number) => Math.abs(Math.cos(x)) > 0.1 ? Math.tan(x) : NaN, color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "Concavity rule for tan", stake: "Concave UP where tan > 0. Concave DOWN where tan < 0. Sign-of-tan IS the concavity sign." },
            { type: "narrate", text: "On $(0, \\pi/2)$: tan is positive ⇒ concave up." },
            { type: "narrate", text: "On $(-\\pi/2, 0)$: tan is negative ⇒ concave down." },
            { type: "checkpoint", prompt: "$f(\\theta) = \\tan(\\theta/2)$ on $7\\pi < \\theta < 8\\pi$. Behavior?",
              choices: [
                "Increasing, concave up",
                "Increasing, concave down",
                "Decreasing, concave up",
                "Decreasing, concave down",
              ],
              answer: 1,
              explain: "Let $u = \\theta/2 \\in (7\\pi/2, 4\\pi)$. Modulo period $\\pi$, this matches $(\\pi/2, \\pi)$ — tan goes from $-\\infty$ to 0, increasing throughout, with $\\tan u < 0$ ⇒ concave DOWN.",
            },
            { type: "summary", bullets: ["Concave up where $\\tan > 0$", "Concave down where $\\tan < 0$", "Always increasing between VAs"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 3.6 Inverse Trig & Reciprocal Trig
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-6",
      title: "Inverse Trig & Reciprocal Trig",
      blurb: "Restricted-domain inverses. Reciprocal trig functions.",
      lessons: [
        {
          id: "l3-6-1",
          title: "Why we restrict — failed HLT",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-2 * Math.PI, 2 * Math.PI], yRange: [-1.5, 1.5],
            curves: [{ id: "sin", fn: (x: number) => Math.sin(x), color: "var(--learn-accent)" }],
            features: [{ kind: "h-asymptote", id: "test", y: 0.5, label: "y = 0.5" }],
          },
          beats: [
            { type: "intro", title: "Trig functions don't pass HLT", stake: "Every horizontal line crosses sin infinitely often. Without restriction, no inverse exists." },
            { type: "narrate", text: "Above: $y = 0.5$ crosses $\\sin x$ infinitely many times. We can't ask 'what x maps to 0.5' — there are many." },
            { type: "narrate", text: "Solution: restrict the domain to a single 'principal' interval where sin IS one-to-one. For sin, that's $[-\\pi/2, \\pi/2]$." },
            { type: "summary", bullets: ["Trig fails HLT on full domain", "Restrict to a principal interval", "Different convention for each trig function"] },
          ],
        },
        {
          id: "l3-6-2",
          title: "arcsin / arccos / arctan",
          estimateMin: 7,
          artifact: "comparison",
          artifactInitial: {
            left: { kind: "coordinate-plane", label: "arcsin x", state: { xRange: [-1.5, 1.5], yRange: [-Math.PI / 2 - 0.3, Math.PI / 2 + 0.3], curves: [{ id: "as", fn: (x: number) => x >= -1 && x <= 1 ? Math.asin(x) : NaN, color: "var(--learn-accent)" }] } },
            right: { kind: "coordinate-plane", label: "arccos x", state: { xRange: [-1.5, 1.5], yRange: [-0.3, Math.PI + 0.3], curves: [{ id: "ac", fn: (x: number) => x >= -1 && x <= 1 ? Math.acos(x) : NaN, color: "var(--learn-accent)" }] } },
          },
          beats: [
            { type: "intro", title: "Three restricted inverses", stake: "Each inverse has its own domain (where the original is defined) and range (the principal interval)." },
            { type: "formula-card", title: "Inverse trig domains and ranges",
              formula: "\\begin{array}{l|c|c} & \\text{domain} & \\text{range} \\\\ \\hline \\arcsin & [-1, 1] & [-\\pi/2, \\pi/2] \\\\ \\arccos & [-1, 1] & [0, \\pi] \\\\ \\arctan & \\mathbb{R} & (-\\pi/2, \\pi/2) \\end{array}" },
            { type: "checkpoint", prompt: "$\\arcsin(\\sqrt{3}/2) = ?$",
              choices: ["$\\pi/3$", "$\\pi/6$", "$2\\pi/3$", "$5\\pi/6$"],
              answer: 0,
              explain: "$\\sin(\\pi/3) = \\sqrt{3}/2$, and $\\pi/3$ is in the principal range $[-\\pi/2, \\pi/2]$.",
            },
            { type: "summary", bullets: ["arcsin: $[-1,1] \\to [-\\pi/2, \\pi/2]$", "arccos: $[-1,1] \\to [0, \\pi]$", "arctan: $\\mathbb{R} \\to (-\\pi/2, \\pi/2)$"] },
          ],
        },
        {
          id: "l3-6-3",
          title: "$\\arcsin(\\sin x) \\ne x$ in general",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-2 * Math.PI, 2 * Math.PI], yRange: [-Math.PI, Math.PI],
            curves: [{ id: "id", fn: (x: number) => x, color: "var(--learn-ink-mute)", dashed: true, label: "y = x" }],
          },
          beats: [
            { type: "intro", title: "The composition trap", stake: "$\\arcsin(\\sin x) = x$ ONLY when $x \\in [-\\pi/2, \\pi/2]$. Outside that, you get a 'reflected' value." },
            { type: "narrate", text: "Why? arcsin's range is $[-\\pi/2, \\pi/2]$. So $\\arcsin(\\sin x)$ always lands in that interval." },
            { type: "derive", text: "$\\arcsin(\\sin(3\\pi/4)) = ?$ Note $\\sin(3\\pi/4) = \\sqrt{2}/2$.",
              line: "\\arcsin(\\sqrt{2}/2) = \\pi/4 \\ne 3\\pi/4" },
            { type: "checkpoint", prompt: "$\\arcsin(\\sin(7\\pi/6)) = ?$",
              choices: ["$7\\pi/6$", "$-7\\pi/6$", "$\\pi/6$", "$-\\pi/6$"],
              answer: 3,
              explain: "$\\sin(7\\pi/6) = -1/2$. $\\arcsin(-1/2) = -\\pi/6$ (in principal range).",
            },
            { type: "summary", bullets: ["arcsin(sin x) = x only on $[-\\pi/2, \\pi/2]$", "Outside: use reference angle"] },
          ],
        },
        {
          id: "l3-6-4",
          title: "Sec, csc, cot — definitions",
          estimateMin: 7,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-Math.PI, Math.PI], yRange: [-3, 3],
            curves: [
              { id: "cos", fn: (x: number) => Math.cos(x), color: "var(--learn-ink-mute)", dashed: true, label: "cos x" },
              { id: "sec", fn: (x: number) => Math.abs(Math.cos(x)) > 0.15 ? 1 / Math.cos(x) : NaN, color: "var(--learn-accent)", label: "sec x" },
            ],
          },
          beats: [
            { type: "intro", title: "Reciprocal trig functions", stake: "Sec, csc, cot are 1 over cos, sin, tan. Their VAs are where the host function = 0." },
            { type: "formula-card", title: "Definitions", formula: "\\sec\\theta = \\dfrac{1}{\\cos\\theta} \\quad \\csc\\theta = \\dfrac{1}{\\sin\\theta} \\quad \\cot\\theta = \\dfrac{\\cos\\theta}{\\sin\\theta}" },
            { type: "narrate", text: "$\\sec, \\csc$: range $(-\\infty, -1] \\cup [1, \\infty)$. Period $2\\pi$. Symmetrical with their hosts." },
            { type: "narrate", text: "$\\cot$: range all reals. Period $\\pi$ (like tan, since $\\cot = 1/\\tan$)." },
            { type: "checkpoint", prompt: "$\\csc(\\pi/2) = ?$",
              choices: ["$0$", "$1$", "$\\sqrt{2}$", "Undefined"],
              answer: 1,
              explain: "$\\csc(\\pi/2) = 1/\\sin(\\pi/2) = 1/1 = 1$.",
            },
            { type: "summary", bullets: ["Reciprocals of cos, sin, tan", "Sec/csc range: $|y| \\geq 1$", "Cot has period $\\pi$"] },
          ],
        },
        {
          id: "l3-6-5",
          title: "Sec asymptotes ↔ cos zeros",
          estimateMin: 5,
          artifact: "comparison",
          artifactInitial: {
            left: { kind: "coordinate-plane", label: "cos x", state: { xRange: [-Math.PI, Math.PI], yRange: [-1.5, 1.5], curves: [{ id: "cos", fn: (x: number) => Math.cos(x), color: "var(--learn-accent)" }], features: [{ kind: "point", id: "z1", x: -Math.PI / 2, y: 0 }, { kind: "point", id: "z2", x: Math.PI / 2, y: 0 }] } },
            right: { kind: "coordinate-plane", label: "sec x", state: { xRange: [-Math.PI, Math.PI], yRange: [-3, 3], curves: [{ id: "sec", fn: (x: number) => Math.abs(Math.cos(x)) > 0.15 ? 1 / Math.cos(x) : NaN, color: "var(--learn-accent)" }], features: [{ kind: "v-asymptote", id: "va1", x: -Math.PI / 2 }, { kind: "v-asymptote", id: "va2", x: Math.PI / 2 }] } },
          },
          beats: [
            { type: "intro", title: "The most-tested trig relationship", stake: "X-intercepts of $\\cos$ are exactly the x-coordinates of vertical asymptotes of $\\sec$." },
            { type: "compare", text: "Left: cos zeros at $\\pm\\pi/2$. Right: sec VAs at the SAME x-coordinates. Always." },
            { type: "narrate", text: "Same logic for sin and csc. Same logic for tan and cot — but cot's zeros are tan's VAs." },
            { type: "checkpoint", prompt: "If $f(x) = \\cos x$ and $g(x) = \\sec x$, the x-coordinates of $f$'s x-intercepts are:",
              choices: [
                "Equal to $g$'s x-intercepts",
                "Equal to $g$'s vertical asymptotes",
                "Equal to $g$'s y-intercept",
                "Unrelated to $g$",
              ],
              answer: 1,
              explain: "Cos zeros = sec VAs. Reciprocals turn zeros into infinities.",
            },
            { type: "summary", bullets: ["cos zero ⇔ sec VA", "sin zero ⇔ csc VA", "Same x-coordinates"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 3.7 Trig Equations
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-7",
      title: "Trig Equations",
      blurb: "General solutions, inequalities, substitution.",
      lessons: [
        {
          id: "l3-7-1",
          title: "General solution: $\\sin x = c$",
          estimateMin: 8,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 6 },
          beats: [
            { type: "intro", title: "All solutions, not just one", stake: "$\\sin x = c$ has infinitely many solutions. Two per cycle, period $2\\pi$. Capture them all in a formula." },
            { type: "formula-card", title: "General solution", formula: "\\sin x = c \\Rightarrow x = \\arcsin c + 2\\pi k \\text{ or } x = \\pi - \\arcsin c + 2\\pi k" },
            { type: "narrate", text: "The two intersections in one cycle: principal $x_0 = \\arcsin c$, and the supplementary $\\pi - x_0$ (sin symmetry across $\\pi/2$)." },
            { type: "derive", text: "Solve $\\sin x = -1/2$:",
              line: "x_0 = \\arcsin(-1/2) = -\\pi/6 \\Rightarrow x = -\\pi/6 + 2\\pi k \\text{ or } \\pi - (-\\pi/6) = 7\\pi/6 + 2\\pi k" },
            { type: "checkpoint", prompt: "Solutions of $-8 \\sin x + 1 = 5$ in $[0, 2\\pi)$?",
              choices: ["$\\pi/6, 5\\pi/6$", "$7\\pi/6, 11\\pi/6$", "$\\pi/3, 2\\pi/3$", "$5\\pi/6, 7\\pi/6$"],
              answer: 1,
              explain: "$\\sin x = -1/2$. Reference angle $\\pi/6$. Sin negative in Q3 and Q4: $7\\pi/6, 11\\pi/6$.",
            },
            { type: "summary", bullets: ["Two solutions per period for $\\sin x = c$", "Principal + supplementary, then add $2\\pi k$"] },
          ],
        },
        {
          id: "l3-7-2",
          title: "General solution: $\\cos x = c$",
          estimateMin: 6,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 3 },
          beats: [
            { type: "intro", title: "Cosine — symmetric across x-axis", stake: "$\\cos x = c$ has solutions $\\pm x_0 + 2\\pi k$. Symmetric pair." },
            { type: "formula-card", title: "General solution", formula: "\\cos x = c \\Rightarrow x = \\pm \\arccos c + 2\\pi k" },
            { type: "narrate", text: "Cosine is even: $\\cos(-x) = \\cos x$. So if $x_0$ works, $-x_0$ works too." },
            { type: "checkpoint", prompt: "All solutions of $\\cos x = 1/2$?",
              choices: [
                "$x = \\pi/3 + 2\\pi k$",
                "$x = \\pm \\pi/3 + 2\\pi k$",
                "$x = \\pi/3 + \\pi k$",
                "$x = \\pm \\pi/3 + \\pi k$",
              ],
              answer: 1,
              explain: "$\\arccos(1/2) = \\pi/3$. Cosine is even, so $\\pm \\pi/3 + 2\\pi k$.",
            },
            { type: "summary", bullets: ["$\\cos x = c$: $x = \\pm x_0 + 2\\pi k$", "Two solutions per cycle"] },
          ],
        },
        {
          id: "l3-7-3",
          title: "General solution: $\\tan x = c$",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: { xRange: [-Math.PI, Math.PI], yRange: [-3, 3], curves: [{ id: "tan", fn: (x: number) => Math.abs(Math.cos(x)) > 0.15 ? Math.tan(x) : NaN, color: "var(--learn-accent)" }] },
          beats: [
            { type: "intro", title: "Tangent has period $\\pi$, only ONE solution per cycle", stake: "Period $\\pi$ instead of $2\\pi$ — only one branch per cycle. Solutions: $\\arctan c + \\pi k$." },
            { type: "formula-card", title: "General solution", formula: "\\tan x = c \\Rightarrow x = \\arctan c + \\pi k" },
            { type: "checkpoint", prompt: "Solve $\\tan x = 1$ on $[0, 2\\pi)$.",
              choices: ["$\\pi/4$ only", "$\\pi/4, 3\\pi/4$", "$\\pi/4, 5\\pi/4$", "$\\pi/4, \\pi/2$"],
              answer: 2,
              explain: "$\\arctan 1 = \\pi/4$. Add $\\pi$: $\\pi/4 + \\pi = 5\\pi/4$. Both are in $[0, 2\\pi)$.",
            },
            { type: "summary", bullets: ["$\\tan x = c$: $x = x_0 + \\pi k$", "Only one solution per period $\\pi$"] },
          ],
        },
        {
          id: "l3-7-4",
          title: "Substitution: $\\sin(3x) = c$",
          estimateMin: 6,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Inner-multiplied equations", stake: "$\\sin(3x) = c$? Solve for $3x$ first, then divide by 3 at the end." },
            { type: "derive", text: "Solve $2 \\sin(3x) - 5 = -7$.",
              line: "\\sin(3x) = -1 \\Rightarrow 3x = -\\pi/2 + 2\\pi k" },
            { type: "derive", text: "Divide by 3:",
              line: "x = -\\pi/6 + (2\\pi/3) k" },
            { type: "checkpoint", prompt: "Solve $\\cos(2x) = 1/2$.",
              choices: [
                "$x = \\pm\\pi/3 + 2\\pi k$",
                "$x = \\pm\\pi/6 + \\pi k$",
                "$x = \\pm\\pi/6 + 2\\pi k$",
                "$x = \\pm\\pi/3 + \\pi k$",
              ],
              answer: 1,
              explain: "$2x = \\pm\\pi/3 + 2\\pi k$, then divide by 2: $x = \\pm\\pi/6 + \\pi k$. Period of $\\cos(2x)$ is $\\pi$, not $2\\pi$.",
            },
            { type: "summary", bullets: ["Solve for the inner expression first", "Divide all parts (including $2\\pi k$) by the multiplier"] },
          ],
        },
        {
          id: "l3-7-5",
          title: "Trig inequalities",
          estimateMin: 7,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 3 },
          beats: [
            { type: "intro", title: "Trig inequalities — find boundaries, test", stake: "Find where the equation equals the boundary value, then test which intervals satisfy the inequality." },
            { type: "derive", text: "Solve $\\cos\\theta > -1/2$ on $[-\\pi, \\pi]$. First find boundary: $\\cos\\theta = -1/2$.",
              line: "\\theta = \\pm 2\\pi/3" },
            { type: "narrate", text: "Boundaries split $[-\\pi, \\pi]$ into three intervals. Test one $\\theta$ in each: $\\cos$ is greater than $-1/2$ on $(-2\\pi/3, 2\\pi/3)$." },
            { type: "checkpoint", prompt: "Solve $\\sin\\theta > \\sqrt{3}/2$ on $[-\\pi, \\pi]$.",
              choices: [
                "$(-\\pi/3, \\pi/3)$",
                "$(\\pi/3, 2\\pi/3)$",
                "$(0, \\pi)$",
                "$(-\\pi/2, \\pi/2)$",
              ],
              answer: 1,
              explain: "Boundary $\\sin\\theta = \\sqrt{3}/2$ at $\\theta = \\pi/3, 2\\pi/3$. Test $\\pi/2$: $\\sin = 1 > \\sqrt{3}/2$ ✓. Other intervals fail.",
            },
            { type: "summary", bullets: ["Find boundaries from equality version", "Test one point per interval", "Take the union of intervals where the test passes"] },
          ],
        },
        {
          id: "l3-7-6",
          title: "Multi-tool: $6\\sin^2 x - 5\\sin x = 4$",
          estimateMin: 8,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Quadratic in trig", stake: "Substitute $u = \\sin x$. Solve quadratic. Back-substitute. Verify range. Standard hard FRQ move." },
            { type: "derive", text: "Let $u = \\sin x$:",
              line: "6u^2 - 5u - 4 = 0 \\Rightarrow u = \\dfrac{5 \\pm \\sqrt{25 + 96}}{12} = \\dfrac{5 \\pm 11}{12}" },
            { type: "derive", text: "Two roots:",
              line: "u = 16/12 = 4/3 \\text{ (reject — } |\\sin x| \\le 1\\text{)}; \\quad u = -1/2" },
            { type: "derive", text: "So $\\sin x = -1/2$ on $[\\pi/2, 3\\pi/2]$. Reference angle $\\pi/6$, sin negative in QIII:",
              line: "x = \\pi + \\pi/6 = 7\\pi/6" },
            { type: "highlight", text: "Note: $11\\pi/6$ also has $\\sin = -1/2$ but it's outside $[\\pi/2, 3\\pi/2]$. Reject.", focus: "interval-check" },
            { type: "checkpoint", prompt: "Why was $u = 4/3$ rejected?",
              choices: [
                "Wrong sign",
                "$\\sin x$ can't exceed 1",
                "Out of the equation's domain",
                "Doesn't satisfy the original equation",
              ],
              answer: 1,
              explain: "$|\\sin x| \\le 1$. $4/3 > 1$ is impossible.",
            },
            { type: "summary", bullets: ["Substitute, solve, back-substitute", "Reject $u$ values outside trig range", "Reject $x$ values outside given interval"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 3.8 Trig Identities
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-8",
      title: "Trig Identities",
      blurb: "Pythagorean. Sum/difference. Double-angle. Cofunction. Reflections.",
      lessons: [
        {
          id: "l3-8-1",
          title: "Pythagorean identities — derivation",
          estimateMin: 7,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 4, showSin: true, showCos: true },
          beats: [
            { type: "intro", title: "From the unit circle", stake: "$x^2 + y^2 = 1$ on the unit circle. $x = \\cos\\theta$, $y = \\sin\\theta$. Substitute." },
            { type: "formula-card", title: "Three Pythagorean identities", formula: "\\sin^2\\theta + \\cos^2\\theta = 1 \\\\ 1 + \\tan^2\\theta = \\sec^2\\theta \\\\ 1 + \\cot^2\\theta = \\csc^2\\theta" },
            { type: "derive", text: "First identity from circle equation:",
              line: "x^2 + y^2 = 1 \\Rightarrow \\cos^2\\theta + \\sin^2\\theta = 1" },
            { type: "derive", text: "Second from dividing by $\\cos^2$:",
              line: "1 + \\tan^2\\theta = \\sec^2\\theta" },
            { type: "checkpoint", prompt: "If $\\sin\\theta = 3/5$ and $\\theta$ in Q2, $\\cos\\theta = ?$",
              choices: ["$4/5$", "$-4/5$", "$3/4$", "$-3/4$"],
              answer: 1,
              explain: "$\\cos^2 = 1 - 9/25 = 16/25$, so $\\cos = \\pm 4/5$. Q2 means cos < 0: $-4/5$.",
            },
            { type: "summary", bullets: ["Three Pythagorean identities — memorize", "All come from $x^2 + y^2 = 1$"] },
          ],
        },
        {
          id: "l3-8-2",
          title: "Three Pythagorean rearrangements",
          estimateMin: 4,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Three useful rearrangements", stake: "Rewrite the basic Pythagorean identity in three forms — useful when simplifying." },
            { type: "formula-card", title: "Useful rearrangements",
              formula: "1 - \\sin^2\\theta = \\cos^2\\theta \\\\ 1 - \\cos^2\\theta = \\sin^2\\theta \\\\ \\sec^2\\theta - 1 = \\tan^2\\theta" },
            { type: "narrate", text: "These let you swap $1 - \\sin^2$ for $\\cos^2$ when it simplifies an expression." },
            { type: "summary", bullets: ["Memorize all three", "Use to substitute when reducing expressions"] },
          ],
        },
        {
          id: "l3-8-3",
          title: "Sum identities",
          estimateMin: 8,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Sum of angles", stake: "$\\sin(\\alpha + \\beta)$ in terms of individual sins and coses. Two formulas to memorize." },
            { type: "formula-card", title: "Sum identities",
              formula: "\\sin(\\alpha + \\beta) = \\sin\\alpha\\cos\\beta + \\cos\\alpha\\sin\\beta \\\\ \\cos(\\alpha + \\beta) = \\cos\\alpha\\cos\\beta - \\sin\\alpha\\sin\\beta" },
            { type: "narrate", text: "Note the SIGN PATTERN: sin keeps the operator's sign; cos FLIPS it ($+ \\to -$)." },
            { type: "derive", text: "Compute $\\sin(75°) = \\sin(45° + 30°)$:",
              line: "= \\sin 45 \\cos 30 + \\cos 45 \\sin 30 = \\dfrac{\\sqrt{2}}{2} \\cdot \\dfrac{\\sqrt{3}}{2} + \\dfrac{\\sqrt{2}}{2} \\cdot \\dfrac{1}{2} = \\dfrac{\\sqrt{6} + \\sqrt{2}}{4}" },
            { type: "summary", bullets: ["sin: $\\sin\\cos + \\cos\\sin$", "cos: $\\cos\\cos - \\sin\\sin$", "Sign pattern: cos flips"] },
          ],
        },
        {
          id: "l3-8-4",
          title: "Difference identities + sign rule",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Difference is the sum identity with a flipped sign", stake: "$\\sin(\\alpha - \\beta) = $ sum identity but minus instead of plus. Same for cos." },
            { type: "formula-card", title: "Difference identities",
              formula: "\\sin(\\alpha - \\beta) = \\sin\\alpha\\cos\\beta - \\cos\\alpha\\sin\\beta \\\\ \\cos(\\alpha - \\beta) = \\cos\\alpha\\cos\\beta + \\sin\\alpha\\sin\\beta" },
            { type: "narrate", text: "Same sign-flip rule: sin matches the operator, cos flips it." },
            { type: "checkpoint", prompt: "$\\cos(30° - 45°) = ?$",
              choices: [
                "$\\cos 30 \\cos 45 + \\sin 30 \\sin 45$",
                "$\\cos 30 \\cos 45 - \\sin 30 \\sin 45$",
                "$\\sin 30 \\cos 45 + \\cos 30 \\sin 45$",
                "$\\sin 30 \\cos 45 - \\cos 30 \\sin 45$",
              ],
              answer: 0,
              explain: "$\\cos(\\alpha - \\beta) = \\cos\\cos + \\sin\\sin$ (note: cos with MINUS in argument gets PLUS).",
            },
            { type: "summary", bullets: ["Sin: matches operator", "Cos: flips operator"] },
          ],
        },
        {
          id: "l3-8-5",
          title: "Double-angle from sum",
          estimateMin: 6,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Double angle = sum with $\\alpha = \\beta$", stake: "Plug $\\beta = \\alpha$ into sum identities. You get double-angle formulas — three forms for cos." },
            { type: "formula-card", title: "Double-angle identities",
              formula: "\\sin(2\\theta) = 2\\sin\\theta\\cos\\theta \\\\ \\cos(2\\theta) = \\cos^2\\theta - \\sin^2\\theta \\\\ = 1 - 2\\sin^2\\theta = 2\\cos^2\\theta - 1" },
            { type: "narrate", text: "The three forms of $\\cos(2\\theta)$ are equivalent — pick whichever makes your problem easier." },
            { type: "checkpoint", prompt: "If $\\sin\\theta = 1/3$, find $\\cos(2\\theta)$.",
              choices: ["$1/9$", "$2/3$", "$7/9$", "$8/9$"],
              answer: 2,
              explain: "$\\cos(2\\theta) = 1 - 2\\sin^2\\theta = 1 - 2/9 = 7/9$.",
            },
            { type: "summary", bullets: ["$\\sin(2\\theta) = 2\\sin\\theta\\cos\\theta$", "Three forms of $\\cos(2\\theta)$ — pick the one that fits your knowns"] },
          ],
        },
        {
          id: "l3-8-6",
          title: "Cofunction identities",
          estimateMin: 4,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 6 },
          beats: [
            { type: "intro", title: "Sin of complement = cos", stake: "Complementary angles ($\\pi/2 - \\theta$) swap sin and cos. Geometric reason: complementary angles make a right triangle." },
            { type: "formula-card", title: "Cofunction identities",
              formula: "\\sin(\\pi/2 - \\theta) = \\cos\\theta \\\\ \\cos(\\pi/2 - \\theta) = \\sin\\theta" },
            { type: "checkpoint", prompt: "$\\sin(60°) = ?$ (using cofunction)",
              choices: ["$\\sin(30°)$", "$\\cos(30°)$", "$\\cos(60°)$", "$\\sin(120°)$"],
              answer: 1,
              explain: "$\\sin(60°) = \\sin(90° - 30°) = \\cos(30°) = \\sqrt{3}/2$.",
            },
            { type: "summary", bullets: ["Sin and cos swap under complement", "$60°$ and $30°$, $\\pi/3$ and $\\pi/6$ are complement pairs"] },
          ],
        },
        {
          id: "l3-8-7",
          title: "Even/odd reflections",
          estimateMin: 5,
          artifact: "unit-circle",
          artifactInitial: { angle: Math.PI / 4 },
          beats: [
            { type: "intro", title: "Reflection identities — exam favorites", stake: "$\\cos$ is even (mirror across y-axis). $\\sin$ is odd (rotate 180°). Fully predictable." },
            { type: "formula-card", title: "Reflections",
              formula: "\\cos(-\\theta) = \\cos\\theta \\\\ \\sin(-\\theta) = -\\sin\\theta \\\\ \\cos(2\\pi - \\theta) = \\cos\\theta \\\\ \\sin(2\\pi - \\theta) = -\\sin\\theta" },
            { type: "checkpoint", prompt: "Angle $\\theta$ has terminal ray through $(-1.9, -0.64)$ on radius-2 circle. Find $\\cos(2\\pi - \\theta)$.",
              choices: ["$0.95$", "$-0.95$", "$0.32$", "$-0.32$"],
              answer: 1,
              explain: "$\\cos(2\\pi - \\theta) = \\cos\\theta$. $\\cos\\theta = x/r = -1.9/2 = -0.95$.",
            },
            { type: "summary", bullets: ["cos: even (no sign change)", "sin: odd (sign flips)"] },
          ],
        },
        {
          id: "l3-8-8",
          title: "Identity simplification drill",
          estimateMin: 10,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Simplification techniques", stake: "Common-denominator + Pythagorean substitution = solves most simplification problems." },
            { type: "derive", text: "Simplify $\\sec\\theta\\csc\\theta - \\cot\\theta$:",
              line: "= \\dfrac{1}{\\cos\\theta\\sin\\theta} - \\dfrac{\\cos\\theta}{\\sin\\theta} = \\dfrac{1 - \\cos^2\\theta}{\\sin\\theta\\cos\\theta} = \\dfrac{\\sin^2\\theta}{\\sin\\theta\\cos\\theta} = \\tan\\theta" },
            { type: "derive", text: "Rewrite $k(x) = \\dfrac{\\sin x \\cos x}{1 - \\sin^2 x}$ with one tan:",
              line: "= \\dfrac{\\sin x \\cos x}{\\cos^2 x} = \\dfrac{\\sin x}{\\cos x} = \\tan x" },
            { type: "derive", text: "Rewrite $h(x) = \\dfrac{\\sin^2 x - 1}{\\cos x}$ with one cos:",
              line: "\\sin^2 x - 1 = -(1 - \\sin^2 x) = -\\cos^2 x \\Rightarrow h(x) = \\dfrac{-\\cos^2 x}{\\cos x} = -\\cos x" },
            { type: "checkpoint", prompt: "Simplify $\\dfrac{1 - \\cos^2 x}{\\sin x}$.",
              choices: ["$0$", "$\\sin x$", "$\\cos x$", "$\\tan x$"],
              answer: 1,
              explain: "$1 - \\cos^2 x = \\sin^2 x$. Then $\\sin^2 x / \\sin x = \\sin x$.",
            },
            { type: "summary", bullets: [
              "Combine fractions to one denominator",
              "Substitute Pythagorean as needed",
              "Reduce common factors at the end",
            ] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 3.9 Polar
    // ─────────────────────────────────────────────────────────
    {
      id: "t3-9",
      title: "Polar Coordinates & Curves",
      blurb: "Polar ↔ rectangular. Circles, limaçons, roses. Negative r. Rate of change.",
      lessons: [
        {
          id: "l3-9-1",
          title: "Polar coordinates and conversion",
          estimateMin: 8,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => 3, thetaRange: [0, 2 * Math.PI], pointAt: Math.PI / 3 },
          beats: [
            { type: "intro", title: "Two coordinate systems for the same plane", stake: "$(r, \\theta)$ instead of $(x, y)$. Distance + angle. Useful for rotational symmetry." },
            { type: "formula-card", title: "Conversions", formula: "x = r\\cos\\theta, \\quad y = r\\sin\\theta \\\\ r = \\sqrt{x^2 + y^2}, \\quad \\theta = \\arctan(y/x) \\text{ (with quadrant adjustment)}" },
            { type: "narrate", text: "Polar to rectangular: pure formula, no thinking. Rectangular to polar: watch the quadrant when computing $\\theta$." },
            { type: "derive", text: "Convert $(2, 2\\sqrt{3})$ to polar:",
              line: "r = \\sqrt{4 + 12} = 4; \\quad \\theta = \\arctan(\\sqrt{3}) = \\pi/3" },
            { type: "checkpoint", prompt: "Convert polar $(4, \\pi/4)$ to rectangular.",
              choices: ["$(4, 4)$", "$(2, 2)$", "$(2\\sqrt{2}, 2\\sqrt{2})$", "$(1, 1)$"],
              answer: 2,
              explain: "$x = 4\\cos(\\pi/4) = 4 \\cdot \\sqrt{2}/2 = 2\\sqrt{2}$. Same for $y$.",
            },
            { type: "summary", bullets: ["Polar → rect: $x = r\\cos\\theta$, $y = r\\sin\\theta$", "Rect → polar: $r = \\sqrt{x^2 + y^2}$, $\\theta$ via arctan with quadrant"] },
          ],
        },
        {
          id: "l3-9-2",
          title: "Negative $r$ convention",
          estimateMin: 5,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => -2, thetaRange: [0, 2 * Math.PI] },
          beats: [
            { type: "intro", title: "Negative r = opposite direction", stake: "$(r, \\theta)$ with $r < 0$ is the same point as $(|r|, \\theta + \\pi)$. Go in the OPPOSITE direction." },
            { type: "narrate", text: "If $r = -2$ at angle $\\pi/3$: instead of moving 2 units along the $\\pi/3$ ray, move 2 units along the $\\pi/3 + \\pi = 4\\pi/3$ ray. Same point either way." },
            { type: "checkpoint", prompt: "Polar $(-3, \\pi/2)$ as rectangular?",
              choices: ["$(0, 3)$", "$(0, -3)$", "$(3, 0)$", "$(-3, 0)$"],
              answer: 1,
              explain: "$r = -3$ at angle $\\pi/2$ = $r = 3$ at angle $3\\pi/2$. That's $(0, -3)$ rectangular.",
            },
            { type: "summary", bullets: ["$(r, \\theta) = (|r|, \\theta + \\pi)$ when $r < 0$", "Negative r flips the direction"] },
          ],
        },
        {
          id: "l3-9-3",
          title: "Complex numbers in polar form",
          estimateMin: 7,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => Math.sqrt(34), thetaRange: [0, 2 * Math.PI], pointAt: Math.PI - Math.atan(5 / 3) },
          beats: [
            { type: "intro", title: "Complex numbers as polar points", stake: "$a + bi$ corresponds to point $(a, b)$. Distance from origin is $|z| = r$. Angle to point is $\\theta$." },
            { type: "formula-card", title: "Polar form", formula: "a + bi = r(\\cos\\theta + i\\sin\\theta), \\quad r = \\sqrt{a^2 + b^2}, \\ \\theta = \\arg(a + bi)" },
            { type: "derive", text: "Convert $-3 + 5i$ to polar.",
              line: "r = \\sqrt{9 + 25} = \\sqrt{34}; \\quad \\text{Q2: } \\theta = \\pi - \\arctan(5/3) \\approx 2.111" },
            { type: "checkpoint", prompt: "$|z|$ for $z = 4 - 3i$?",
              choices: ["$1$", "$5$", "$7$", "$25$"],
              answer: 1,
              explain: "$|z| = \\sqrt{4^2 + 3^2} = 5$.",
            },
            { type: "summary", bullets: ["Complex modulus = polar $r$", "Complex argument = polar $\\theta$"] },
          ],
        },
        {
          id: "l3-9-4",
          title: "Common polar curves library",
          estimateMin: 8,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => 2 * Math.cos(theta), thetaRange: [0, 2 * Math.PI] },
          beats: [
            { type: "intro", title: "A handful of recognizable shapes", stake: "Polar curves are mostly identifiable by inspection. Memorize the basic library." },
            { type: "formula-card", title: "Common curves",
              formula: "\\begin{array}{l|l} r = a & \\text{circle radius } |a| \\text{ at origin} \\\\ r = a\\cos\\theta & \\text{circle on x-axis} \\\\ r = a\\sin\\theta & \\text{circle on y-axis} \\\\ r = a + b\\cos\\theta & \\text{limaçon} \\\\ r = a\\cos(n\\theta) & \\text{rose curve} \\end{array}" },
            { type: "transform", text: "$r = 2\\cos\\theta$: circle, diameter 2, on the x-axis.", artifact: { fn: (theta: number) => 2 * Math.cos(theta), thetaRange: [-Math.PI / 2, Math.PI / 2] } },
            { type: "transform", text: "$r = 1 + \\cos\\theta$: cardioid (heart-shape).", artifact: { fn: (theta: number) => 1 + Math.cos(theta), thetaRange: [0, 2 * Math.PI] } },
            { type: "summary", bullets: ["$r = a\\cos\\theta$ → circle on x-axis", "$r = a + b\\cos\\theta$ → limaçon family", "$r = a\\cos(n\\theta)$ → rose"] },
          ],
        },
        {
          id: "l3-9-5",
          title: "Limaçon classification by $|a/b|$",
          estimateMin: 8,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => 2 + 3 * Math.cos(theta), thetaRange: [0, 2 * Math.PI] },
          beats: [
            { type: "intro", title: "Four limaçon types", stake: "$r = a + b\\cos\\theta$ has four shapes based on $|a/b|$. Memorize the boundaries." },
            { type: "formula-card", title: "Limaçon classification",
              formula: "\\begin{array}{l|l} |a/b| < 1 & \\text{inner loop} \\\\ |a/b| = 1 & \\text{cardioid} \\\\ 1 < |a/b| < 2 & \\text{dimpled} \\\\ |a/b| \\ge 2 & \\text{convex} \\end{array}" },
            { type: "transform", text: "$r = 3\\cos\\theta + 2$ — that's $a = 2, b = 3$, $|a/b| = 2/3 < 1$ → inner loop.",
              artifact: { fn: (theta: number) => 2 + 3 * Math.cos(theta), thetaRange: [0, 2 * Math.PI] } },
            { type: "transform", text: "$r = 2 + 2\\cos\\theta$ — $|a/b| = 1$ → cardioid.",
              artifact: { fn: (theta: number) => 2 + 2 * Math.cos(theta), thetaRange: [0, 2 * Math.PI] } },
            { type: "checkpoint", prompt: "Shape of $r = 4 + \\cos\\theta$?",
              choices: ["Inner loop", "Cardioid", "Dimpled", "Convex"],
              answer: 3,
              explain: "$|a/b| = 4 \\ge 2$ → convex limaçon. No dimple.",
            },
            { type: "summary", bullets: ["Compute $|a/b|$ — the ratio classifies", "<1: inner loop. =1: cardioid. <2: dimpled. ≥2: convex"] },
          ],
        },
        {
          id: "l3-9-6",
          title: "Rose curves: petal counting rule",
          estimateMin: 6,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => 2 * Math.cos(3 * theta), thetaRange: [0, 2 * Math.PI] },
          beats: [
            { type: "intro", title: "Roses — count petals", stake: "$r = a\\cos(n\\theta)$ or $a\\sin(n\\theta)$ creates a rose. $n$ odd: $n$ petals. $n$ even: $2n$ petals." },
            { type: "narrate", text: "Above: $r = 2\\cos(3\\theta)$ — $n = 3$ (odd) → 3 petals." },
            { type: "transform", text: "$r = 2\\cos(2\\theta)$ — $n = 2$ (even) → $2n = 4$ petals.",
              artifact: { fn: (theta: number) => 2 * Math.cos(2 * theta), thetaRange: [0, 2 * Math.PI] } },
            { type: "checkpoint", prompt: "How many petals in $r = 3\\sin(5\\theta)$?",
              choices: ["$3$", "$5$", "$10$", "$15$"],
              answer: 1,
              explain: "$n = 5$ is odd, so 5 petals.",
            },
            { type: "summary", bullets: ["$n$ odd → $n$ petals", "$n$ even → $2n$ petals"] },
          ],
        },
        {
          id: "l3-9-7",
          title: "Polar rate of change vs distance $|r|$",
          estimateMin: 7,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => -3 * Math.cos(2 * theta), thetaRange: [Math.PI / 4, Math.PI / 2] },
          beats: [
            { type: "intro", title: "Distance from origin = $|r|$, not $r$", stake: "Watch this: $r$ can be negative, but DISTANCE from origin is always $|r|$. Tracking distance vs $r$ is different." },
            { type: "narrate", text: "On a polar curve, the value of $r$ might decrease while the DISTANCE from origin INCREASES — if $r$ is becoming more negative." },
            { type: "derive", text: "$r(\\theta) = 2\\sin\\theta\\cos\\theta = \\sin(2\\theta)$ on $[7\\pi/12, 3\\pi/4]$.",
              line: "2\\theta \\in [7\\pi/6, 3\\pi/2] \\Rightarrow r \\in [-1/2, -1] \\text{ (decreasing)}" },
            { type: "narrate", text: "$r$ DECREASES from $-1/2$ to $-1$. But $|r|$ INCREASES from $1/2$ to $1$." },
            { type: "checkpoint", prompt: "On the same interval, the DISTANCE from origin is:",
              choices: ["Decreasing", "Increasing", "Constant", "Not monotonic"],
              answer: 1,
              explain: "$|r|$ goes from 1/2 to 1 — increasing.",
            },
            { type: "summary", bullets: ["Distance = $|r|$", "When $r < 0$, $r$ decreasing means $|r|$ increasing"] },
          ],
        },
        {
          id: "l3-9-8",
          title: "Above/below polar axis, near/far",
          estimateMin: 6,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => -3 * Math.cos(2 * theta), thetaRange: [Math.PI / 4, Math.PI / 2] },
          beats: [
            { type: "intro", title: "Quadrant table", stake: "Sign of $r$ and quadrant of $\\theta$ together tell you the actual quadrant of the point." },
            { type: "formula-card", title: "Sign × quadrant",
              formula: "\\begin{array}{c|c|c} r & \\theta & \\text{actual} \\\\ \\hline + & \\text{Q}n & \\text{Q}n \\\\ - & \\text{Q}1 & \\text{Q}3 \\\\ - & \\text{Q}2 & \\text{Q}4 \\\\ \\text{etc.} & & \\end{array}" },
            { type: "narrate", text: "Negative $r$ flips the point to the OPPOSITE quadrant — opposite means add $\\pi$ to the angle." },
            { type: "checkpoint", prompt: "$r = -1 + \\sin\\theta$ on $(0, \\pi/2)$. Where is the actual point?",
              choices: [
                "Above polar axis (Q1)",
                "Below polar axis (Q3 or Q4)",
                "On the axis",
                "Outside the page",
              ],
              answer: 1,
              explain: "On $(0, \\pi/2)$, $\\sin\\theta < 1$, so $r < 0$. $\\theta$ in Q1 + $r < 0$ ⇒ actual point in Q3 (below).",
            },
            { type: "summary", bullets: ["Positive r: same quadrant as θ", "Negative r: opposite quadrant"] },
          ],
        },
        {
          id: "l3-9-9",
          title: "Polar relative max",
          estimateMin: 4,
          artifact: "polar-plane",
          artifactInitial: { fn: (theta: number) => 4 - 7 * Math.sin(theta), thetaRange: [0, 2 * Math.PI], pointAt: 3 * Math.PI / 2 },
          beats: [
            { type: "intro", title: "Polar relative max of $r$", stake: "Find where $r$ is largest as a function of $\\theta$. For $r = a + b\\sin\\theta$, max happens where $\\sin\\theta = -\\text{sign}(b)$." },
            { type: "derive", text: "$r = 4 - 7\\sin\\theta$. Want $r$ max — $\\sin\\theta$ as negative as possible:",
              line: "\\sin\\theta = -1 \\text{ at } \\theta = 3\\pi/2 \\Rightarrow r = 4 - 7(-1) = 11" },
            { type: "checkpoint", prompt: "Relative max of $r = 5 + 3\\cos\\theta$ at?",
              choices: ["$(2, 0)$", "$(8, 0)$", "$(8, \\pi)$", "$(2, \\pi)$"],
              answer: 1,
              explain: "Want $\\cos\\theta = 1$ to maximize. At $\\theta = 0$: $r = 5 + 3 = 8$.",
            },
            { type: "summary", bullets: ["Maximize the trig term", "$r_{\\max} = a + |b|$ for $r = a + b\\sin/\\cos\\theta$"] },
          ],
        },
      ],
    },
  ],
};
