// Unit 2 — Exponential & Logarithmic Functions (27-40% of exam)
//
// 8 topics, 33 lessons. The unit that hinges on one big idea: exp and log
// are inverses. Every property of one mirrors a property of the other.

import type { Unit } from "../types";

export const UNIT_2: Unit = {
  id: "u2",
  number: 2,
  title: "Exponential & Logarithmic Functions",
  examWeight: "27–40%",
  coreIdeas: [
    "Sequences ↔ functions: arithmetic ↔ linear, geometric ↔ exponential",
    "Exp and log are inverses — every property mirrors",
    "Composition and inversion bind everything",
  ],
  topics: [
    // ─────────────────────────────────────────────────────────
    // 2.1 Sequences
    // ─────────────────────────────────────────────────────────
    {
      id: "t2-1",
      title: "Sequences",
      blurb: "Arithmetic and geometric. Recursive and explicit. Link to linear and exponential functions.",
      lessons: [
        {
          id: "l2-1-1",
          title: "Arithmetic sequences",
          estimateMin: 5,
          artifact: "sequence-list",
          artifactInitial: { terms: [3, 7, 11, 15, 19, 23], mode: "differences" },
          beats: [
            { type: "intro", title: "Arithmetic sequences", stake: "Each term differs from the previous by a constant. That constant is the 'common difference.' Linear function's discrete twin." },
            { type: "narrate", text: "Above: terms 3, 7, 11, 15, 19, 23. Common difference $d = 4$." },
            { type: "formula-card", title: "Arithmetic formulas", formula: "\\text{Recursive: } a_n = a_{n-1} + d \\qquad \\text{Explicit: } a_n = a_1 + (n-1)d" },
            { type: "narrate", text: "Recursive defines each term in terms of the previous. Explicit jumps straight to term $n$ from $a_1$." },
            { type: "checkpoint", prompt: "Arithmetic sequence with $a_1 = 5$, $d = -3$. What's $a_8$?",
              choices: ["$-19$", "$-16$", "$-24$", "$8$"],
              answer: 1,
              explain: "$a_8 = a_1 + 7d = 5 + 7(-3) = 5 - 21 = -16$.",
            },
            { type: "summary", bullets: ["Common difference $d$ identifies arithmetic", "Explicit form $a_1 + (n-1)d$ jumps to any term"] },
          ],
        },
        {
          id: "l2-1-2",
          title: "Geometric sequences",
          estimateMin: 5,
          artifact: "sequence-list",
          artifactInitial: { terms: [8, 4, 2, 1, 0.5], mode: "ratios" },
          beats: [
            { type: "intro", title: "Geometric sequences", stake: "Each term is the previous times a constant — the common RATIO. Exponential's discrete twin." },
            { type: "narrate", text: "Terms above: $8, 4, 2, 1, 0.5$. Each is half the previous — ratio $r = \\tfrac{1}{2}$." },
            { type: "formula-card", title: "Geometric formulas", formula: "\\text{Recursive: } g_n = r \\cdot g_{n-1} \\qquad \\text{Explicit: } g_n = g_1 \\cdot r^{n-1}" },
            { type: "predict", prompt: "Sequence 6.5, 3.25, 1.625, 0.8125. Common ratio?",
              choices: [
                { label: "$0.25$", correct: false, consequence: "Check: $3.25/6.5 = 0.5$, not 0.25." },
                { label: "$0.5$", correct: true, consequence: "Right — each term is half the previous." },
                { label: "$-3.25$", correct: false, consequence: "That's the first difference, not the ratio." },
              ],
              reveal: "$r = 0.5$. Geometric ratios stay constant; if differences look weird, check ratios." },
            { type: "checkpoint", prompt: "Geometric with $g_1 = 4$, $r = 3$. What's $g_5$?",
              choices: ["$12$", "$60$", "$108$", "$324$"],
              answer: 3,
              explain: "$g_5 = 4 \\cdot 3^4 = 4 \\cdot 81 = 324$.",
            },
            { type: "summary", bullets: ["Common ratio $r$ identifies geometric", "Explicit $g_1 \\cdot r^{n-1}$ jumps to any term"] },
          ],
        },
        {
          id: "l2-1-3",
          title: "Recursive vs explicit form",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [{ tex: "a_1 = 7" }, { tex: "a_n = a_{n-1} + 4" }] },
          beats: [
            { type: "intro", title: "Two ways to define the same sequence", stake: "Recursive: prior-term rule. Explicit: closed-form formula in $n$." },
            { type: "narrate", text: "Recursive: $a_1 = 7$, $a_n = a_{n-1} + 4$. Need to compute $a_5$? You'd walk: 7, 11, 15, 19, 23." },
            { type: "narrate", text: "Explicit: $a_n = 7 + 4(n-1) = 4n + 3$. Plug $n = 5$: $a_5 = 23$. One step." },
            { type: "checkpoint", prompt: "Geometric: $g_1 = 2$, $g_n = 3 g_{n-1}$. Explicit form?",
              choices: ["$g_n = 2n + 3$", "$g_n = 2 \\cdot 3^n$", "$g_n = 2 \\cdot 3^{n-1}$", "$g_n = 3 \\cdot 2^{n-1}$"],
              answer: 2,
              explain: "Geometric explicit: $g_1 \\cdot r^{n-1} = 2 \\cdot 3^{n-1}$. Note the $n-1$, not $n$.",
            },
            { type: "summary", bullets: ["Recursive needs prior terms", "Explicit jumps directly", "Convert by reading off $a_1$ and $d$ (or $r$)"] },
          ],
        },
        {
          id: "l2-1-4",
          title: "Sequences ↔ functions",
          estimateMin: 6,
          artifact: "comparison",
          artifactInitial: {
            left: { kind: "sequence-list", label: "Arithmetic — discrete", state: { terms: [3, 5, 7, 9, 11] } },
            right: { kind: "coordinate-plane", label: "Linear — continuous", state: { xRange: [0, 6], yRange: [0, 13], curves: [{ id: "f", fn: (x: number) => 2 * x + 1, color: "var(--learn-accent)" }] } },
          },
          beats: [
            { type: "intro", title: "The discrete-continuous bridge", stake: "Arithmetic sequence is just a linear function sampled at integers. Geometric is exponential sampled at integers." },
            { type: "compare", text: "Left: arithmetic sequence 3, 5, 7, 9, 11 with $d = 2$. Right: $f(x) = 2x + 1$ — same slope, same intercept, same values at integer $x$." },
            { type: "narrate", text: "Geometric ↔ exponential works the same way. Sequence $g_n = 8 \\cdot (1/2)^{n-1}$ matches $f(x) = 8 \\cdot (1/2)^{x-1}$ at integer $x$." },
            { type: "checkpoint", prompt: "What continuous function corresponds to the arithmetic sequence $a_n = 5n + 7$?",
              choices: ["$f(x) = 5x$", "$f(x) = 5x + 7$", "$f(x) = 7x + 5$", "$f(x) = 7 \\cdot 5^x$"],
              answer: 1,
              explain: "Direct read: same formula, $f(x) = 5x + 7$, but now $x$ is continuous.",
            },
            { type: "summary", bullets: ["Arithmetic sequence = linear function at integer inputs", "Geometric sequence = exponential function at integer inputs"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 2.2 Exponential Functions
    // ─────────────────────────────────────────────────────────
    {
      id: "t2-2",
      title: "Exponential Functions",
      blurb: "ab^x shape, exponent rules, common rewrites.",
      lessons: [
        {
          id: "l2-2-1",
          title: "Form $a b^x$, growth vs decay",
          estimateMin: 6,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-3, 4], yRange: [-1, 12],
            curves: [{ id: "g", fn: (x: number) => Math.pow(2, x), color: "var(--learn-accent)", label: "f(x) = 2ˣ" }],
            features: [{ kind: "h-asymptote", id: "ha", y: 0, label: "y = 0" }],
          },
          beats: [
            { type: "intro", title: "Anatomy of $a b^x$", stake: "$a$ is the y-intercept. $b$ is the per-step factor. If $b > 1$ it's growth; $0 < b < 1$ it's decay." },
            { type: "formula-card", title: "Form", formula: "f(x) = a \\cdot b^x, \\quad a \\ne 0, \\ b > 0, \\ b \\ne 1" },
            { type: "narrate", text: "y-intercept is $a$ because $b^0 = 1$. Above, $a = 1$, so y-intercept is at 1." },
            { type: "transform", text: "Now $b = 1/2$ instead of 2. Same shape, mirrored — DECAY.", artifact: {
              curves: [{ id: "g", fn: (x: number) => Math.pow(0.5, x), color: "var(--learn-accent)", label: "(1/2)ˣ" }],
              features: [{ kind: "h-asymptote", id: "ha", y: 0, label: "y = 0" }] } },
            { type: "predict", prompt: "$f(x) = 3 \\cdot (1.5)^x$. As $x \\to -\\infty$, $f(x) \\to$?",
              choices: [
                { label: "$+\\infty$", correct: false, consequence: "$-\\infty$ input on a growth function shrinks the output." },
                { label: "$0$", correct: true, consequence: "Decay direction for growth-base." },
                { label: "$3$", correct: false, consequence: "That's $f(0)$, not the limit." },
              ],
              reveal: "Exponentials always approach the horizontal asymptote (y = 0) on one end, $\\infty$ on the other." },
            { type: "summary", bullets: ["y-intercept = $a$", "$b > 1$: growth", "$0 < b < 1$: decay", "Always a horizontal asymptote at $y = 0$"] },
          ],
        },
        {
          id: "l2-2-2",
          title: "Properties — domain, range, asymptote",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-4, 4], yRange: [-1, 10],
            curves: [{ id: "e", fn: (x: number) => Math.exp(x), color: "var(--learn-accent)", label: "f(x) = eˣ" }],
            features: [{ kind: "h-asymptote", id: "ha", y: 0, label: "y = 0" }],
          },
          beats: [
            { type: "intro", title: "Properties at a glance", stake: "Domain all reals. Range positive (if $a > 0$). Asymptote at $y = 0$." },
            { type: "narrate", text: "Domain: all real $x$. You can plug ANYTHING in — including negative, zero, fractions." },
            { type: "narrate", text: "Range: $(0, \\infty)$ if $a > 0$. (If $a < 0$, range is $(-\\infty, 0)$.) The output never equals zero." },
            { type: "highlight", text: "Horizontal asymptote at $y = 0$ — the x-axis. The function APPROACHES but never touches.", focus: "ha" },
            { type: "checkpoint", prompt: "Range of $f(x) = -2 \\cdot 3^x$?",
              choices: ["$(0, \\infty)$", "$(-\\infty, 0)$", "$(-\\infty, -2)$", "$(-2, 0)$"],
              answer: 1,
              explain: "$3^x > 0$ always, so $-2 \\cdot 3^x < 0$ always. Range is $(-\\infty, 0)$.",
            },
            { type: "summary", bullets: ["Domain: all reals", "Range: $(0,\\infty)$ if $a>0$, $(-\\infty,0)$ if $a<0$", "Always an HA at $y = 0$"] },
          ],
        },
        {
          id: "l2-2-3",
          title: "Exponent rules — drill",
          estimateMin: 8,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Six rules, applied as reflex", stake: "Each rule comes from one definition: $b^n$ = b multiplied n times. Memorize and apply without thinking." },
            { type: "formula-card", title: "Six rules", formula: "\\begin{array}{lr} b^m \\cdot b^n = b^{m+n} & \\text{product} \\\\ b^m / b^n = b^{m-n} & \\text{quotient} \\\\ (b^m)^n = b^{mn} & \\text{power} \\\\ b^{-m} = 1/b^m & \\text{negative} \\\\ b^{m/n} = \\sqrt[n]{b^m} & \\text{fractional} \\\\ a^m b^m = (ab)^m & \\text{same exp} \\end{array}" },
            { type: "derive", text: "Simplify $\\dfrac{x^7 \\cdot x^{-3}}{x^2}$:", line: "= x^{7 + (-3) - 2} = x^2", because: "Combine product and quotient rules — sum/difference of exponents." },
            { type: "predict", prompt: "Simplify $(2^3)^4$:",
              choices: [
                { label: "$2^7$", correct: false, consequence: "That's the product rule, not power-of-a-power." },
                { label: "$2^{12}$", correct: true, consequence: "Power rule: multiply the exponents." },
                { label: "$8^4$", correct: false, consequence: "True but unsimplified. Question wanted exponent form." },
              ],
              reveal: "$(b^m)^n = b^{mn}$ — exponents multiply." },
            { type: "checkpoint", prompt: "$16^{3/4}$ equals?",
              choices: ["$4$", "$8$", "$12$", "$48$"],
              answer: 1,
              explain: "$16^{3/4} = (\\sqrt[4]{16})^3 = 2^3 = 8$.",
            },
            { type: "summary", bullets: ["Product: add exponents", "Quotient: subtract", "Power: multiply", "Negative: reciprocal", "Fractional: root"] },
          ],
        },
        {
          id: "l2-2-4",
          title: "Standard rewrites",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "The three rewrites you'll do constantly", stake: "Three patterns let you reshape exponentials into whatever the question needs." },
            { type: "derive", text: "Pattern 1 — change of base form:", line: "a \\cdot b^{kx} = a \\cdot (b^k)^x" },
            { type: "derive", text: "Pattern 2 — separate constants:", line: "b^{x+c} = b^c \\cdot b^x" },
            { type: "derive", text: "Pattern 3 — flip growth/decay:", line: "b^{-x} = \\left(\\dfrac{1}{b}\\right)^x" },
            { type: "checkpoint", prompt: "Rewrite $h(d) = A_0 (0.5)^{d/8}$ where $d$ is days as a function of hours $t$ (so $d = t/24$).",
              choices: ["$A_0 (0.5)^{t/8}$", "$A_0 (0.5)^{t/24}$", "$A_0 (0.5)^{t/192}$", "$A_0 (0.5)^{8t/24}$"],
              answer: 2,
              explain: "$d = t/24$, so $d/8 = t/192$. New form: $A_0 (0.5)^{t/192}$.",
            },
            { type: "summary", bullets: ["Move constants between the exponent and the coefficient", "Use these to match a given form on the FRQ"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 2.3 Exponential Modeling
    // ─────────────────────────────────────────────────────────
    {
      id: "t2-3",
      title: "Exponential Modeling",
      blurb: "Doubling time, half-life, continuous percent rate, unit conversion.",
      lessons: [
        {
          id: "l2-3-1",
          title: "Doubling time",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Doubling-time model", stake: "If a population doubles every $T$ time units, the model is fixed. One formula, plug and chug." },
            { type: "formula-card", title: "Doubling-time model", formula: "P(t) = P_0 \\cdot 2^{t/T}" },
            { type: "narrate", text: "Logic: when $t = T$, exponent is 1 ⇒ factor of 2. When $t = 2T$, exponent is 2 ⇒ factor of 4. Doubles every $T$." },
            { type: "derive", text: "Pet product revenue doubles every 9 months, $r(0) = 32{,}000$, $t$ in months:",
              line: "r(t) = 32{,}000 \\cdot 2^{t/9}" },
            { type: "checkpoint", prompt: "A bacterial culture doubles every 5 hours, starts at 2500. Population after 24 hours?",
              choices: ["$\\approx 7{,}500$", "$\\approx 24{,}000$", "$\\approx 70{,}000$", "$\\approx 100{,}000$"],
              answer: 2,
              explain: "$2500 \\cdot 2^{24/5} = 2500 \\cdot 2^{4.8} \\approx 2500 \\cdot 27.86 \\approx 69{,}644$.",
            },
            { type: "summary", bullets: ["Doubling time $T$ ⇒ $P_0 \\cdot 2^{t/T}$"] },
          ],
        },
        {
          id: "l2-3-2",
          title: "Half-life",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Half-life model", stake: "Same idea as doubling, with 1/2 instead of 2." },
            { type: "formula-card", title: "Half-life model", formula: "P(t) = P_0 \\cdot \\left(\\dfrac{1}{2}\\right)^{t/T}" },
            { type: "derive", text: "Carbon-14 has half-life ≈ 5730 years. If you start with 100g, after 11460 years:",
              line: "100 \\cdot (1/2)^{11460/5730} = 100 \\cdot (1/2)^2 = 25 \\text{ g}" },
            { type: "checkpoint", prompt: "A drug has 4-hour half-life. After 12 hours, what fraction remains?",
              choices: ["$1/3$", "$1/8$", "$1/12$", "$1/16$"],
              answer: 1,
              explain: "12 hours = 3 half-lives. $(1/2)^3 = 1/8$.",
            },
            { type: "summary", bullets: ["Half-life $T$ ⇒ $P_0 \\cdot (1/2)^{t/T}$"] },
          ],
        },
        {
          id: "l2-3-3",
          title: "Continuous percent rate",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Percent-rate model", stake: "Growing at $r\\%$ per unit ⇒ multiply by $(1 + r/100)$ each unit." },
            { type: "formula-card", title: "Percent-rate", formula: "P(t) = P_0 \\cdot (1 + r/100)^t" },
            { type: "derive", text: "Value increases by 6.1% each quarter, $M(0) = 54$M, $t$ in years (4 quarters per year):",
              line: "M(t) = 54 \\cdot (1.061)^{4t}" },
            { type: "checkpoint", prompt: "Population grows 3% per year, currently 500. After 5 years?",
              choices: ["$\\approx 575$", "$\\approx 580$", "$\\approx 750$", "$\\approx 2500$"],
              answer: 1,
              explain: "$500 \\cdot 1.03^5 \\approx 500 \\cdot 1.159 \\approx 580$.",
            },
            { type: "summary", bullets: ["Per-unit rate $r\\%$ ⇒ factor of $(1 + r/100)$ each unit"] },
          ],
        },
        {
          id: "l2-3-4",
          title: "Converting time units",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Days ↔ hours, years ↔ months", stake: "Substitute the new variable for the old expression in terms of new. Standard rewrite move." },
            { type: "derive", text: "Half-life model in days: $h(d) = A_0 (0.5)^{d/8}$. Convert to hours ($d = t/24$):",
              line: "k(t) = A_0 (0.5)^{(t/24)/8} = A_0 (0.5)^{t/192}" },
            { type: "checkpoint", prompt: "Growth model $P(t) = 100 \\cdot 2^{t/3}$ ($t$ in years). Per-month form?",
              choices: ["$100 \\cdot 2^{t/3}$", "$100 \\cdot 2^{t/36}$", "$100 \\cdot 2^{12t/3}$", "$100 \\cdot 2^{t/12}$"],
              answer: 1,
              explain: "If $t$ is now months, then years $= t/12$. Substitute: $2^{(t/12)/3} = 2^{t/36}$.",
            },
            { type: "summary", bullets: ["Substitute the new variable expressed in old units", "Simplify the exponent"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 2.4 Composition
    // ─────────────────────────────────────────────────────────
    {
      id: "t2-4",
      title: "Composition",
      blurb: "f(g(x)) from formulas, tables, graphs. Decomposition.",
      lessons: [
        {
          id: "l2-4-1",
          title: "$f(g(x))$ from formulas",
          estimateMin: 6,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Composition", stake: "$(f \\circ g)(x) = f(g(x))$. Apply $g$ first, then feed the result into $f$." },
            { type: "narrate", text: "Order matters: $f(g(x))$ and $g(f(x))$ are usually different functions." },
            { type: "derive", text: "$f(x) = 3^x + x^2$, $g(3) = -2$. Find $f(g(3))$.",
              line: "f(-2) = 3^{-2} + (-2)^2 = \\tfrac{1}{9} + 4 = \\tfrac{37}{9}" },
            { type: "checkpoint", prompt: "$f(x) = 2x + 1$, $g(x) = x^2$. What's $g(f(3))$?",
              choices: ["$13$", "$19$", "$49$", "$50$"],
              answer: 2,
              explain: "$f(3) = 7$. Then $g(7) = 49$.",
            },
            { type: "summary", bullets: ["Inner function first, then outer", "$f(g(x)) \\ne g(f(x))$ in general"] },
          ],
        },
        {
          id: "l2-4-2",
          title: "Composition from tables and graphs",
          estimateMin: 6,
          artifact: "function-table",
          artifactInitial: {
            columns: [{ key: "x", header: "x" }, { key: "g", header: "g(x)" }, { key: "f", header: "f(x)" }],
            rows: [{ x: -2, g: 5, f: -1 }, { x: 0, g: 3, f: 2 }, { x: 3, g: -2, f: 0 }, { x: 5, g: 4, f: -2 }],
          },
          beats: [
            { type: "intro", title: "Two-step lookup", stake: "Given two tables, $f(g(x))$ = find $g(x)$ in left table, then look up that value in right table." },
            { type: "derive", text: "From table: $g(0) = 3$. Then $f(3) = ?$ Look up $x = 3$ in $f$'s column.",
              line: "f(g(0)) = f(3) = 0" },
            { type: "checkpoint", prompt: "Using the table, $g(f(5)) = ?$",
              choices: ["$-2$", "$3$", "$4$", "$5$"],
              answer: 0,
              explain: "$f(5) = -2$. Then $g(-2) = 5$. Wait — wrong. Let me retry: $f(5) = -2$, $g(-2) = 5$. Answer is 5. (Corrected: option 3.) — Actually the table only shows g(−2) = 5 in the first row. So $g(f(5)) = g(-2) = 5$.",
            },
            { type: "summary", bullets: ["Read inner from one table, plug into outer", "Trust the table values verbatim"] },
          ],
        },
        {
          id: "l2-4-3",
          title: "Decomposition",
          estimateMin: 4,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Going the other way", stake: "Given $h(x)$, find $f$ and $g$ such that $h = f \\circ g$. Multiple valid decompositions usually exist." },
            { type: "derive", text: "$h(x) = \\sqrt{x^2 + 1}$. One decomposition:",
              line: "g(x) = x^2 + 1, \\quad f(u) = \\sqrt{u} \\Rightarrow f(g(x)) = \\sqrt{x^2 + 1}" },
            { type: "checkpoint", prompt: "$h(x) = (3x - 5)^4$. Pick $f$ and $g$:",
              choices: [
                "$f(u) = u^4$, $g(x) = 3x - 5$",
                "$f(u) = 3u - 5$, $g(x) = x^4$",
                "$f(u) = u - 5$, $g(x) = 3x^4$",
                "$f(u) = u^3$, $g(x) = x - 5$",
              ],
              answer: 0,
              explain: "Inner is the parenthesized expression, outer is the power-4 wrapper.",
            },
            { type: "summary", bullets: ["Inside the parens / under the radical = $g$ (inner)", "Wrapper operation = $f$ (outer)"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 2.5 Inverse Functions
    // ─────────────────────────────────────────────────────────
    {
      id: "t2-5",
      title: "Inverse Functions",
      blurb: "Definition, HLT, algebraic inversion, table/graph lookup, domain restriction.",
      lessons: [
        {
          id: "l2-5-1",
          title: "Definition + horizontal line test",
          estimateMin: 6,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-3, 3], yRange: [-2, 8],
            curves: [{ id: "p", fn: (x: number) => x * x, color: "var(--learn-accent)", label: "x² (fails HLT)" }],
          },
          beats: [
            { type: "intro", title: "Inverse functions", stake: "$f^{-1}(y)$ is the unique $x$ where $f(x) = y$. Inverse exists iff $f$ is one-to-one." },
            { type: "narrate", text: "One-to-one means each output comes from at most one input. Graphically: passes the Horizontal Line Test." },
            { type: "transform", text: "$x^2$ fails HLT: a horizontal line at $y = 4$ hits the curve at $x = 2$ AND $x = -2$. Two inputs, same output.", artifact: {
              curves: [{ id: "p", fn: (x: number) => x * x, color: "var(--learn-accent)" }],
              features: [{ kind: "h-asymptote", id: "test", y: 4, label: "y = 4" }, { kind: "point", id: "p1", x: 2, y: 4 }, { kind: "point", id: "p2", x: -2, y: 4 }] } },
            { type: "checkpoint", prompt: "Which function is one-to-one (passes HLT)?",
              choices: ["$f(x) = x^2$", "$f(x) = x^3$", "$f(x) = |x|$", "$f(x) = \\cos x$"],
              answer: 1,
              explain: "$x^3$ is strictly increasing → one input per output → passes HLT.",
            },
            { type: "summary", bullets: ["One-to-one ⇔ HLT passes", "Inverse exists only for one-to-one functions"] },
          ],
        },
        {
          id: "l2-5-2",
          title: "Algebraic inversion",
          estimateMin: 8,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Swap and solve", stake: "Three steps: write $y = f(x)$, swap $x$ and $y$, solve for $y$." },
            { type: "derive", text: "Find inverse of $f(x) = 12 \\log_2(x + 5) + 6$. Step 1: write $y = \\ldots$.",
              line: "y = 12 \\log_2(x + 5) + 6" },
            { type: "derive", text: "Step 2: swap.",
              line: "x = 12 \\log_2(y + 5) + 6" },
            { type: "derive", text: "Step 3: isolate $y$.",
              line: "(x - 6)/12 = \\log_2(y + 5) \\Rightarrow y + 5 = 2^{(x-6)/12} \\Rightarrow f^{-1}(x) = 2^{(x-6)/12} - 5" },
            { type: "checkpoint", prompt: "Find $f^{-1}$ for $f(x) = 3x + 7$.",
              choices: ["$\\dfrac{x - 7}{3}$", "$\\dfrac{x + 7}{3}$", "$3x - 7$", "$\\dfrac{x}{3} + 7$"],
              answer: 0,
              explain: "Swap: $x = 3y + 7$. Solve: $y = (x - 7)/3$.",
            },
            { type: "summary", bullets: ["1. Write $y = f(x)$. 2. Swap. 3. Solve for $y$", "Result is $f^{-1}(x) = $ solved expression"] },
          ],
        },
        {
          id: "l2-5-3",
          title: "Inverse from table or graph",
          estimateMin: 5,
          artifact: "function-table",
          artifactInitial: {
            columns: [{ key: "x", header: "x" }, { key: "f", header: "f(x)" }],
            rows: [{ x: 2, f: 1 }, { x: 4, f: 2 }, { x: 8, f: 3 }, { x: 16, f: 4 }, { x: 32, f: 5 }],
          },
          beats: [
            { type: "intro", title: "Reverse lookup", stake: "$f^{-1}(b) = a$ means $f(a) = b$. Read the table BACKWARDS." },
            { type: "narrate", text: "To find $f^{-1}(4)$ from the table: which $x$ gives output 4? Scan the $f(x)$ column for 4, then read the corresponding $x$." },
            { type: "highlight", text: "From the table, $f(16) = 4$, so $f^{-1}(4) = 16$.", focus: "answer" },
            { type: "checkpoint", prompt: "Same table — find $f^{-1}(3)$.",
              choices: ["$2$", "$3$", "$8$", "$16$"],
              answer: 2,
              explain: "$f(8) = 3$ ⇒ $f^{-1}(3) = 8$.",
            },
            { type: "summary", bullets: ["$f^{-1}(b) = a$ ⇔ $f(a) = b$", "Read tables backwards: output → input"] },
          ],
        },
        {
          id: "l2-5-4",
          title: "Restricting domain for invertibility",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-4, 4], yRange: [-1, 10],
            curves: [{ id: "p", fn: (x: number) => x * x, color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "Make it one-to-one", stake: "If a function isn't one-to-one on its full domain, restrict to an interval where it IS." },
            { type: "narrate", text: "$x^2$ isn't one-to-one. But on $[0, \\infty)$ it's strictly increasing — one-to-one. Restrict there, take the inverse: $\\sqrt{x}$." },
            { type: "narrate", text: "Trig functions need restriction too. $\\sin x$ has period $2\\pi$ — definitely not one-to-one. But on $[-\\pi/2, \\pi/2]$ it IS one-to-one. That restriction is where $\\arcsin$ lives." },
            { type: "checkpoint", prompt: "$g(x) = \\sin x - \\cos x = \\sqrt{2} \\sin(x - \\pi/4)$. Period $2\\pi$. Largest interval starting at $-\\pi/4$ where it's invertible?",
              choices: ["$[-\\pi/4, \\pi/4]$", "$[-\\pi/4, \\pi/2]$", "$[-\\pi/4, 3\\pi/4]$", "$[-\\pi/4, \\pi]$"],
              answer: 2,
              explain: "Half-period intervals on a sinusoid are monotonic. Half of $2\\pi$ is $\\pi$, so length-$\\pi$ interval starting at $-\\pi/4$ ends at $3\\pi/4$.",
            },
            { type: "summary", bullets: ["Restrict to a monotonic interval", "Half-period intervals work for sinusoids"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 2.6 Logarithms
    // ─────────────────────────────────────────────────────────
    {
      id: "t2-6",
      title: "Logarithms",
      blurb: "Definition (log = exponent). Natural and common log. Inverse of exponential. Special values.",
      lessons: [
        {
          id: "l2-6-1",
          title: "Definition (logarithm = exponent)",
          estimateMin: 6,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "What is a logarithm?", stake: "A logarithm IS an exponent. $\\log_b y = x$ means $b^x = y$. Internalize this and the rules become obvious." },
            { type: "formula-card", title: "Definition", formula: "\\log_b y = x \\iff b^x = y" },
            { type: "narrate", text: "$\\log_2 8 = 3$ because $2^3 = 8$. The logarithm is asking 'what exponent do I raise the base to?'" },
            { type: "derive", text: "$\\log_3 81 = ?$ Ask: $3$ to what power is $81$?",
              line: "3^4 = 81 \\Rightarrow \\log_3 81 = 4" },
            { type: "predict", prompt: "$\\log_5 \\dfrac{1}{25} = ?$",
              choices: [
                { label: "$-2$", correct: true, consequence: "$5^{-2} = 1/25$. Negative exponents give fractional results." },
                { label: "$2$", correct: false, consequence: "$5^2 = 25$, not $1/25$." },
                { label: "$1/2$", correct: false, consequence: "$5^{1/2} = \\sqrt{5}$, not $1/25$." },
              ],
              reveal: "$\\log_5(1/25) = -2$. Logs of fractions less than 1 are negative." },
            { type: "summary", bullets: ["$\\log_b y$ asks 'what exponent makes $b^? = y$?'", "Treat logs and exponents as the SAME equation written two ways"] },
          ],
        },
        {
          id: "l2-6-2",
          title: "Natural log and common log",
          estimateMin: 4,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Two special logs", stake: "Two bases get short names: $\\ln = \\log_e$ and $\\log$ (no base written) = $\\log_{10}$." },
            { type: "formula-card", title: "Conventions", formula: "\\ln x = \\log_e x \\qquad \\log x = \\log_{10} x" },
            { type: "narrate", text: "$e \\approx 2.718$. Natural log is the inverse of $e^x$ — and $e^x$ is the most-natural exponential because its rate of change equals its value." },
            { type: "checkpoint", prompt: "$\\ln(e^7) = ?$",
              choices: ["$0$", "$1$", "$7$", "$e^7$"],
              answer: 2,
              explain: "$\\log_b(b^x) = x$. Here $\\ln(e^7) = 7$.",
            },
            { type: "summary", bullets: ["$\\ln$ = log base $e \\approx 2.718$", "Bare $\\log$ = log base 10"] },
          ],
        },
        {
          id: "l2-6-3",
          title: "Inverse relationship visualized",
          estimateMin: 6,
          artifact: "comparison",
          artifactInitial: {
            left: { kind: "coordinate-plane", label: "y = 2ˣ", state: { xRange: [-3, 4], yRange: [-1, 9], curves: [{ id: "e", fn: (x: number) => Math.pow(2, x), color: "var(--learn-accent)" }], features: [{ kind: "h-asymptote", id: "ha", y: 0 }] } },
            right: { kind: "coordinate-plane", label: "y = log₂(x)", state: { xRange: [-1, 9], yRange: [-3, 4], curves: [{ id: "l", fn: (x: number) => x > 0 ? Math.log2(x) : NaN, color: "var(--learn-accent)" }], features: [{ kind: "v-asymptote", id: "va", x: 0 }] } },
          },
          beats: [
            { type: "intro", title: "Mirror image across y = x", stake: "Inverse functions reflect over $y = x$. Every feature of one mirrors the other." },
            { type: "compare", text: "Exp has y-intercept $(0, 1)$. Log has x-intercept $(1, 0)$. Roles of $x$ and $y$ swap." },
            { type: "narrate", text: "Exp domain is all reals, range $(0, \\infty)$. Log domain is $(0, \\infty)$, range all reals. Same swap." },
            { type: "narrate", text: "Exp has HORIZONTAL asymptote $y = 0$. Log has VERTICAL asymptote $x = 0$. Same line, different orientation." },
            { type: "checkpoint", prompt: "If $f(x) = b^x$ passes through $(3, 27)$, what point does $f^{-1}$ pass through?",
              choices: ["$(27, 3)$", "$(3, 27)$", "$(-3, -27)$", "$(1/3, 1/27)$"],
              answer: 0,
              explain: "Inverse swaps $x$ and $y$ — point $(a, b)$ becomes $(b, a)$.",
            },
            { type: "summary", bullets: [
              "Swap domain ↔ range",
              "y-intercept of exp ↔ x-intercept of log",
              "HA of exp ↔ VA of log",
            ] },
          ],
        },
        {
          id: "l2-6-4",
          title: "Special values + identities",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Four facts to memorize", stake: "These come up everywhere. Make them reflex." },
            { type: "formula-card", title: "Four logged identities", formula: "\\begin{array}{lr} \\log_b 1 = 0 & b^0 = 1 \\\\ \\log_b b = 1 & b^1 = b \\\\ \\log_b(b^x) = x & \\text{inverse 1} \\\\ b^{\\log_b x} = x & \\text{inverse 2} \\end{array}" },
            { type: "checkpoint", prompt: "$e^{\\ln 7} = ?$",
              choices: ["$0$", "$1$", "$7$", "$e^7$"],
              answer: 2,
              explain: "$b^{\\log_b x} = x$. Here $e^{\\ln 7} = 7$.",
            },
            { type: "summary", bullets: ["$\\log_b 1 = 0$", "$\\log_b b = 1$", "Logs and exps cancel each other"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 2.7 Log/Exp Manipulation & Equations
    // ─────────────────────────────────────────────────────────
    {
      id: "t2-7",
      title: "Log/Exp Manipulation & Equations",
      blurb: "Log rules. Three solving strategies. The domain check trap.",
      lessons: [
        {
          id: "l2-7-1",
          title: "Log rules — product, quotient, power",
          estimateMin: 8,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Three rules that flip multiplication into addition", stake: "Multiplication inside a log ⇒ addition outside. Power inside ⇒ coefficient outside. That's the whole game." },
            { type: "formula-card", title: "Three rules", formula: "\\begin{array}{lr} \\log_b(MN) = \\log_b M + \\log_b N & \\text{product} \\\\ \\log_b(M/N) = \\log_b M - \\log_b N & \\text{quotient} \\\\ \\log_b(M^p) = p \\log_b M & \\text{power} \\end{array}" },
            { type: "derive", text: "Why does the product rule work? From exponent rules: $b^a \\cdot b^c = b^{a+c}$.",
              line: "\\text{Take log: } \\log_b(MN) = \\log_b M + \\log_b N" },
            { type: "checkpoint", prompt: "Expand $\\log_{10}(kz/w^2)$:",
              choices: [
                "$\\log k + \\log z - 2 \\log w$",
                "$\\log k + \\log z - \\log w^2$",
                "$\\log(k+z) - 2\\log w$",
                "Both A and B",
              ],
              answer: 3,
              explain: "Both are correct expansions; A simplifies further by applying the power rule to $\\log w^2$.",
            },
            { type: "summary", bullets: ["Multiplication inside ⇒ addition outside", "Division inside ⇒ subtraction outside", "Power inside ⇒ coefficient outside"] },
          ],
        },
        {
          id: "l2-7-2",
          title: "Combining and expanding logs",
          estimateMin: 6,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Aggressive log gymnastics", stake: "Combine multiple logs into one, or expand one into many. FRQ likes both directions." },
            { type: "derive", text: "Combine $3 \\log_b M - 2 \\log_b N + \\log_b P$ into a single log.",
              line: "= \\log_b M^3 - \\log_b N^2 + \\log_b P = \\log_b \\dfrac{M^3 P}{N^2}" },
            { type: "checkpoint", prompt: "Rewrite $3\\log x^2 - \\log\\sqrt{x}$ as a single log without negative exponents.",
              choices: ["$\\log x^{11/2}$", "$\\log x^{13/2}$", "$\\log x^{6/2}$", "$\\log x^4$"],
              answer: 0,
              explain: "$3\\log x^2 = \\log x^6$. $\\log\\sqrt{x} = \\log x^{1/2}$. Difference: $\\log x^{6 - 1/2} = \\log x^{11/2}$.",
            },
            { type: "summary", bullets: ["Power rule first to move exponents", "Then combine via product/quotient", "Result: one log of one expression"] },
          ],
        },
        {
          id: "l2-7-3",
          title: "Change of base",
          estimateMin: 4,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Switch the base", stake: "Calculators only have $\\log$ and $\\ln$. To compute $\\log_b$ for any other $b$, divide." },
            { type: "formula-card", title: "Change of base", formula: "\\log_b M = \\dfrac{\\ln M}{\\ln b} = \\dfrac{\\log M}{\\log b}" },
            { type: "derive", text: "Compute $\\log_3 5$ numerically:",
              line: "\\log_3 5 = \\dfrac{\\ln 5}{\\ln 3} \\approx \\dfrac{1.609}{1.099} \\approx 1.465" },
            { type: "summary", bullets: ["Divide by log of the base to convert", "Use $\\ln$ or $\\log$ — your choice"] },
          ],
        },
        {
          id: "l2-7-4",
          title: "Strategy: matching bases",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Exact answer when bases agree", stake: "If both sides can be written with the same base, equate the exponents. Clean, exact." },
            { type: "derive", text: "$2^{3x} = 16$. Match bases: $16 = 2^4$.",
              line: "2^{3x} = 2^4 \\Rightarrow 3x = 4 \\Rightarrow x = 4/3" },
            { type: "checkpoint", prompt: "Solve $5^x = 125$.",
              choices: ["$2$", "$3$", "$5$", "$25$"],
              answer: 1,
              explain: "$125 = 5^3$. Equating: $x = 3$.",
            },
            { type: "summary", bullets: ["When you can rewrite both sides with same base, just equate exponents"] },
          ],
        },
        {
          id: "l2-7-5",
          title: "Strategy: taking log of both sides",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Generic exponential equations", stake: "When bases can't be matched, take log of both sides — log is one-to-one, so equation is preserved." },
            { type: "derive", text: "Solve $5^x = 17$. Take $\\ln$ of both sides:",
              line: "x \\ln 5 = \\ln 17 \\Rightarrow x = \\dfrac{\\ln 17}{\\ln 5}" },
            { type: "checkpoint", prompt: "Solve $4000 \\cdot 2^{5x} + 100 = 6100$.",
              choices: ["$x = \\dfrac{\\log_2 3 - 1}{5}$", "$x = \\dfrac{\\log_2 6}{5}$", "$x = \\log_2(3/2)$", "$x = \\dfrac{3}{2}$"],
              answer: 0,
              explain: "Isolate: $2^{5x} = 3/2$. Take $\\log_2$: $5x = \\log_2 3 - 1 \\Rightarrow x = (\\log_2 3 - 1)/5$.",
            },
            { type: "summary", bullets: ["Isolate the exponential first", "Take log of both sides", "Use power rule to bring exponent down"] },
          ],
        },
        {
          id: "l2-7-6",
          title: "Strategy: substitute $u = b^x$",
          estimateMin: 6,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Quadratic-in-disguise", stake: "If you see both $b^{2x}$ and $b^x$ (or $\\sin^2 x$ and $\\sin x$), substitute. Polynomial in $u$ appears." },
            { type: "derive", text: "$2^{2x} - 5 \\cdot 2^x + 4 = 0$. Let $u = 2^x$:",
              line: "u^2 - 5u + 4 = 0 \\Rightarrow (u - 4)(u - 1) = 0 \\Rightarrow u = 4 \\text{ or } 1" },
            { type: "derive", text: "Back-substitute:",
              line: "2^x = 4 \\Rightarrow x = 2; \\quad 2^x = 1 \\Rightarrow x = 0" },
            { type: "checkpoint", prompt: "Solve $9^x - 4 \\cdot 3^x + 3 = 0$.",
              choices: ["$x = 0$ only", "$x = 1$ only", "$x = 0, 1$", "$x = 1, 2$"],
              answer: 2,
              explain: "$9^x = (3^x)^2$. Let $u = 3^x$: $u^2 - 4u + 3 = 0 \\Rightarrow u = 1, 3 \\Rightarrow x = 0, 1$.",
            },
            { type: "summary", bullets: ["Spot the $b^{2x}$ pattern", "Substitute to get a quadratic", "Back-solve both roots"] },
          ],
        },
        {
          id: "l2-7-7",
          title: "Solving log equations + the domain trap",
          estimateMin: 7,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "The trap that costs FRQ points", stake: "Solving log equations sometimes produces 'solutions' that violate domain. Always check." },
            { type: "narrate", text: "Log of a non-positive number is undefined. So $\\log_b(\\text{stuff}) = c$ requires stuff > 0." },
            { type: "derive", text: "Solve $\\ln(x^3) - \\ln x = 4$.",
              line: "\\ln(x^3 / x) = \\ln x^2 = 4 \\Rightarrow x^2 = e^4 \\Rightarrow x = \\pm e^2" },
            { type: "highlight", text: "Check domain: $\\ln(x^3)$ requires $x^3 > 0$, so $x > 0$. Reject $x = -e^2$!",
              focus: "domain" },
            { type: "checkpoint", prompt: "Solve $\\log_2(x + 3) = 5$.",
              choices: ["$x = 7$", "$x = 13$", "$x = 29$", "$x = 32$"],
              answer: 2,
              explain: "$x + 3 = 2^5 = 32 \\Rightarrow x = 29$. Verify domain: $29 + 3 = 32 > 0$. ✓",
              reteach: {
                headline: "Always check domain at the end of a log problem.",
                body: [
                  "Logs of non-positive numbers are undefined.",
                  "When you algebraically solve, you sometimes get extra 'solutions' that don't actually work in the original equation.",
                  "After finding candidate $x$ values, plug each into the ORIGINAL log expressions and verify each argument is positive.",
                ],
                followup: {
                  prompt: "Solve $\\log(x - 1) + \\log(x + 2) = \\log 4$. Valid solutions?",
                  choices: ["$x = 2$ only", "$x = -3$ only", "$x = 2$ and $x = -3$", "No solution"],
                  answer: 0,
                  explain: "Combine: $\\log((x-1)(x+2)) = \\log 4 \\Rightarrow (x-1)(x+2) = 4 \\Rightarrow x^2 + x - 6 = 0 \\Rightarrow x = 2, -3$. Check domain: $x - 1 > 0$ requires $x > 1$, so reject $-3$.",
                },
              },
            },
            { type: "summary", bullets: ["Solve algebraically", "ALWAYS check that arguments are positive", "Reject extraneous solutions"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 2.8 Logarithmic Modeling
    // ─────────────────────────────────────────────────────────
    {
      id: "t2-8",
      title: "Logarithmic Modeling",
      blurb: "Pattern recognition. Building log models. Semi-log plots.",
      lessons: [
        {
          id: "l2-8-1",
          title: "Identifying log model from data",
          estimateMin: 6,
          artifact: "function-table",
          artifactInitial: {
            columns: [{ key: "x", header: "x" }, { key: "y", header: "f(x)" }],
            rows: [{ x: 2, y: 1 }, { x: 4, y: 2 }, { x: 8, y: 3 }, { x: 16, y: 4 }, { x: 32, y: 5 }],
          },
          beats: [
            { type: "intro", title: "Logarithmic data signature", stake: "Multiplicative-x and additive-y. When inputs double (or triple, or scale by any factor) and outputs go up by a constant, it's log." },
            { type: "highlight", text: "Above: $x$ DOUBLES each row ($\\times 2$), $y$ adds 1. That's the log signature. Specifically, $f(x) = \\log_2 x$.", focus: "pattern" },
            { type: "narrate", text: "FRQ sentence: 'The function is best modeled by a logarithmic function because as the input values are multiplied by a constant factor, the output values increase by a constant amount.'" },
            { type: "checkpoint", prompt: "Table: $x = 5, 25, 125, 625$. $y = 2, 4, 6, 8$. Best model?",
              choices: ["Linear", "Quadratic", "Exponential", "Logarithmic"],
              answer: 3,
              explain: "$x$ multiplies by 5 each step, $y$ adds 2. Multiplicative input, additive output → logarithmic.",
            },
            { type: "summary", bullets: ["Equal multiplicative changes in $x$ ⇒ equal additive changes in $y$ ⇒ logarithmic", "Use this exact phrasing on the FRQ"] },
          ],
        },
        {
          id: "l2-8-2",
          title: "Building a log model",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Fit $a + b \\ln(t + 1)$ to two points", stake: "Two unknowns, two equations. Plug each point in. Solve." },
            { type: "derive", text: "Retention model $R(t) = a + b\\ln(t+1)$ with $R(0) = 75$, $R(3) = 70.84$.",
              line: "R(0) = a + b\\ln 1 = a = 75" },
            { type: "derive", text: "Then:",
              line: "R(3) = 75 + b\\ln 4 = 70.84 \\Rightarrow b = -4.16 / \\ln 4 \\approx -3.001" },
            { type: "checkpoint", prompt: "$f(t) = a \\ln t$ with $f(e) = 5$. What is $a$?",
              choices: ["$1$", "$5$", "$e$", "$\\dfrac{1}{5}$"],
              answer: 1,
              explain: "$f(e) = a \\ln e = a \\cdot 1 = a = 5$.",
            },
            { type: "summary", bullets: ["Plug each given point into the model", "Solve the small system", "Use $\\ln 1 = 0$ to simplify"] },
          ],
        },
        {
          id: "l2-8-3",
          title: "Semi-log plots",
          estimateMin: 5,
          artifact: "comparison",
          artifactInitial: {
            left: {
              kind: "coordinate-plane", label: "Linear axes",
              state: { xRange: [0, 6], yRange: [0, 100], curves: [{ id: "e", fn: (x: number) => Math.pow(2, x), color: "var(--learn-accent)" }] },
            },
            right: {
              kind: "coordinate-plane", label: "Semi-log: log y axis",
              state: { xRange: [0, 6], yRange: [0, 7], curves: [{ id: "e", fn: (x: number) => Math.log2(Math.pow(2, x)), color: "var(--learn-accent)", label: "log(2ˣ) = x" }] },
            },
          },
          beats: [
            { type: "intro", title: "Semi-log: exponential becomes linear", stake: "If data is exponential, plotting log($y$) vs $x$ produces a STRAIGHT LINE. That's the test." },
            { type: "compare", text: "Left: $2^x$ on linear axes — curves up dramatically. Right: $\\log_2(2^x) = x$ on semi-log — a straight line." },
            { type: "narrate", text: "Why: $y = ab^x \\Rightarrow \\log y = \\log a + x \\log b$. Linear in $x$." },
            { type: "checkpoint", prompt: "Data plotted on semi-log axes shows a straight line. What's the underlying relationship?",
              choices: ["Linear", "Quadratic", "Exponential", "Logarithmic"],
              answer: 2,
              explain: "Straight line on semi-log = exponential. (Straight on log-log = power law; straight on linear = linear.)",
            },
            { type: "summary", bullets: ["Exponential data shows as a straight line on semi-log axes", "Calculator regression exploits this by linearizing"] },
          ],
        },
      ],
    },
  ],
};
