// Unit 1 — Polynomial & Rational Functions (30-40% of exam)
//
// 8 topics, 32 lessons. The largest single unit on the AP Precalc exam.
// Each lesson is a walkthrough — 5-10 beats — with at least one
// interactive (predict, try-it, or checkpoint) and a summary at the end.

import type { Unit } from "../types";

// Small helpers used across lessons to keep curve-data terse.
const linear = (m: number, b: number) => (x: number) => m * x + b;
const quad = (a: number, b: number, c: number) => (x: number) => a * x * x + b * x + c;

export const UNIT_1: Unit = {
  id: "u1",
  number: 1,
  title: "Polynomial & Rational Functions",
  examWeight: "30–40%",
  coreIdeas: [
    "Co-variation and rate of change",
    "Polynomial structure: degree, zeros, end behavior",
    "Rational functions: asymptotes, holes, sign behavior",
  ],
  topics: [
    // ─────────────────────────────────────────────────────────
    // 1.1 Rate of Change
    // ─────────────────────────────────────────────────────────
    {
      id: "t1-1",
      title: "Rate of Change",
      blurb: "Average rate of change. Increasing × concavity. Reading behavior off graphs.",
      lessons: [
        {
          id: "l1-1-1",
          title: "Average Rate of Change",
          estimateMin: 6,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-1, 6],
            yRange: [-2, 18],
            curves: [{ id: "fx", fn: (x: number) => x * x, color: "var(--learn-accent)", label: "f(x) = x²" }],
          },
          beats: [
            { type: "intro", title: "Average Rate of Change", stake: "By the end of this you'll compute ARC for any function and know what it means geometrically." },
            { type: "narrate", text: "The average rate of change of $f$ from $a$ to $b$ is the slope of the secant line connecting $(a, f(a))$ and $(b, f(b))$.",
              artifact: { features: [
                { kind: "point", id: "a", x: 1, y: 1, label: "(1, 1)" },
                { kind: "point", id: "b", x: 4, y: 16, label: "(4, 16)" },
              ] } },
            { type: "formula-card", title: "ARC formula", formula: "\\text{ARC}_{[a,b]}(f) = \\dfrac{f(b) - f(a)}{b - a}",
              derivation: ["\\text{Slope of secant} = \\dfrac{\\Delta y}{\\Delta x}", "= \\dfrac{f(b) - f(a)}{b - a}"] },
            { type: "highlight", text: "Geometrically, ARC is the slope of the secant line. Draw a line from where the curve starts to where it ends — that line's slope is your ARC.",
              focus: "secant",
              artifact: { features: [
                { kind: "point", id: "a", x: 1, y: 1, label: "(1, 1)" },
                { kind: "point", id: "b", x: 4, y: 16, label: "(4, 16)" },
                { kind: "secant", id: "secant", from: [1, 1], to: [4, 16], label: "slope = 5" },
              ] } },
            { type: "derive", text: "Take $f(x) = x^2$ on $[1, 4]$. Plug in:", line: "\\text{ARC} = \\dfrac{f(4) - f(1)}{4 - 1} = \\dfrac{16 - 1}{3} = 5", because: "Square both endpoints, subtract, divide by the run." },
            { type: "predict", prompt: "What's the ARC of $f(x) = x^2$ on $[2, 5]$?",
              artifact: { features: [
                { kind: "point", id: "a", x: 2, y: 4, label: "(2, 4)" },
                { kind: "point", id: "b", x: 5, y: 25, label: "(5, 25)" },
                { kind: "secant", id: "secant", from: [2, 4], to: [5, 25] },
              ], yRange: [-2, 30] },
              choices: [
                { label: "$5$", correct: false, consequence: "That's the ARC on $[1, 4]$ — the interval shifted, so the rate did too." },
                { label: "$7$", correct: true, consequence: "Yes — $\\dfrac{25 - 4}{5 - 2} = \\dfrac{21}{3} = 7$." },
                { label: "$9$", correct: false, consequence: "Check: $f(5) - f(2) = 21$, not 27." },
              ],
              reveal: "On $[2, 5]$, ARC is 7. Same function, different interval, larger rate — quadratics have rates that grow with the interval." },
            { type: "narrate", text: "ARC is one number summarizing net change per unit input. It says nothing about what happens between the endpoints." },
            { type: "checkpoint",
              prompt: "For a linear function $f(x) = mx + b$, what's the ARC on any interval $[a, b]$?",
              choices: ["$0$", "$b$", "$m$", "Depends on $a$ and $b$"],
              answer: 2,
              explain: "Linear functions have constant slope $m$. The secant *is* the graph — same slope everywhere.",
              reteach: {
                headline: "Linear ARC = slope, always.",
                body: [
                  "The defining feature of a linear function is constant slope.",
                  "Plug it in: $\\text{ARC} = \\dfrac{m \\cdot b + c - (m \\cdot a + c)}{b - a} = \\dfrac{m(b - a)}{b - a} = m$.",
                  "No matter which interval you pick, the secant slope equals $m$.",
                ],
                followup: {
                  prompt: "$g(x) = 4x - 7$. What's the ARC on $[10, 100]$?",
                  choices: ["$-7$", "$4$", "$393$", "$397$"],
                  answer: 1,
                  explain: "Slope is 4. Linear ARC is always the slope.",
                },
              },
            },
            { type: "summary",
              bullets: [
                "Compute ARC as $\\dfrac{f(b) - f(a)}{b - a}$ for any function on any interval",
                "See ARC as the slope of the secant line",
                "Recognize that linear functions have constant ARC = slope",
              ],
              addToDeck: [
                { id: "arc-formula", front: "ARC of $f$ on $[a, b]$", back: "$\\dfrac{f(b) - f(a)}{b - a}$ — slope of the secant line" },
              ],
            },
          ],
        },
        {
          id: "l1-1-2",
          title: "Increasing × Concavity — the four phrases",
          estimateMin: 8,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-1, 7],
            yRange: [-1, 8],
            curves: [{ id: "f", fn: (x: number) => Math.log(x + 0.5) + 3, color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "The four behavior phrases", stake: "After this you'll never get tripped up by 'decreasing at an increasing rate' again. It's mechanical." },
            { type: "narrate", text: "AP Precalc loves four phrases. They sound confusing but they're just monotonicity × concavity." },
            { type: "formula-card", title: "The 2×2 table", formula: "\\begin{array}{c|c|c} & \\text{concave up} & \\text{concave down} \\\\ \\hline \\text{increasing} & \\text{inc at inc rate} & \\text{inc at dec rate} \\\\ \\text{decreasing} & \\text{dec at dec rate} & \\text{dec at inc rate} \\end{array}" },
            { type: "narrate", text: "The trick: ignore the words. Track the slope itself as a number.",
              artifact: { curves: [{ id: "f", fn: (x: number) => x * x / 6, color: "var(--learn-accent)" }], xRange: [-1, 6], yRange: [-1, 6] } },
            { type: "highlight", text: "If the slope (the number) is going UP — concave up. If the slope is going DOWN — concave down. That's it.", focus: "slope" },
            { type: "predict", prompt: "Curve descends sharply, then levels off toward $y = 1$. Behavior?",
              artifact: { curves: [{ id: "decay", fn: (x: number) => 5 / (x + 1) + 1, color: "var(--learn-accent)" }], xRange: [0, 6], yRange: [0, 7] },
              choices: [
                { label: "Decreasing at increasing rate (concave down)", correct: false, consequence: "Slope starts very negative, approaches 0. The slope is going UP, not down." },
                { label: "Decreasing at decreasing rate (concave up)", correct: true, consequence: "Right — slope goes from −large toward 0, i.e. the slope is increasing → concave up." },
                { label: "Increasing at decreasing rate", correct: false, consequence: "The function is decreasing, not increasing." },
              ],
              reveal: "Decreasing AND concave up = decreasing at a decreasing rate. The function is dropping but the drop is slowing." },
            { type: "checkpoint",
              prompt: "A graph rises sharply then levels off near a horizontal asymptote. What phrase?",
              choices: ["Increasing at increasing rate", "Increasing at decreasing rate", "Decreasing at increasing rate", "Decreasing at decreasing rate"],
              answer: 1,
              explain: "Increasing, slope shrinking toward 0 — increasing AND concave down — 'increasing at a decreasing rate.'",
            },
            { type: "summary",
              bullets: [
                "Match the four phrases to (monotonicity, concavity) pairs reflexively",
                "Use the slope-as-a-number trick to read concavity off any graph",
              ],
              addToDeck: [
                { id: "inc-inc", front: "Increasing AND concave up", back: "Increasing at an increasing rate" },
                { id: "inc-dec", front: "Increasing AND concave down", back: "Increasing at a decreasing rate" },
                { id: "dec-inc", front: "Decreasing AND concave down", back: "Decreasing at an increasing rate" },
                { id: "dec-dec", front: "Decreasing AND concave up", back: "Decreasing at a decreasing rate" },
              ],
            },
          ],
        },
        {
          id: "l1-1-3",
          title: "Reading behavior from a graph",
          estimateMin: 6,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-1, 7],
            yRange: [-3, 8],
            curves: [{ id: "f", fn: (x: number) => -0.3 * (x - 2) * (x - 2) * (x - 5) + 1, color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "Reading behavior off a graph", stake: "The exam shows you a curve and asks where it's increasing-at-decreasing-rate. Get fast at this." },
            { type: "narrate", text: "Step 1: trace left to right. Mark intervals where the curve is going UP vs DOWN — that's monotonicity." },
            { type: "narrate", text: "Step 2: same trace, but ask 'is it smiling or frowning here?' Smile = concave up, frown = concave down." },
            { type: "highlight", text: "On the curve shown: increasing on $(0, 2)$, increasing on $(2, 5)$, decreasing for $x > 5$. Mark each interval before classifying.", focus: "intervals" },
            { type: "predict", prompt: "On $(2, 5)$ above, where the curve climbs to a peak — concavity?",
              choices: [
                { label: "Concave up (smile)", correct: false, consequence: "Smile shape would curve upward. Near a peak the curve frowns." },
                { label: "Concave down (frown)", correct: true, consequence: "Near a maximum the curve always frowns down — concave down." },
              ],
              reveal: "Near any local max, concavity is DOWN. Near any local min, concavity is UP." },
            { type: "checkpoint",
              prompt: "On $(0, 2)$ the curve climbs from a valley. Best phrase?",
              choices: ["Inc at inc rate", "Inc at dec rate", "Dec at inc rate", "Dec at dec rate"],
              answer: 0,
              explain: "Climbing out of a valley = increasing, and near a min, concave up. → Inc at inc rate.",
            },
            { type: "summary", bullets: [
              "Mark monotonicity intervals first, concavity intervals second",
              "Near local max → concave down. Near local min → concave up",
              "Inflection points are where concavity flips",
            ] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 1.2 Linear, Quadratic, Polynomial Differences
    // ─────────────────────────────────────────────────────────
    {
      id: "t1-2",
      title: "Detecting Degree from a Table",
      blurb: "First differences linear, second differences quadratic, nth differences polynomial of degree n.",
      lessons: [
        {
          id: "l1-2-1",
          title: "Linear ARC is constant",
          estimateMin: 5,
          artifact: "function-table",
          artifactInitial: {
            columns: [{ key: "x", header: "x" }, { key: "y", header: "f(x)" }],
            rows: [{ x: 0, y: 3 }, { x: 1, y: 7 }, { x: 2, y: 11 }, { x: 3, y: 15 }, { x: 4, y: 19 }],
            showDifferences: 1,
          },
          beats: [
            { type: "intro", title: "Detecting linear from a table", stake: "If first differences over equal Δx are constant, the function is linear. One look." },
            { type: "narrate", text: "On the table, every Δx = 1. Compute $f(x+1) - f(x)$ down the column — those are first differences." },
            { type: "highlight", text: "Every first difference is +4. That's the slope. The function is $f(x) = 4x + 3$.", focus: "diff" },
            { type: "checkpoint",
              prompt: "A table with $\\Delta x = 2$ has $f$-values 5, 11, 17, 23, 29. What degree?",
              choices: ["Linear", "Quadratic", "Cubic", "Exponential"],
              answer: 0,
              explain: "Differences are 6, 6, 6, 6 — constant → linear. (Slope = 6/2 = 3.)",
            },
            { type: "summary", bullets: ["Constant first differences over equal Δx = linear", "The constant difference is slope × Δx"] },
          ],
        },
        {
          id: "l1-2-2",
          title: "Quadratic — constant second differences",
          estimateMin: 7,
          artifact: "function-table",
          artifactInitial: {
            columns: [{ key: "x", header: "x" }, { key: "y", header: "f(x)" }],
            rows: [{ x: 0, y: 100 }, { x: 3, y: 80 }, { x: 6, y: 62 }, { x: 9, y: 46 }, { x: 12, y: 32 }, { x: 15, y: 20 }, { x: 18, y: 10 }],
            showDifferences: 2,
          },
          beats: [
            { type: "intro", title: "Quadratic = constant 2nd differences", stake: "First differences linear? Function is linear. Second differences constant? Quadratic. Same trick, one level deeper." },
            { type: "narrate", text: "Table shows $f$ over $x = 0, 3, 6, \\ldots$. First differences vary, so it's not linear." },
            { type: "highlight", text: "But the Δ² column is constant. That's the quadratic signature.", focus: "d2" },
            { type: "narrate", text: "For a degree-2 polynomial $ax^2 + bx + c$ with step $h$, the second difference is $2ah^2$ — always the same value." },
            { type: "checkpoint",
              prompt: "$f$-values over $\\Delta x = 1$ are 1, 4, 9, 16, 25. What's the degree?",
              choices: ["Linear", "Quadratic", "Cubic", "Quartic"],
              answer: 1,
              explain: "First differences: 3, 5, 7, 9 (not constant). Second differences: 2, 2, 2 (constant!) → quadratic. ($f(x) = x^2$.)",
            },
            { type: "summary", bullets: [
              "Constant Δ² over equal Δx ⇒ quadratic",
              "The Δ² value is $2ah^2$ where $a$ is leading coefficient and $h$ is step",
            ] },
          ],
        },
        {
          id: "l1-2-3",
          title: "Polynomial degree from differences",
          estimateMin: 6,
          artifact: "function-table",
          artifactInitial: {
            columns: [{ key: "x", header: "x" }, { key: "y", header: "f(x)" }],
            rows: [{ x: 0, y: 1 }, { x: 1, y: 2 }, { x: 2, y: 9 }, { x: 3, y: 28 }, { x: 4, y: 65 }, { x: 5, y: 126 }],
            showDifferences: 3,
          },
          beats: [
            { type: "intro", title: "The general rule", stake: "Polynomial of degree $n$ ⇒ $n$-th differences are constant. Walk the column until it stabilizes." },
            { type: "narrate", text: "Above: Δ varies, Δ² varies, Δ³ is constant at 6. Polynomial of degree 3. (It's $x^3 + 1$.)" },
            { type: "predict", prompt: "If Δ⁴ is constant but Δ³ isn't, what's the degree?",
              choices: [
                { label: "3", correct: false, consequence: "Degree 3 would have constant Δ³, not Δ⁴." },
                { label: "4", correct: true, consequence: "Quartic — degree-4 polynomial." },
                { label: "5", correct: false, consequence: "Too high." },
              ],
              reveal: "Δⁿ constant ⇒ polynomial of degree exactly $n$." },
            { type: "summary", bullets: ["Walk the differences until they stabilize", "Constant Δⁿ ⇔ polynomial of degree $n$"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 1.3 Polynomial Structure
    // ─────────────────────────────────────────────────────────
    {
      id: "t1-3",
      title: "Polynomial Structure",
      blurb: "Degree, leading coefficient, zeros, multiplicity, end behavior, parity.",
      lessons: [
        {
          id: "l1-3-1",
          title: "Degree, leading coefficient, constant term",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: { xRange: [-3, 3], yRange: [-5, 8], curves: [{ id: "p", fn: (x: number) => 2 * x * x * x - 3 * x + 4, color: "var(--learn-accent)", label: "p(x)" }] },
          beats: [
            { type: "intro", title: "Anatomy of a polynomial", stake: "Three numbers tell you everything basic about a polynomial: degree, leading coefficient, constant term." },
            { type: "formula-card", title: "General form", formula: "p(x) = a_n x^n + a_{n-1} x^{n-1} + \\cdots + a_1 x + a_0" },
            { type: "narrate", text: "For $p(x) = 2x^3 - 3x + 4$: degree $n = 3$, leading coefficient $a_n = 2$, constant term $a_0 = 4 = p(0)$." },
            { type: "checkpoint", prompt: "For $p(x) = -5x^4 + 2x^2 - x + 7$, the y-intercept is:", choices: ["$-5$", "$0$", "$2$", "$7$"], answer: 3, explain: "$p(0) = 7$. The constant term IS the y-intercept." },
            { type: "summary", bullets: ["Degree = highest power", "Leading coefficient = $a_n$", "Constant term = $a_0 = p(0)$ = y-intercept"] },
          ],
        },
        {
          id: "l1-3-2",
          title: "End behavior — the 4 cases",
          estimateMin: 8,
          artifact: "coordinate-plane",
          artifactInitial: { xRange: [-4, 4], yRange: [-15, 15], curves: [{ id: "p", fn: (x: number) => x * x * x, color: "var(--learn-accent)" }] },
          beats: [
            { type: "intro", title: "End behavior is mechanical", stake: "Four cases, one table. Memorize and never miss this." },
            { type: "formula-card", title: "The four cases (from leading term $a_n x^n$)", formula: "\\begin{array}{c|c|c|c} n & a_n & x \\to +\\infty & x \\to -\\infty \\\\ \\hline \\text{even} & + & +\\infty & +\\infty \\\\ \\text{even} & - & -\\infty & -\\infty \\\\ \\text{odd} & + & +\\infty & -\\infty \\\\ \\text{odd} & - & -\\infty & +\\infty \\end{array}" },
            { type: "transform", text: "Watch — odd degree, positive leading: rises right, falls left.", artifact: { curves: [{ id: "p", fn: (x: number) => x * x * x, color: "var(--learn-accent)" }] } },
            { type: "transform", text: "Now odd degree, NEGATIVE leading. Flips both ends.", artifact: { curves: [{ id: "p", fn: (x: number) => -x * x * x, color: "var(--learn-accent)" }] } },
            { type: "transform", text: "Even degree, positive leading: both ends UP.", artifact: { curves: [{ id: "p", fn: (x: number) => x * x, color: "var(--learn-accent)" }], yRange: [-2, 15] } },
            { type: "transform", text: "Even degree, negative leading: both ends DOWN.", artifact: { curves: [{ id: "p", fn: (x: number) => -x * x, color: "var(--learn-accent)" }], yRange: [-15, 2] } },
            { type: "predict", prompt: "$g(x) = -2x^5 + 7x^4 + 3$. As $x \\to \\infty$?",
              choices: [
                { label: "$+\\infty$", correct: false, consequence: "Leading coefficient is negative." },
                { label: "$-\\infty$", correct: true, consequence: "Odd degree (5), negative leading coefficient (−2). Right end → $-\\infty$." },
              ],
              reveal: "Leading term dominates. $-2x^5$ alone tells you everything — the $7x^4 + 3$ is noise at infinity." },
            { type: "checkpoint", prompt: "$h(x) = 4x^6 - 100x^5 + 1$. As $x \\to -\\infty$?",
              choices: ["$+\\infty$", "$-\\infty$", "$0$", "Depends on the $-100x^5$ term"],
              answer: 0,
              explain: "Leading $4x^6$. Even degree, positive coefficient — both ends $\\to +\\infty$. The other terms are irrelevant at infinity.",
            },
            { type: "summary", bullets: ["End behavior is fully determined by the leading term $a_n x^n$", "Even degree: ends agree", "Odd degree: ends opposite", "Sign of $a_n$ flips everything"],
              addToDeck: [
                { id: "end-even-pos", front: "Even degree, positive leading. End behavior?", back: "Both ends $\\to +\\infty$" },
                { id: "end-odd-pos", front: "Odd degree, positive leading. End behavior?", back: "Right $\\to +\\infty$, left $\\to -\\infty$" },
              ],
            },
          ],
        },
        {
          id: "l1-3-3",
          title: "Real and complex zeros, conjugate pairs",
          estimateMin: 7,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [{ tex: "p(x) = a_n x^n + \\cdots + a_0" }] },
          beats: [
            { type: "intro", title: "Counting zeros", stake: "A degree-$n$ polynomial has exactly $n$ zeros in the complex numbers. Real ones plus complex pairs." },
            { type: "formula-card", title: "Fundamental Theorem of Algebra", formula: "\\text{Degree } n \\Rightarrow n \\text{ zeros (counting multiplicity) in } \\mathbb{C}" },
            { type: "narrate", text: "Complex zeros of real polynomials come in conjugate pairs. If $a + bi$ is a zero, so is $a - bi$." },
            { type: "derive", text: "Polynomial $g$ has zero at $x = 9.217$ (mult 2) and zero at $x = -3 + 0.251i$. Minimum degree?",
              line: "9.217\\text{ contributes }2; \\quad -3 \\pm 0.251i \\text{ contribute }2; \\quad \\text{min degree} = 4" },
            { type: "checkpoint",
              prompt: "A polynomial with real coefficients has zero at $4 - 2i$. Another zero must be:",
              choices: ["$-4 - 2i$", "$-4 + 2i$", "$4 + 2i$", "$2 + 4i$"],
              answer: 2,
              explain: "Conjugate of $4 - 2i$ is $4 + 2i$. Complex zeros always pair with their conjugates.",
              reteach: {
                headline: "Conjugate pairs — real coefficients required.",
                body: [
                  "The conjugate of $a + bi$ is $a - bi$. Sign flips on the imaginary part only.",
                  "This conjugate-pair rule only applies if the polynomial has real coefficients.",
                  "If a polynomial has $z$ as a zero, then $(x - z)$ is a factor. For real coefficients, $(x - \\bar{z})$ must also be a factor.",
                ],
                followup: {
                  prompt: "Conjugate of $-7i$?",
                  choices: ["$-7i$", "$7i$", "$7$", "$0$"],
                  answer: 1,
                  explain: "$-7i = 0 - 7i$. Conjugate flips imaginary sign: $0 + 7i = 7i$.",
                },
              },
            },
            { type: "summary", bullets: ["$n$-th degree polynomial has $n$ complex zeros", "Complex zeros pair: $a + bi$ and $a - bi$ together", "Real polynomial with $k$ complex pairs has $n - 2k$ real zeros"] },
          ],
        },
        {
          id: "l1-3-4",
          title: "Multiplicity — cross, touch, flat-cross",
          estimateMin: 6,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-3, 3], yRange: [-3, 4],
            curves: [{ id: "p", fn: (x: number) => (x - 1) * (x + 1) * (x + 1), color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "Behavior at a zero", stake: "Multiplicity tells you how the graph behaves at each zero." },
            { type: "narrate", text: "Multiplicity 1 (odd): graph CROSSES through the x-axis like a line." },
            { type: "narrate", text: "Multiplicity 2 (even): graph TOUCHES the axis and bounces back, like a parabola." },
            { type: "narrate", text: "Multiplicity 3 (odd, higher): graph crosses but FLATTENS momentarily — a cubic-style flex." },
            { type: "highlight", text: "Above: $(x-1)(x+1)^2$ has a simple zero at $x = 1$ (cross) and a double zero at $x = -1$ (touch).",
              focus: "zeros" },
            { type: "predict", prompt: "$p(x) = (x - 2)^3 (x + 1)$. Behavior at $x = 2$?",
              choices: [
                { label: "Crosses linearly", correct: false, consequence: "Multiplicity 3, not 1." },
                { label: "Crosses, but flattens", correct: true, consequence: "Right — odd multiplicity ≥ 3 means cross with a flat moment." },
                { label: "Touches and bounces", correct: false, consequence: "That's even multiplicity. 3 is odd." },
              ],
              reveal: "Odd multiplicity = cross. Even = touch. Higher odd = cross with a flat/flex." },
            { type: "checkpoint", prompt: "Graph touches axis at $x = 5$, doesn't cross. Multiplicity at 5 is:",
              choices: ["1", "2", "3", "any odd"],
              answer: 1,
              explain: "Touch-but-don't-cross requires EVEN multiplicity. Lowest is 2.",
            },
            { type: "summary", bullets: ["Mult 1 → linear crossing", "Mult 2 → parabolic touch", "Mult 3 → flat crossing"],
              addToDeck: [{ id: "mult-cross", front: "Multiplicity behavior at a zero", back: "Odd = cross. Even = touch. Higher odd = flatten while crossing." }],
            },
          ],
        },
        {
          id: "l1-3-5",
          title: "Even and odd functions",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: { xRange: [-3, 3], yRange: [-4, 5], curves: [{ id: "even", fn: (x: number) => x * x - 2, color: "var(--learn-accent)", label: "x² − 2 (even)" }] },
          beats: [
            { type: "intro", title: "Even, odd, neither", stake: "Two symmetry tests. If neither passes, the function is just 'neither'." },
            { type: "formula-card", title: "Definitions", formula: "\\text{Even: } f(-x) = f(x). \\quad \\text{Odd: } f(-x) = -f(x)." },
            { type: "narrate", text: "Even function: graph is symmetric across the y-axis. Polynomials with ONLY even-degree terms are even.",
              artifact: { curves: [{ id: "even", fn: (x: number) => x * x - 2, color: "var(--learn-accent)", label: "f(x) = x² − 2" }] } },
            { type: "narrate", text: "Odd function: graph is symmetric through the ORIGIN. Polynomials with ONLY odd-degree terms are odd.",
              artifact: { curves: [{ id: "odd", fn: (x: number) => x * x * x - 2 * x, color: "var(--learn-accent)", label: "f(x) = x³ − 2x" }] } },
            { type: "checkpoint", prompt: "$f(x) = x^4 + x^2 + 7$. Even, odd, or neither?",
              choices: ["Even", "Odd", "Neither", "Both"],
              answer: 0,
              explain: "All powers are even (and the constant $7 = 7x^0$ has even degree 0). $f(-x) = f(x)$. Even.",
            },
            { type: "summary", bullets: ["Even: only even-degree terms", "Odd: only odd-degree terms (no constant)", "Mixed degrees: neither"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 1.4 Rational Functions: Asymptotes
    // ─────────────────────────────────────────────────────────
    {
      id: "t1-4",
      title: "Rational Functions: Asymptotes",
      blurb: "Horizontal asymptote rules. Vertical asymptotes. Slant asymptotes via division.",
      lessons: [
        {
          id: "l1-4-1",
          title: "Horizontal asymptote — three degree cases",
          estimateMin: 7,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-6, 6], yRange: [-3, 5],
            curves: [{ id: "f", fn: (x: number) => (3 * x * x + 5) / (x * x - 4), color: "var(--learn-accent)" }],
            features: [{ kind: "h-asymptote", id: "ha", y: 3, label: "y = 3" }],
          },
          beats: [
            { type: "intro", title: "End behavior of $p(x)/q(x)$", stake: "Three cases. Look at numerator degree vs denominator degree. Done." },
            { type: "formula-card", title: "The rule", formula: "\\begin{array}{c|c} n < m & y = 0 \\\\ n = m & y = a_n / b_m \\\\ n = m + 1 & \\text{slant (linear)} \\\\ n > m + 1 & \\text{no HA / SA} \\end{array}" },
            { type: "narrate", text: "If numerator degree is SMALLER, the function goes to 0 at the ends. (The denominator wins the race.)",
              artifact: { curves: [{ id: "f", fn: (x: number) => 1 / (x * x + 1), color: "var(--learn-accent)" }], features: [{ kind: "h-asymptote", id: "ha", y: 0, label: "y = 0" }], yRange: [-1, 2] } },
            { type: "narrate", text: "If degrees are EQUAL, horizontal asymptote at the ratio of leading coefficients.",
              artifact: { curves: [{ id: "f", fn: (x: number) => (3 * x * x + 5) / (x * x - 4), color: "var(--learn-accent)" }], features: [{ kind: "h-asymptote", id: "ha", y: 3, label: "y = 3" }] } },
            { type: "predict", prompt: "$h(x) = \\dfrac{x^2 + 1}{2x^2 - x}$. Horizontal asymptote?",
              choices: [
                { label: "$y = 0$", correct: false, consequence: "Degrees are equal — not zero." },
                { label: "$y = 1/2$", correct: true, consequence: "Ratio of leading coefficients: $1/2$." },
                { label: "No HA", correct: false, consequence: "There is one — degrees are equal." },
              ],
              reveal: "Numerator and denominator both quadratic. HA = $a_n / b_m = 1 / 2$." },
            { type: "checkpoint", prompt: "$g(x) = \\dfrac{x^3 + 2x}{x^2 - 1}$. End behavior?",
              choices: ["HA at $y = 0$", "HA at $y = 1$", "Slant asymptote (linear)", "Grows faster than any line"],
              answer: 2,
              explain: "Numerator degree (3) is exactly one more than denominator (2) → slant asymptote.",
            },
            { type: "summary", bullets: ["$n < m$: HA at $y = 0$", "$n = m$: HA at ratio of leading coefficients", "$n = m + 1$: slant asymptote", "$n > m + 1$: no HA, grows polynomially"] },
          ],
        },
        {
          id: "l1-4-2",
          title: "Vertical asymptotes",
          estimateMin: 6,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-4, 6], yRange: [-6, 6],
            curves: [{ id: "f", fn: (x: number) => 1 / (x - 2), color: "var(--learn-accent)" }],
            features: [{ kind: "v-asymptote", id: "va", x: 2, label: "x = 2" }],
          },
          beats: [
            { type: "intro", title: "Where rational functions blow up", stake: "VA at $x = c$ when denominator is 0 and numerator isn't (after reducing)." },
            { type: "formula-card", title: "VA test", formula: "x = c \\text{ is a VA iff } q(c) = 0 \\text{ AND } p(c) \\ne 0 \\text{ (in reduced form)}" },
            { type: "narrate", text: "Always REDUCE first. If $(x - c)$ cancels between numerator and denominator, $x = c$ is a hole, not a VA." },
            { type: "checkpoint", prompt: "$f(x) = \\dfrac{(x - 3)(x + 1)}{(x - 3)(x - 5)}$. VAs?",
              choices: ["$x = 3$ and $x = 5$", "$x = 3$ only", "$x = 5$ only", "$x = -1$ and $x = 5$"],
              answer: 2,
              explain: "$(x - 3)$ cancels — that's a hole at 3, not a VA. Only $x = 5$ remains as a VA.",
            },
            { type: "summary", bullets: ["Reduce the fraction FIRST", "VA: denominator zero with numerator nonzero", "Behavior near a VA: function $\\to \\pm\\infty$"] },
          ],
        },
        {
          id: "l1-4-3",
          title: "Slant asymptotes via division",
          estimateMin: 7,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Slant asymptotes", stake: "Degree of top is exactly one more than degree of bottom ⇒ slant. Polynomial-divide to find it." },
            { type: "narrate", text: "Take $f(x) = \\dfrac{x^2 + 3x + 1}{x - 1}$. Divide $x^2 + 3x + 1$ by $x - 1$." },
            { type: "derive", text: "Long division:", line: "x^2 + 3x + 1 = (x - 1)(x + 4) + 5" },
            { type: "derive", text: "So", line: "f(x) = x + 4 + \\dfrac{5}{x - 1}" },
            { type: "highlight", text: "As $x \\to \\pm\\infty$, the remainder term $5/(x-1) \\to 0$. The function approaches the line $y = x + 4$.", focus: "asymptote" },
            { type: "checkpoint", prompt: "If $g(x) = \\dfrac{2x^3 - 5}{x^2}$, what is the slant asymptote?",
              choices: ["$y = 2x$", "$y = x$", "$y = 2x + 5$", "No slant asymptote"],
              answer: 0,
              explain: "$\\dfrac{2x^3}{x^2} = 2x$, and the $-5/x^2$ term vanishes at infinity. SA: $y = 2x$.",
            },
            { type: "summary", bullets: ["Slant only when $\\deg p = \\deg q + 1$", "Use polynomial division — quotient is the slant", "Remainder vanishes at infinity"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 1.5 Holes, Zeros, Sign Analysis
    // ─────────────────────────────────────────────────────────
    {
      id: "t1-5",
      title: "Holes, Zeros, Sign Analysis",
      blurb: "The Hole vs Zero vs VA disambiguation. Sign charts.",
      lessons: [
        {
          id: "l1-5-1",
          title: "Holes vs zeros vs VAs",
          estimateMin: 7,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [{ tex: "f(x) = \\dfrac{(x - 4)(x + 3)}{(x - 3)(x + 3)}", label: "Given" }] },
          beats: [
            { type: "intro", title: "The 3-way classifier", stake: "Same $x$-value can be a zero, a hole, or a VA depending on what cancels. Confusing this is one of the most common MCQ mistakes." },
            { type: "formula-card", title: "Decision rules", formula: "\\begin{array}{l|l} \\text{factor in } p \\text{ only} & \\text{zero} \\\\ \\text{factor in both} & \\text{hole} \\\\ \\text{factor in } q \\text{ only} & \\text{VA} \\end{array}" },
            { type: "derive", text: "For $f(x) = \\dfrac{(x-4)(x+3)}{(x-3)(x+3)}$, classify each factor:",
              line: "(x + 3) \\text{ is in both} \\Rightarrow \\text{hole at } x = -3" },
            { type: "derive", text: "Then:",
              line: "(x - 4) \\text{ is in numerator only} \\Rightarrow \\text{zero at } x = 4" },
            { type: "derive", text: "And:",
              line: "(x - 3) \\text{ is in denominator only} \\Rightarrow \\text{VA at } x = 3" },
            { type: "checkpoint", prompt: "$g(x) = \\dfrac{(x-2)(x-5)}{(x+1)(x-2)}$. At $x = 2$?",
              choices: ["Zero", "Hole", "VA", "Nothing"],
              answer: 1,
              explain: "$(x-2)$ appears in both → cancels → hole at $x = 2$.",
              reteach: {
                headline: "Always FACTOR first.",
                body: [
                  "Before reading off zeros / holes / VAs, factor numerator and denominator completely.",
                  "Match factors: same factor in both ⇒ hole. Numerator only ⇒ zero. Denominator only ⇒ VA.",
                  "After cancellation, the reduced fraction tells you ALL behavior except where you canceled.",
                ],
                followup: {
                  prompt: "$h(x) = \\dfrac{(x+4)(x-1)}{(x-1)^2(x+6)}$. At $x = 1$?",
                  choices: ["Zero", "Hole", "VA", "Both hole and VA"],
                  answer: 2,
                  explain: "$(x - 1)$ appears once in numerator, twice in denominator. ONE cancels, but one $(x-1)$ stays in denominator → VA at $x = 1$.",
                },
              },
            },
            { type: "summary", bullets: [
              "Factor first. Always.",
              "Hole = common factor that cancels completely",
              "If denominator power exceeds numerator power for a factor, residual VA",
            ] },
          ],
        },
        {
          id: "l1-5-2",
          title: "Hole y-coordinate via limit notation",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Where is the hole?", stake: "The hole has an x-coordinate (the canceled factor) and a y-coordinate (evaluate the reduced function at that x). FRQ rubric wants limit notation." },
            { type: "narrate", text: "Step 1: factor, cancel. Step 2: evaluate the REDUCED expression at the hole's x." },
            { type: "derive", text: "For $g(x) = \\dfrac{x^2 - x - 12}{x^2 - 9} = \\dfrac{(x-4)(x+3)}{(x-3)(x+3)}$:",
              line: "(x + 3) \\text{ cancels} \\Rightarrow \\text{reduced: } \\dfrac{x - 4}{x - 3}" },
            { type: "derive", text: "Evaluate the reduced expression at $x = -3$:",
              line: "\\lim_{x \\to -3} g(x) = \\dfrac{-3 - 4}{-3 - 3} = \\dfrac{-7}{-6} = \\dfrac{7}{6}" },
            { type: "highlight", text: "Write the answer as $\\lim_{x \\to -3} g(x) = 7/6$. The hole is at $(-3, 7/6)$.", focus: "answer" },
            { type: "checkpoint", prompt: "$f(x) = \\dfrac{x^2 - 4}{x - 2}$. Hole y-coordinate?",
              choices: ["$0$", "$2$", "$4$", "Undefined"],
              answer: 2,
              explain: "$f = \\dfrac{(x-2)(x+2)}{x-2}$. Reduced: $x + 2$. At $x = 2$: $\\lim_{x \\to 2} f(x) = 4$.",
            },
            { type: "summary", bullets: ["Reduce, then evaluate at the hole's x", "Use limit notation on FRQs: $\\lim_{x \\to c} f(x) = L$"] },
          ],
        },
        {
          id: "l1-5-3",
          title: "Sign analysis on a number line",
          estimateMin: 6,
          artifact: "number-line",
          artifactInitial: {
            range: [-5, 5],
            marks: [
              { x: -2, kind: "zero", label: "−2" },
              { x: 1, kind: "va", label: "VA at 1" },
              { x: 3, kind: "zero", label: "3" },
            ],
            regions: [
              { from: -5, to: -2, sign: "+" },
              { from: -2, to: 1, sign: "-" },
              { from: 1, to: 3, sign: "+" },
              { from: 3, to: 5, sign: "-" },
            ],
          },
          beats: [
            { type: "intro", title: "Where is the function positive?", stake: "Mark zeros, holes, VAs on a line. Test one point per interval. Easy points on the FRQ." },
            { type: "narrate", text: "For $r(x) = \\dfrac{(x + 2)(x - 3)}{(x - 1)}$: zeros at $-2$ and $3$, VA at $1$. Three marks split the line into 4 intervals." },
            { type: "narrate", text: "Pick one test value per interval. Substitute. The sign of $r$ is constant on each interval (signs change only at zeros and VAs)." },
            { type: "highlight", text: "Test $x = 0$ in $(-2, 1)$: $\\dfrac{(0+2)(0-3)}{(0-1)} = \\dfrac{-6}{-1} = 6 > 0$. Wait — that's positive!", focus: "test" },
            { type: "narrate", text: "Recheck the visualization above — the second interval is NEGATIVE. Let me recompute: $\\dfrac{(2)(-3)}{-1} = \\dfrac{-6}{-1} = +6$. So $(-2, 1)$ is positive, not negative. Always recheck signs!" },
            { type: "checkpoint", prompt: "For $f(x) = (x - 4)(x + 1)$, on what interval is $f(x) < 0$?",
              choices: ["$x < -1$", "$-1 < x < 4$", "$x > 4$", "$f$ is never negative"],
              answer: 1,
              explain: "Parabola opens up with zeros at $-1$ and $4$. Below the axis between the zeros.",
            },
            { type: "summary", bullets: ["Mark zeros / holes / VAs as boundaries", "Test one point per interval", "Sign is constant inside each interval"] },
          ],
        },
        {
          id: "l1-5-4",
          title: "Domain of h/g",
          estimateMin: 4,
          artifact: "number-line",
          artifactInitial: {
            range: [-5, 5],
            marks: [
              { x: -3, kind: "va", label: "−3" },
              { x: 0, kind: "va", label: "0" },
              { x: 6, kind: "va", label: "6 (off line)" },
            ],
            regions: [{ from: -5, to: -3, sign: "?" }, { from: -3, to: 0, sign: "?" }, { from: 0, to: 5, sign: "?" }],
          },
          beats: [
            { type: "intro", title: "Where is $h/g$ undefined?", stake: "Domain of $h(x)/g(x)$ excludes zeros of $g$ (after cancellation). Quick FRQ-style move." },
            { type: "narrate", text: "$g(x) = x^3 - 3x^2 - 18x = x(x-6)(x+3)$. Zeros at $0$, $6$, $-3$. $h(x) = x^2 - 2x - 35 = (x-7)(x+5)$. Zeros at $7$, $-5$." },
            { type: "highlight", text: "No common factors. Domain excludes only the zeros of $g$: $\\{x : x \\ne -3, 0, 6\\}$.", focus: "excluded" },
            { type: "checkpoint", prompt: "$f(x) = \\dfrac{x + 1}{x^2 - 9}$. Domain excludes:",
              choices: ["$x \\ne -1$", "$x \\ne \\pm 3$", "$x \\ne 3$", "Domain is all reals"],
              answer: 1,
              explain: "$x^2 - 9 = (x-3)(x+3) = 0$ at $x = \\pm 3$. Numerator doesn't cancel either.",
            },
            { type: "summary", bullets: ["Factor numerator and denominator", "Cancel common factors (those become holes)", "Domain excludes leftover denominator zeros"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 1.6 Equivalent Representations
    // ─────────────────────────────────────────────────────────
    {
      id: "t1-6",
      title: "Equivalent Representations",
      blurb: "Standard / factored / vertex form. Long division. Synthetic division. Remainder theorem.",
      lessons: [
        {
          id: "l1-6-1",
          title: "Standard ↔ factored ↔ vertex",
          estimateMin: 6,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Three ways to write the same quadratic", stake: "Each form reveals something different. Pick the form that surfaces what the question wants." },
            { type: "formula-card", title: "Three forms", formula: "\\begin{array}{ll} \\text{Standard:} & ax^2 + bx + c \\\\ \\text{Factored:} & a(x - r_1)(x - r_2) \\\\ \\text{Vertex:} & a(x - h)^2 + k \\end{array}" },
            { type: "narrate", text: "Standard form shows the y-intercept ($c$). Factored shows the zeros ($r_1, r_2$). Vertex shows the extremum and axis of symmetry." },
            { type: "derive", text: "Convert $x^2 - 6x + 8$ to factored form.", line: "x^2 - 6x + 8 = (x - 2)(x - 4)", because: "Find two numbers multiplying to 8, summing to $-6$: $-2$ and $-4$." },
            { type: "derive", text: "Convert $x^2 - 6x + 8$ to vertex form (complete the square).",
              line: "(x - 3)^2 - 9 + 8 = (x - 3)^2 - 1", because: "Half of $-6$ is $-3$, squared is $9$. Add and subtract." },
            { type: "checkpoint", prompt: "Vertex of $y = 2(x + 1)^2 - 5$?",
              choices: ["$(1, -5)$", "$(-1, -5)$", "$(-1, 5)$", "$(2, -5)$"],
              answer: 1,
              explain: "$(x - h)^2 \\Rightarrow h = -1$. Vertex is at $(h, k) = (-1, -5)$.",
            },
            { type: "summary", bullets: ["Standard: y-intercept", "Factored: zeros", "Vertex: extremum location"] },
          ],
        },
        {
          id: "l1-6-2",
          title: "Polynomial long division",
          estimateMin: 7,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Long division for polynomials", stake: "Same algorithm as long division on numbers, but with x's instead of digits." },
            { type: "narrate", text: "Divide $x^3 + 2x^2 - 5x + 6$ by $x - 2$." },
            { type: "derive", text: "Step 1: $x^3 / x = x^2$. Multiply $x^2 \\cdot (x - 2) = x^3 - 2x^2$. Subtract.",
              line: "x^3 + 2x^2 - 5x + 6 - (x^3 - 2x^2) = 4x^2 - 5x + 6" },
            { type: "derive", text: "Step 2: $4x^2 / x = 4x$. Multiply $4x \\cdot (x - 2) = 4x^2 - 8x$. Subtract.",
              line: "4x^2 - 5x + 6 - (4x^2 - 8x) = 3x + 6" },
            { type: "derive", text: "Step 3: $3x / x = 3$. Multiply $3 \\cdot (x - 2) = 3x - 6$. Subtract.",
              line: "3x + 6 - (3x - 6) = 12" },
            { type: "derive", text: "Quotient $x^2 + 4x + 3$, remainder $12$:",
              line: "\\dfrac{x^3 + 2x^2 - 5x + 6}{x - 2} = x^2 + 4x + 3 + \\dfrac{12}{x - 2}" },
            { type: "summary", bullets: ["Long division algorithm: divide leading, multiply back, subtract, repeat", "Always result = quotient + remainder/divisor"] },
          ],
        },
        {
          id: "l1-6-3",
          title: "Synthetic division",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Fast division for $(x - c)$ divisors", stake: "Only works when divisor is $(x - c)$. Much faster than long division — just numbers." },
            { type: "narrate", text: "For $\\dfrac{x^3 + 2x^2 - 5x + 6}{x - 2}$ with $c = 2$:" },
            { type: "derive", text: "Set up: bring down $1$, multiply by 2, add to next, etc.",
              line: "\\begin{array}{c|cccc} 2 & 1 & 2 & -5 & 6 \\\\ & & 2 & 8 & 6 \\\\ \\hline & 1 & 4 & 3 & 12 \\end{array}" },
            { type: "highlight", text: "Bottom row reads coefficients: $1, 4, 3$ are quotient $x^2 + 4x + 3$. Last number $12$ is the remainder.", focus: "result" },
            { type: "summary", bullets: ["Synthetic = numerical shortcut for dividing by $(x - c)$", "Last number on the bottom row is the remainder", "Other numbers are the quotient coefficients"] },
          ],
        },
        {
          id: "l1-6-4",
          title: "Remainder and factor theorems",
          estimateMin: 5,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "The two theorems that link zeros and division", stake: "Two facts that let you test factors fast without doing the full division." },
            { type: "formula-card", title: "Remainder theorem", formula: "p(c) = \\text{remainder when dividing } p(x) \\text{ by } (x - c)" },
            { type: "formula-card", title: "Factor theorem", formula: "(x - c) \\text{ is a factor of } p(x) \\iff p(c) = 0" },
            { type: "narrate", text: "Want to test whether $(x - 3)$ divides $p(x) = x^3 - 7x + 6$? Compute $p(3)$. If zero, yes." },
            { type: "derive", text: "$p(3) = 27 - 21 + 6 = 12$.", line: "p(3) = 12 \\ne 0 \\Rightarrow (x - 3) \\text{ is NOT a factor}" },
            { type: "checkpoint", prompt: "When $p(x)$ is divided by $(x + 2)$, the remainder is 0. What does that tell you?",
              choices: ["$p(2) = 0$", "$p(-2) = 0$", "$p$ has degree 2", "$x = 2$ is a zero"],
              answer: 1,
              explain: "Divisor $(x + 2) = (x - (-2))$, so $c = -2$. By the remainder theorem, $p(-2) = 0$, i.e., $-2$ is a zero.",
            },
            { type: "summary", bullets: ["$p(c) = $ remainder when divided by $(x - c)$", "$(x - c)$ is a factor iff $p(c) = 0$"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 1.7 Transformations
    // ─────────────────────────────────────────────────────────
    {
      id: "t1-7",
      title: "Transformations",
      blurb: "a, b, h, k mechanics. The 'horizontal is backwards' trap. Range under transformation.",
      lessons: [
        {
          id: "l1-7-1",
          title: "Vertical shifts and dilations ($a$ and $k$)",
          estimateMin: 6,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-4, 4], yRange: [-3, 8],
            curves: [{ id: "parent", fn: (x: number) => x * x, color: "var(--learn-accent)", label: "f(x) = x²", dashed: true }],
          },
          beats: [
            { type: "intro", title: "Vertical transformations", stake: "$g(x) = a \\cdot f(x) + k$. $a$ stretches vertically, $k$ shifts up/down. Both straightforward." },
            { type: "transform", text: "Add 3 to the function. Whole graph slides up.", artifact: {
              curves: [
                { id: "parent", fn: (x: number) => x * x, color: "var(--learn-ink-mute)", label: "x²", dashed: true },
                { id: "shifted", fn: (x: number) => x * x + 3, color: "var(--learn-accent)", label: "x² + 3" },
              ] } },
            { type: "transform", text: "Now multiply by 2. The graph stretches vertically by factor 2.", artifact: {
              curves: [
                { id: "parent", fn: (x: number) => x * x, color: "var(--learn-ink-mute)", label: "x²", dashed: true },
                { id: "stretched", fn: (x: number) => 2 * x * x, color: "var(--learn-accent)", label: "2x²" },
              ] } },
            { type: "highlight", text: "If $a < 0$, the graph also reflects across the x-axis.", focus: "reflect", artifact: {
              curves: [
                { id: "parent", fn: (x: number) => x * x, color: "var(--learn-ink-mute)", label: "x²", dashed: true },
                { id: "flipped", fn: (x: number) => -x * x, color: "var(--learn-accent)", label: "−x²" },
              ], yRange: [-8, 4] } },
            { type: "checkpoint", prompt: "$g(x) = -3f(x) + 5$. If $f$ has range $[1, 4]$, what's the range of $g$?",
              choices: ["$[-7, 2]$", "$[2, 8]$", "$[-7, 4]$", "$[-12, -3]$"],
              answer: 0,
              explain: "Multiply by $-3$: range becomes $[-12, -3]$ (signs flip, order flips). Add 5: $[-7, 2]$.",
            },
            { type: "summary", bullets: ["$+k$ shifts up by $k$", "$\\times a$ scales vertically", "$a < 0$ reflects over x-axis"] },
          ],
        },
        {
          id: "l1-7-2",
          title: "Horizontal shifts and dilations ($h$ and $b$)",
          estimateMin: 8,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-5, 5], yRange: [-1, 9],
            curves: [{ id: "parent", fn: (x: number) => x * x, color: "var(--learn-ink-mute)", dashed: true, label: "f(x)" }],
          },
          beats: [
            { type: "intro", title: "Horizontal: it feels backwards", stake: "This is where students get burned. The sign and the factor work backwards from your intuition." },
            { type: "formula-card", title: "The trap", formula: "g(x) = f(b(x - h)): \\text{shift right by } h \\text{ (positive), compress by } 1/|b|" },
            { type: "transform", text: "Replace $x$ with $(x - 2)$. The graph shifts RIGHT by 2, not left.", artifact: {
              curves: [
                { id: "parent", fn: (x: number) => x * x, color: "var(--learn-ink-mute)", dashed: true, label: "x²" },
                { id: "shifted", fn: (x: number) => (x - 2) * (x - 2), color: "var(--learn-accent)", label: "(x − 2)²" },
              ] } },
            { type: "narrate", text: "Why? When $x = 2$, $(x - 2) = 0$ — the same input the parent had at $x = 0$. So the value 'at $x = 2$' is the parent's value 'at 0'. Right shift." },
            { type: "transform", text: "Replace $x$ with $2x$. The graph COMPRESSES horizontally by factor 1/2.", artifact: {
              curves: [
                { id: "parent", fn: (x: number) => x * x, color: "var(--learn-ink-mute)", dashed: true, label: "x²" },
                { id: "compressed", fn: (x: number) => (2 * x) * (2 * x), color: "var(--learn-accent)", label: "(2x)²" },
              ] } },
            { type: "predict", prompt: "$g(x) = f(\\tfrac{1}{2} x)$. What happens?",
              choices: [
                { label: "Compresses by factor 2", correct: false, consequence: "$\\tfrac{1}{2}$ is small — but small inside means stretching." },
                { label: "Stretches by factor 2", correct: true, consequence: "Inside-factor of $1/b$ stretches by $|1/b|$ when $|b| < 1$. So factor $\\tfrac{1}{2}$ inside ⇒ stretch by 2." },
              ],
              reveal: "Inside-the-parentheses transformations work BACKWARDS: bigger factor inside compresses, smaller stretches." },
            { type: "checkpoint", prompt: "$g(x) = f(3x - 6) = f(3(x - 2))$. Transformations on $f$?",
              choices: [
                "Shift right 6, compress by 1/3",
                "Shift right 2, compress by 1/3",
                "Shift right 2, stretch by 3",
                "Shift left 2, compress by 1/3",
              ],
              answer: 1,
              explain: "Factor out the 3 first: $f(3(x - 2))$. Horizontal shift right by 2 (sign flips), horizontal compress by $1/|3| = 1/3$.",
              reteach: {
                headline: "Factor first, then read off.",
                body: [
                  "Always rewrite inside as $b(x - h)$ — factor out $b$ from inside.",
                  "Then $h$ is shift (right if positive), $1/|b|$ is the compression factor.",
                  "If you don't factor, you'll mis-read the shift.",
                ],
                followup: {
                  prompt: "$g(x) = f(2x + 4) = f(2(x + 2))$. Horizontal shift?",
                  choices: ["Right 4", "Left 4", "Right 2", "Left 2"],
                  answer: 3,
                  explain: "Factor: $f(2(x + 2)) = f(2(x - (-2)))$. $h = -2$, so shift left 2.",
                },
              },
            },
            { type: "summary", bullets: [
              "Factor inside as $b(x - h)$ FIRST",
              "$h$ = horizontal shift (sign flipped from what you'd expect)",
              "$b$ inside: $|b| > 1$ compresses, $|b| < 1$ stretches",
              "$b < 0$ also reflects over y-axis",
            ] },
          ],
        },
        {
          id: "l1-7-3",
          title: "Reflections",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [-3, 3], yRange: [-3, 5],
            curves: [{ id: "p", fn: (x: number) => Math.sqrt(x + 0.1), color: "var(--learn-accent)" }],
          },
          beats: [
            { type: "intro", title: "Two reflections", stake: "Negative $a$ flips over x-axis. Negative $b$ flips over y-axis." },
            { type: "transform", text: "$-f(x)$: reflect over x-axis.", artifact: {
              curves: [
                { id: "orig", fn: (x: number) => Math.sqrt(Math.max(x, 0) + 0.1), color: "var(--learn-ink-mute)", dashed: true },
                { id: "flipped", fn: (x: number) => -Math.sqrt(Math.max(x, 0) + 0.1), color: "var(--learn-accent)" },
              ], yRange: [-3, 3] } },
            { type: "transform", text: "$f(-x)$: reflect over y-axis.", artifact: {
              curves: [
                { id: "orig", fn: (x: number) => x >= 0 ? Math.sqrt(x + 0.1) : NaN, color: "var(--learn-ink-mute)", dashed: true },
                { id: "flipped", fn: (x: number) => x <= 0 ? Math.sqrt(-x + 0.1) : NaN, color: "var(--learn-accent)" },
              ] } },
            { type: "checkpoint", prompt: "$g(x) = -f(-x)$. What reflections?",
              choices: ["Over x-axis only", "Over y-axis only", "Over both axes (= rotation 180°)", "Neither"],
              answer: 2,
              explain: "Negative outside ⇒ over x-axis. Negative inside ⇒ over y-axis. Both = 180° rotation about origin.",
            },
            { type: "summary", bullets: ["Negative $a$: over x-axis", "Negative $b$ (inside): over y-axis"] },
          ],
        },
        {
          id: "l1-7-4",
          title: "Range under transformations",
          estimateMin: 5,
          artifact: "function-table",
          artifactInitial: {
            columns: [{ key: "step", header: "Step" }, { key: "range", header: "Range" }],
            rows: [
              { step: "f", range: "[−2, 7]" },
              { step: "2·f", range: "[−4, 14]" },
              { step: "2·f + 3", range: "[−1, 17]" },
            ],
          },
          beats: [
            { type: "intro", title: "Range tracking", stake: "Horizontal transformations don't change the range. Vertical ones do — and the order matters." },
            { type: "narrate", text: "If $f$ has range $[m, M]$, then $a \\cdot f$ has range $[am, aM]$ when $a > 0$, or $[aM, am]$ when $a < 0$ (order flips!). Adding $k$ shifts both bounds by $k$." },
            { type: "checkpoint", prompt: "$f$ has range $[-2, 7]$. Range of $-3f + 5$?",
              choices: ["$[-16, 11]$", "$[-16, 26]$", "$[11, -16]$", "$[-1, 26]$"],
              answer: 0,
              explain: "$-3 \\cdot [-2, 7] = [-21, 6]$ → reorder → $[-21, 6]$. Plus 5: $[-16, 11]$.",
            },
            { type: "summary", bullets: ["Horizontal moves don't change range", "Vertical: multiply bounds, then shift", "If $a < 0$, swap min and max"] },
          ],
        },
        {
          id: "l1-7-5",
          title: "Order of operations on transformations",
          estimateMin: 6,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Inside vs outside", stake: "Inside-the-parens (horizontal) operations: shift then dilate. Outside (vertical): dilate then shift. Reading order matters for full transformations." },
            { type: "narrate", text: "For $g(x) = a f(b(x - h)) + k$: read inside-out for horizontal, outside-in for vertical." },
            { type: "derive", text: "Take $g(x) = 3 f(\\tfrac{1}{2}(x - 4)) + 5$.",
              line: "\\text{horizontal: shift right 4, then stretch by 2}" },
            { type: "derive", text: "Continuing:",
              line: "\\text{vertical: stretch by 3, then shift up 5}" },
            { type: "checkpoint", prompt: "If $f(-2) = 5$ and $g(x) = 3 f(\\tfrac{1}{2} x) + 5$, find $g(-4)$.",
              choices: ["$10$", "$15$", "$20$", "$25$"],
              answer: 2,
              explain: "$g(-4) = 3 f(\\tfrac{1}{2} \\cdot -4) + 5 = 3 f(-2) + 5 = 3 \\cdot 5 + 5 = 20$.",
            },
            { type: "summary", bullets: ["Inside parens = horizontal", "Outside = vertical", "Plug in carefully when evaluating"] },
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────────
    // 1.8 Modeling
    // ─────────────────────────────────────────────────────────
    {
      id: "t1-8",
      title: "Modeling",
      blurb: "Pick the right model class. Residuals. Quadratic from 3 points.",
      lessons: [
        {
          id: "l1-8-1",
          title: "Function model selection",
          estimateMin: 7,
          artifact: "function-table",
          artifactInitial: {
            columns: [{ key: "x", header: "x" }, { key: "y", header: "y" }],
            rows: [{ x: 2, y: 1 }, { x: 4, y: 2 }, { x: 8, y: 3 }, { x: 16, y: 4 }, { x: 32, y: 5 }],
          },
          beats: [
            { type: "intro", title: "Pick the right model class", stake: "Five model classes, five diagnostic patterns. Recognize the pattern, name the model. Confident sentence on the FRQ." },
            { type: "formula-card", title: "Decision rules", formula: "\\begin{array}{l|l} \\text{constant } \\Delta y & \\text{linear} \\\\ \\text{constant } \\Delta^2 y & \\text{quadratic} \\\\ \\text{constant } \\Delta^n y & \\text{polynomial deg } n \\\\ \\text{constant ratio } y_{i+1}/y_i & \\text{exponential} \\\\ \\times \\text{ change in } x \\Rightarrow \\text{constant } \\Delta y & \\text{logarithmic} \\end{array}" },
            { type: "highlight", text: "In the table above: $x$ DOUBLES each step ($\\times 2$), and $y$ INCREASES BY 1 each step (additive). That's the logarithmic signature.", focus: "pattern" },
            { type: "narrate", text: "FRQ-ready sentence: 'As input values are multiplied by a constant factor, output values increase by a constant amount. That's the defining characteristic of a logarithmic function.'" },
            { type: "predict", prompt: "Table: $x$ = 0, 1, 2, 3, 4. $y$ = 2, 6, 18, 54, 162. Model?",
              choices: [
                { label: "Linear", correct: false, consequence: "First differences aren't constant." },
                { label: "Quadratic", correct: false, consequence: "Check second differences — not constant either." },
                { label: "Exponential", correct: true, consequence: "Each $y$ is 3× the previous. Constant ratio → exponential." },
              ],
              reveal: "Exponential. Specifically $y = 2 \\cdot 3^x$." },
            { type: "summary", bullets: [
              "Constant $\\Delta y$ over equal $\\Delta x$ ⇒ linear",
              "Constant ratio ⇒ exponential",
              "Multiplicative $x$, additive $y$ ⇒ logarithmic",
            ] },
          ],
        },
        {
          id: "l1-8-2",
          title: "Residual plots",
          estimateMin: 5,
          artifact: "comparison",
          artifactInitial: {
            left: {
              kind: "coordinate-plane",
              label: "Good fit — random scatter",
              state: {
                xRange: [0, 10], yRange: [-2, 2],
                features: [
                  { kind: "point", id: "a1", x: 1, y: 0.4 },
                  { kind: "point", id: "a2", x: 2, y: -0.6 },
                  { kind: "point", id: "a3", x: 3, y: 0.1 },
                  { kind: "point", id: "a4", x: 4, y: -0.4 },
                  { kind: "point", id: "a5", x: 5, y: 0.7 },
                  { kind: "point", id: "a6", x: 6, y: -0.2 },
                  { kind: "point", id: "a7", x: 7, y: 0.5 },
                  { kind: "point", id: "a8", x: 8, y: -0.3 },
                  { kind: "point", id: "a9", x: 9, y: 0.2 },
                ],
              },
            },
            right: {
              kind: "coordinate-plane",
              label: "Bad fit — clear pattern",
              state: {
                xRange: [0, 10], yRange: [-2, 2],
                features: [
                  { kind: "point", id: "b1", x: 1, y: 1.4 },
                  { kind: "point", id: "b2", x: 2, y: 0.6 },
                  { kind: "point", id: "b3", x: 3, y: -0.1 },
                  { kind: "point", id: "b4", x: 4, y: -0.8 },
                  { kind: "point", id: "b5", x: 5, y: -1.2 },
                  { kind: "point", id: "b6", x: 6, y: -1.0 },
                  { kind: "point", id: "b7", x: 7, y: -0.5 },
                  { kind: "point", id: "b8", x: 8, y: 0.4 },
                  { kind: "point", id: "b9", x: 9, y: 1.3 },
                ],
              },
            },
          },
          beats: [
            { type: "intro", title: "Reading residual plots", stake: "Residual = actual − predicted. RANDOM scatter = good model. PATTERN in residuals = bad model." },
            { type: "compare", text: "Left: residuals scatter randomly. No structure. The model captures the trend." },
            { type: "compare", text: "Right: residuals form a clear arc. The model is missing curvature — the true relationship is nonlinear and we fit a line." },
            { type: "narrate", text: "Sign of a residual tells direction. NEGATIVE residual = model overestimates. POSITIVE = underestimates." },
            { type: "checkpoint", prompt: "A residual plot for a linear model shows a clear U-shape. Conclusion?",
              choices: [
                "Linear model is appropriate — small residuals",
                "Linear model is NOT appropriate — pattern suggests nonlinear",
                "The data is noisy",
                "Need more data",
              ],
              answer: 1,
              explain: "Patterned residuals signal misspecified model. A U-shape suggests quadratic or higher.",
            },
            { type: "summary", bullets: ["Random scatter = good fit", "Patterned = model is wrong", "Negative residual = overestimate. Positive = underestimate"] },
          ],
        },
        {
          id: "l1-8-3",
          title: "Quadratic from 3 points",
          estimateMin: 7,
          artifact: "algebra-ladder",
          artifactInitial: { lines: [] },
          beats: [
            { type: "intro", title: "Three points define a parabola", stake: "Given three $(x, y)$ pairs, plug each into $f(x) = ax^2 + bx + c$ to get a 3×3 system. Solve. That's it." },
            { type: "narrate", text: "Take Spotify subscribers: 2015 (x=0, y=28), 2018 (x=3, y=96), 2021 (x=6, y=180)." },
            { type: "derive", text: "Plug in each point:",
              line: "\\begin{array}{l} f(0) = c = 28 \\\\ f(3) = 9a + 3b + c = 96 \\\\ f(6) = 36a + 6b + c = 180 \\end{array}" },
            { type: "derive", text: "Substitute $c = 28$:",
              line: "9a + 3b = 68; \\quad 36a + 6b = 152" },
            { type: "derive", text: "Eliminate $b$ — multiply first by 2 and subtract:",
              line: "(36a + 6b) - 2(9a + 3b) = 152 - 136 \\Rightarrow 18a = 16 \\Rightarrow a = 8/9" },
            { type: "derive", text: "Back-solve:",
              line: "b = (68 - 8)/3 = 20; \\quad f(x) = \\tfrac{8}{9} x^2 + 20x + 28" },
            { type: "checkpoint", prompt: "A parabola passes through $(0, 5)$, $(1, 8)$, $(2, 13)$. Leading coefficient $a$?",
              choices: ["$1$", "$2$", "$3$", "$5$"],
              answer: 0,
              explain: "$c = 5$, $a + b = 3$, $4a + 2b = 8 \\Rightarrow 2a + b = 4$. Subtract: $a = 1$.",
            },
            { type: "summary", bullets: ["Plug each point into $ax^2 + bx + c$ to get a 3×3 system", "Solve by substitution or elimination", "Concavity (sign of $a$) tells you whether ARC grows or shrinks"] },
          ],
        },
        {
          id: "l1-8-4",
          title: "Direct and inverse proportion",
          estimateMin: 5,
          artifact: "coordinate-plane",
          artifactInitial: {
            xRange: [0, 6], yRange: [0, 8],
            curves: [{ id: "direct", fn: (x: number) => 2 * x, color: "var(--learn-accent)", label: "y = 2x (direct)" }],
          },
          beats: [
            { type: "intro", title: "Two simple models with their own vocabulary", stake: "Direct proportion: $y = kx$. Inverse proportion: $y = k/x$. The FRQ uses these phrases verbatim." },
            { type: "formula-card", title: "Two models", formula: "\\text{Direct: } y = kx \\qquad \\text{Inverse: } y = \\dfrac{k}{x}" },
            { type: "transform", text: "Inverse proportion: $y = 6/x$. Hyperbola — large $x$ ⇒ small $y$.", artifact: {
              curves: [{ id: "inverse", fn: (x: number) => 6 / x, color: "var(--learn-accent)", label: "y = 6/x" }],
              xRange: [0.5, 6], yRange: [0, 12] } },
            { type: "checkpoint", prompt: "$y$ is inversely proportional to $x$, and $y = 4$ when $x = 6$. Find $y$ when $x = 8$.",
              choices: ["$3$", "$4$", "$5$", "$32$"],
              answer: 0,
              explain: "$y = k/x$, so $k = xy = 24$. At $x = 8$: $y = 24/8 = 3$.",
            },
            { type: "summary", bullets: ["Direct: $y = kx$, $k$ found from one data point", "Inverse: $y = k/x$, $k = xy$ (constant for the dataset)"] },
          ],
        },
      ],
    },
  ],
};
